- src/Index.ts
- src/ui/CurrentTab/CurrentTab.ts
- src/utils/Dom.ts
- test/MockEnvironment.ts
- test/Test.ts
- test/ui/CurrentTabTest.ts
- tsconfig.json
Not really sure how to use the tabSectionToOpen option.
> CurrentTab support

- src/ui/ResultList/ResultList.ts
https://coveord.atlassian.net/browse/JSUI-830
> Fix handlePageChange in ResultList

- src/ui/Base/ComponentOptions.ts
- src/ui/Facet/Facet.ts
- src/ui/Facet/FacetHeader.ts
- test/ui/FacetHeaderTest.ts
- test/ui/FacetTest.ts
https://coveord.atlassian.net/browse/JSUI-837
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/26)
> Renamed allowTogglingOperator option and support alias

- gulpTasks/compile.js
- gulpTasks/dev.js
Removed `sudo` on windows only and added `node`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/30)
> gulp tasks to work on windows

- .travis.yml
- gulpTasks/compile.js
- karma.common.conf.js
- package.json
- pages/Index.html
- pages/Recommendation.html
- src/Dependencies.js
- src/ui/ResultLink/ResultLink.ts
- test/SpecRunner.html
- webpack.config.js
Change casing for dependency output file
https://coveord.atlassian.net/browse/JSUI-866
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/39)
> Minify resources in CI build

- sass/_Quickview.scss
https://coveord.atlassian.net/browse/JSUI-865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/40)
> Fix quickview iframe size

- src/Index.ts
- strings/strings.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/42)
> Export function to set lang after dom ready

- gulpTasks/compile.js
Was trying to run gulp, had an error OOTB. This fixed it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/46)
> Fix Windows gulp build task

- src/ui/Omnibox/FieldAddon.ts
- test/ui/OmniboxTest.ts
https://coveord.atlassian.net/browse/JSUI-884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/47)
> Fix duplicate @ with listOfFields option on Omnibox

- environments/link.externally.js
https://coveord.atlassian.net/browse/JSUI-889
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/49)
> + Windows support for link.externally.js

- .travis.yml
- gulpTasks/compile.js
- gulpTasks/injectTag.js
- package.json
- webpack.config.js
https://coveord.atlassian.net/browse/JSUI-868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/50)
> Inject travis tag in Coveo.version

- src/ui/Base/CoveoJQuery.ts
- src/ui/Base/RegisteredNamedMethods.ts
https://coveord.atlassian.net/browse/JSUI-887
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/48)
> Added check to support adding jQuery after the jsSearch

- src/ui/Base/Initialization.ts
- test/ui/InitializationTest.ts
https://coveord.atlassian.net/browse/JSUI-864
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/51)
> Skip initialization if the interface is getting initialized twice

- src/ui/SearchInterface/SearchInterface.ts
- src/utils/QueryUtils.ts
- test/ui/ExpressionBuilderTest.ts
https://coveord.atlassian.net/browse/JSUI-901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/56)
> Use double quote for field equality

- src/ui/Analytics/AnalyticsActionListMeta.ts
https://coveord.atlassian.net/browse/SFINT-102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/60)
> + New field on inputChange, submit, cancel and unload

- src/ui/Base/RegisteredNamedMethods.ts
- src/ui/Recommendation/Recommendation.ts
- test/ui/RecommendationTest.ts
Also fixed a bug when using `<data-user-context="{}">` to pass the user context.
https://coveord.atlassian.net/browse/JSUI-908
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/65)
> Generate default recommendation id

- .travis.yml
https://coveord.atlassian.net/browse/JSUI-919
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/70)
> Build only master and release

- src/ui/Debug/Debug.ts
https://coveord.atlassian.net/browse/JSUI-836
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/71)
> Modified regex so it supports negative weights.

- src/ui/Recommendation/Recommendation.ts
https://coveord.atlassian.net/browse/JSUI-917
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/75)
> Fix display

- gulpTasks/compile.js
- src/Index.ts
- src/ui/Facet/Facet.ts
- src/ui/ResponsiveComponents/ResponsiveFacets.ts
- src/ui/ResponsiveComponents/ResponsiveTabs.ts
- src/ui/Tab/Tab.ts
- webpack.config.js
https://coveord.atlassian.net/browse/JSUI-933
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/81)
> remove css require: JSUI-933

- webpack.config.js
https://coveord.atlassian.net/browse/JSUI-940
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/84)
> Switch to umd in webpack

- src/ui/Facet/FacetSearch.ts
- src/ui/HierarchicalFacet/HierarchicalFacet.ts
- src/ui/HierarchicalFacet/HierarchicalFacetSearch.ts
https://coveord.atlassian.net/browse/JSUI-938
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/86)
> FacetSearch focus should rely on css instead of display property

- src/ui/SearchInterface/SearchInterface.ts
https://coveord.atlassian.net/browse/JSUI-942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/87)
> removeClass instead of addClass in unsetSmallInterface

- src/ui/Facet/FacetSearchParameters.ts
- test/ui/FacetSearchParametersTest.ts
https://coveord.atlassian.net/browse/JSUI-928
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/88)
> Facet search should follow facet sort settings

- environments/link.externally.js
- src/rest/SearchEndpointInterface.ts
- src/rest/SearchEndpointWithDefaultCallOptions.ts
https://coveord.atlassian.net/browse/SFINT-171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/90)
> Expose the method the get the search alert base uri

- sass/_Omnibox.scss
- src/ui/Facet/Facet.ts
https://coveord.atlassian.net/browse/JSUI-946
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/91)
> Use promises for omnibox facet search

- src/ui/Facet/FacetSearch.ts
- src/ui/Misc/Slider.ts
https://coveord.atlassian.net/browse/JSUI-959
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/99)
> Use fat arrow to get correct "this" context on external call of nuke

- gulpTasks/strings.js
- strings/strings.js
https://coveord.atlassian.net/browse/JSUI-754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/103)
> Tweak the culture file generations to fix various bugs

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/104)
> JSUI-966 – Pimp the README

- .bithoundrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/107)
> Bithound config changes

- src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/102)
> +adds possibility to enable results filter preferences by default

- src/utils/PopupUtils.ts
https://coveord.atlassian.net/browse/JSUI-981
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/110)
> set position absolute before adding pop up to dom

- src/ui/Facet/Facet.ts
Otherwise 2 facet might try to pin themselves at the same time.
https://coveord.atlassian.net/browse/JSUI-931
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/118)
> Use a different variable to check for pin/unpin

- src/ui/SearchInterface/SearchInterface.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/121)
> Fixed a bug where JQuery is used but not imported. :tophat:

- environments/link.externally.js
- gulpTasks/dev.js
- gulpTasks/doc.js
- package.json
- src/ui/CurrentTab/CurrentTab.ts
- src/ui/Facet/Facet.ts
- src/ui/SearchInterface/SearchInterface.ts
- test/ui/CurrentTabTest.ts
https://coveord.atlassian.net/browse/JSUI-991
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/120)
> *fixes current tab exception

- package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/122)
> Bump pretty-typescript version

- test/Simulate.ts
- test/SpecRunner.html
- test/Test.ts
- test/models/ModelTest.ts
- test/ui/AuthenticationProviderTest.ts
- test/ui/CurrentTabTest.ts
- test/ui/FollowItemTest.ts
- test/ui/SearchAlertsTest.ts
- test/utils/DomTest.ts
Remove some unused stuff
https://coveord.atlassian.net/browse/JSUI-962
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/125)
> Fix linter errors

- src/ui/Base/ComponentOptions.ts
- src/ui/Pager/Pager.ts
https://coveord.atlassian.net/browse/JSUI-1001
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/126)
> attribute options before Coveo.options

- src/ui/SearchAlerts/FollowItem.ts
- src/utils/Dom.ts
- test/utils/DomTest.ts
https://coveord.atlassian.net/browse/JSUI-996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/132)
> Fix spinning follow item icon

- pages/Standalone.html
- src/ui/Omnibox/Omnibox.ts
- src/ui/Querybox/Querybox.ts
- test/ui/OmniboxTest.ts
- test/ui/QueryboxTest.ts
https://coveord.atlassian.net/browse/JSUI-995
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/131)
> Added option to choose if clear on Searchbox should trigger a query

- src/rest/RevealQuerySuggest.ts
- src/ui/Omnibox/RevealQuerySuggestAddon.ts
https://coveord.atlassian.net/browse/JSUI-998
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/130)
> Use the pipeline on the search interface for reveal query suggest

- gulpTasks/definition.js
https://coveord.atlassian.net/browse/JSUI-1022
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/136)
> Fix errors with CoveoJsSearch.d.ts

- gulpTasks/definition.js
- src/ui/Settings/Settings.ts
- test/Simulate.ts
https://coveord.atlassian.net/browse/JSUI-1022
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/137)
> Fix .d.ts while keeping Simulate and MockEnvironment

- src/ui/Base/ComponentOptions.ts
- src/ui/Pager/Pager.ts
> Use isNullOrUndefined instead of _.isEmpty in initOptions

- src/ui/ResultsPreferences/ResultsPreferences.ts
https://coveord.atlassian.net/browse/JSUI-1031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/140)
> target instead of srcElement

- plop/plopTemplates/plop.component.test.template.hbs
- plop/plopfile.js
https://coveord.atlassian.net/browse/JSUI-1025
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/142)
> Update plop / plop files pour UT

- src/ui/Base/Component.ts
- src/ui/Base/Initialization.ts
- src/ui/Base/RegisteredNamedMethods.ts
- test/Test.ts
- test/ui/RegisteredNamedMethodsTest.ts
- tsconfig.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/148)
> More UT for registered named methods

- src/ui/Pager/ResultsPerPage.ts
- test/ui/ResultsPerPageTest.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/143)
> Added initialChoice to ResultsPerPage component

- package.json
https://coveord.atlassian.net/browse/JSUI-1058
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/152)
> Update the modal box dependency to newer version

- src/ui/Facet/Facet.ts
- src/ui/Facet/FacetSearch.ts
- src/ui/Facet/FacetSort.ts
- src/ui/Facet/FacetValuesList.ts
- src/ui/Facet/FacetValuesOrder.ts
- test/Test.ts
- test/ui/FacetValuesOrderTest.ts
- tsconfig.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/153)
> Handle Facet sort better with alphaascending/descending when there is a value caption

- pages/Slack.html
- templates/Slack/MobileSlack.html
- templates/Slack/Slack.html
- templates/conditions.json
https://coveord.atlassian.net/browse/CT-1612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/117)
> [Slack] Add our Slack source to InternalSearch

- src/misc/SentryLogger.ts
- src/rest/SearchEndpoint.ts
- src/rest/SearchEndpointInterface.ts
- src/rest/SearchEndpointWithDefaultCallOptions.ts
- src/rest/SentryLog.ts
- src/ui/SearchInterface/SearchInterface.ts
- test/Test.ts
- test/misc/SentryLoggerTest.ts
- tsconfig.json
https://coveord.atlassian.net/browse/JSUI-859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/158)
> Add support to log errors in sentry

- src/ui/ResponsiveComponents/ResponsiveFacets.ts
https://coveord.atlassian.net/browse/JSUI-1104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/163)
> Exit init of responsive mode when there is not tab section

- src/events/InitializationEvents.ts
- src/events/QueryEvents.ts
https://coveord.atlassian.net/browse/JSUI-1115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/168)
> Document the InitializationEvents

- src/ui/ResponsiveComponents/ResponsiveComponentsManager.ts
https://coveord.atlassian.net/browse/JSUI-1117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/169)
> disable reponsive mode when old design

- pages/All.html
- pages/Chatter.html
- pages/Dropbox.html
- pages/Email.html
- pages/GoogleDrive.html
- pages/Index.html
- pages/Jira.html
- pages/Lithium.html
- pages/People.html
- pages/Recommendation.html
- pages/Salesforce.html
- pages/SalesforceCase.html
- pages/Slack.html
- pages/Standalone.html
- pages/YouTube.html
- src/rest/SearchEndpoint.ts
- src/ui/Querybox/Querybox.ts
Add new helper to configure the v2 endpoint
https://coveord.atlassian.net/browse/JSUI-1055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/170)
> Configure a new demo endpoint in cloud v2

- src/ui/QuerySummary/QuerySummary.ts
https://coveord.atlassian.net/browse/JSUI-1127
> Use last known good state instead of going back in history on no results

- src/ui/Base/CoveoJQuery.ts
- src/utils/Dom.ts
https://coveord.atlassian.net/browse/JSUI-1135
> If Coveo.$ is already defined, shouldn't be overwritten with undefined

- src/ui/Base/ComponentOptions.ts
- test/utils/DomTest.ts
https://coveord.atlassian.net/browse/JSUI-1139
> JSDoc for component options

- src/events/AnalyticsEvents.ts
- src/ui/Analytics/LiveAnalyticsClient.ts
https://coveord.atlassian.net/browse/JSUI-1145
> Add JSDoc for the changeAnalyticsCustomData event

- src/events/AnalyticsEvents.ts
- src/ui/Analytics/LiveAnalyticsClient.ts
- test/ui/LiveAnalyticsClientTest.ts
Add UT for resultData
https://coveord.atlassian.net/browse/JSUI-1144
> Merge data for changeAnalyticsCustomData when it is supplied,

- src/events/AnalyticsEvents.ts
- src/ui/FacetRange/FacetRange.ts
- src/ui/FieldTable/Badge.ts
- src/ui/HierarchicalFacet/HierarchicalFacet.ts
- src/ui/ImageResultList/ImageResultList.ts
- src/ui/OmniboxResultList/OmniboxResultList.ts
- src/ui/Recommendation/Recommendation.ts
- src/ui/SearchInterface/SearchInterface.ts
https://coveord.atlassian.net/browse/JSUI-1147
> Add interface implementation for typedoc

- package.json
https://coveord.atlassian.net/browse/JSUI-1159
> allow minor version update for coveomagicbox

- .gitignore
- docs/playground/src/Index.ts
- docs/playground/src/Playground.ts
- docs/playground/src/PlaygroundConfiguration.ts
- docs/theme/assets/css/main.css
- docs/theme/layouts/default.hbs
- gulpTasks/dev.js
- gulpTasks/doc.js
- src/rest/SearchEndpoint.ts
- src/ui/AdvancedSearch/AdvancedSearch.ts
- src/ui/Matrix/Matrix.ts
- src/ui/YouTube/YouTubeThumbnail.ts
- tsconfig.json
- webpack.playground.config.js
> Basic support for playground in doc

- src/controllers/FacetSliderQueryController.ts
- test/ui/FacetSliderTest.ts
> Defensive check for FacetSlider on non-numerical field

- src/ui/HierarchicalFacet/HierarchicalFacet.ts
- test/Fake.ts
- test/ui/HierarchicalFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-1169
> Check for orphans values should consider the levelStart option

- sass/notifications/_SubscriptionsPanel.scss
- src/ui/SearchAlerts/SearchAlerts.ts
- src/utils/DomUtils.ts
> Add dismiss icon for search alert panel

- src/ui/ResultList/ResultList.ts
https://coveord.atlassian.net/browse/JSUI-1171
> After a query success, scroll back to top (with infinite scroll)

- src/controllers/FacetQueryController.ts
- test/ui/FacetTest.ts
> Rework the number of values requested when there is a custom sort

- src/controllers/QueryController.ts
- src/ui/Base/Initialization.ts
https://coveord.atlassian.net/browse/JSUI-1193
> Set the page view history correctly when the first query is from an external link.

- src/ui/Settings/Settings.ts
- test/ui/SettingsTest.ts
https://coveord.atlassian.net/browse/JSUI-1178
> Call close when opening a menu, instead of detach.

- src/ui/Facet/FacetSearch.ts
- src/ui/Facet/FacetValues.ts
- test/ui/SettingsTest.ts
https://coveord.atlassian.net/browse/JSUI-1177
> Do not import occurrences from other list for selected values

- src/ui/SearchAlerts/SearchAlerts.ts
- strings/strings.json
- test/ui/FacetSliderTest.ts
- test/ui/RecommendationTest.ts
Fix linter complaints.
https://coveord.atlassian.net/browse/JSUI-1185
> Add monthly value for the search alerts service

- sass/_FacetValues.scss
https://coveord.atlassian.net/browse/JSUI-1191
> Add magical css property to fix everything

- filetypes/common.json
- filetypes/objectType.json
- pages/DynamicsCrm.html
- templates/DynamicsCrm/DynamicsCrm.html
- templates/DynamicsCrm/MobileDynamicsCrm.html
- templates/DynamicsCrmCase/DynamicsCrmCase.html
- templates/DynamicsCrmCase/MobileDynamicsCrmCase.html
- templates/conditions.json
> Add Dynamics CRM result list templates

- src/ui/Base/BaseComponent.ts
- src/ui/Base/Component.ts
- src/ui/Debug/Debug.ts
- test/ui/DebugTest.ts
> Various debug panel problems

- src/ui/AdvancedSearch/Form/Dropdown.ts
https://coveord.atlassian.net/browse/JSUI-1206
> Close the dropdown on mouse leave.

- sass/_AdvancedSearch.scss
- sass/_ShareQuery.scss
https://coveord.atlassian.net/browse/JSUI-1208
> align left for advanced search (and share query)

- src/events/QuerySummaryEvents.ts
- src/ui/AdvancedSearch/AdvancedSearch.ts
- src/ui/AdvancedSearch/AdvancedSearchInput.ts
- src/ui/AdvancedSearch/DateInput/BetweenDateInput.ts
- src/ui/AdvancedSearch/DateInput/DateInput.ts
- src/ui/AdvancedSearch/DateInput/InTheLastDateInput.ts
- src/ui/AdvancedSearch/DocumentInput/AdvancedFieldInput.ts
- src/ui/AdvancedSearch/DocumentInput/DocumentInput.ts
- src/ui/AdvancedSearch/DocumentInput/SimpleFieldInput.ts
- src/ui/AdvancedSearch/DocumentInput/SizeInput.ts
- src/ui/AdvancedSearch/Form/DatePicker.ts
- src/ui/AdvancedSearch/Form/Dropdown.ts
- src/ui/AdvancedSearch/Form/NumericSpinner.ts
- src/ui/AdvancedSearch/Form/RadioButton.ts
- src/ui/AdvancedSearch/Form/TextInput.ts
- src/ui/AdvancedSearch/KeywordsInput/KeywordsInput.ts
- src/ui/QuerySummary/QuerySummary.ts
Add an event when the cancel action is triggered by the query summary
https://coveord.atlassian.net/browse/JSUI-1127
> Add a mechanism to reset the AdvancedSearch

- src/ui/Analytics/RecommendationAnalyticsClient.ts
- src/ui/Recommendation/Recommendation.ts
- test/ui/RecommendationAnalyticsClientTest.ts
https://coveord.atlassian.net/browse/JSUI-1230
> Modify the query pipeline on click event for recommendation component

- src/BaseModules.ts
- strings/strings.js
Instead of using onDOM ready function.
Allows easier customization for localization.
https://coveord.atlassian.net/browse/JSUI-1239
> Load default language on script load

- src/ui/Base/Initialization.ts
- test/ui/InitializationTest.ts
> Accept jQuery elements for external components

- src/ui/Quickview/QuickviewDocument.ts
https://coveord.atlassian.net/browse/JSUI-1288
> Bad logic for quick view scroll

- src/ui/Quickview/QuickviewDocument.ts
- src/ui/TemplateLoader/TemplateLoader.ts
> Documented the TemplateLoader class.

- .travis.yml
- deploy.beta.js
- deploy.doc.sh
- package.json
https://coveord.atlassian.net/browse/JSUI-1183
> Support for beta builds

- src/Index.ts
- src/utils/KeyboardUtils.ts
- test/Test.ts
- test/tsconfig.json
- test/utils/KeyboardUtilsTest.ts
Add coverage
https://coveord.atlassian.net/browse/JSUI-1213
> Defensive code for KeyboardUtils.keypressAction

- src/models/Model.ts
- src/ui/TemplateLoader/TemplateLoader.ts
Since this method was referred to in the tutorial, I thought it would be a good idea to expose it in the generated reference documentation.
> Briefly commented the Model.getAttributes() method.

- README.md
- plop/plopTemplates/plop.bundle.template.hbs
https://coveord.atlassian.net/browse/JSUI-1308
> fix relative import in plop build template

- .travis.yml
🤓 
https://coveord.atlassian.net/browse/JSUI-1316
> Ont travis, update node version from 4.2.2 to 6.9.2

- sass/_Omnibox.scss
- sass/_Searchbox.scss
https://coveord.atlassian.net/browse/JSUI-1299
> Remove ghost text with css

- gulpTasks/test.js
- lib/latinize.d.ts
- package.json
- src/ui/ResultLink/ResultLink.ts
- src/utils/DomUtils.ts
- src/utils/StringUtils.ts
- test/Test.ts
- test/tsconfig.json
- test/ui/ResultLinkTest.ts
- test/utils/StringUtilsTest.ts
- tsconfig.json
https://coveord.atlassian.net/browse/JSUI-1277
> Use latinize lib to remove accent and diacritic (e.g. : ç)

- src/rest/RevealQuerySuggest.ts
- src/ui/Omnibox/RevealQuerySuggestAddon.ts
https://coveord.atlassian.net/browse/JSUI-1297
> add the parameter enableWordCompletion

- src/ui/Base/Component.ts
- src/ui/Omnibox/RevealQuerySuggestAddon.ts
- test/Simulate.ts
- test/ui/ResultListTest.ts
https://coveord.atlassian.net/browse/JSUI-1287
> add binding with jQuery if possible when rendering results

- .travis.yml
- README.md
- docs/theme/assets/css/overrides.css
- docs/theme/assets/js/generateMetaData.js
- docs/theme/assets/js/header.js
- docs/theme/assets/js/searchUIrefDoc.js
- docs/theme/layouts/default.hbs
- docs/theme/partials/footer.hbs
- docs/theme/partials/header.hbs
- docs/theme/partials/index.hbs
- docs/tsconfig.json
- gulpTasks/doc.js
- gulpTasks/docsitemap.js
- package.json
Added usage analytics
Added metadata
Added Site Map
> Modified documentation site theme look

- docs/tsconfig.json
- src/ui/Analytics/Analytics.ts
- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/Analytics/LiveAnalyticsClient.ts
- src/ui/ResultList/ResultList.ts
- src/ui/SearchAlerts/FollowItem.ts
- src/ui/SearchAlerts/SearchAlerts.ts
- src/utils/QueryUtils.ts
- test/ui/FollowItemTest.ts
- test/ui/ResultListTest.ts
- test/ui/SearchAlertsTest.ts
https://coveord.atlassian.net/browse/JSUI-1304
> Add UA events for search alerts

- src/ui/Omnibox/Omnibox.ts
- src/ui/ResultLink/ResultLink.ts
https://coveord.atlassian.net/browse/JSUI-1300
> Blur the input on submit and escape key.

- sass/_FacetHeader.scss
- src/ui/Facet/FacetHeader.ts
Add a title to show on hover.
https://coveord.atlassian.net/browse/JSUI-1269
> Overflow hidden for text in facet header.

- src/ui/Misc/Slider.ts
https://coveord.atlassian.net/browse/JSUI-1340
> handle touches correctly for slider button

- src/models/QueryStateModel.ts
https://coveord.atlassian.net/browse/JSUI-1329
> do not exclude range facet from active facet check.

- src/ui/SearchAlerts/SearchAlerts.ts
- test/MockEnvironment.ts
- test/ui/SearchAlertsTest.ts
https://coveord.atlassian.net/browse/JSUI-1324
> do not bind the search alerts if the user is anonymous

- src/ui/FacetSlider/FacetSlider.ts
- src/ui/Misc/Slider.ts
- test/ui/FacetSliderTest.ts
- test/ui/SliderTest.ts
https://coveord.atlassian.net/browse/JSUI-1247
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/269)
> Fix facet slider being drawn inside the insight panel.

- src/ui/Facet/FacetSearch.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/270)
> Scroll search results when navigating with keyboard

- src/ui/SearchInterface/SearchInterface.ts
- test/ui/StandaloneSearchInterfaceTest.ts
https://coveord.atlassian.net/browse/JSUI-1210
> Modify searchBoxSubmit to searchFromLink

- src/ui/Facet/OmniboxValuesList.ts
- src/ui/Omnibox/OldOmniboxAddon.ts
https://coveord.atlassian.net/browse/JSUI-1367
> Trigger event from root element (used for external components)

- pages/All.html
- pages/Chatter.html
- pages/Dropbox.html
- pages/DynamicsCrm.html
- pages/Email.html
- pages/GoogleDrive.html
- pages/Jira.html
- pages/Lithium.html
- pages/People.html
- pages/Salesforce.html
- pages/SalesforceCase.html
- pages/SharePoint.html
- pages/Slack.html
- pages/YouTube.html
- sass/_Quickview.scss
- src/ui/Quickview/QuickviewDocument.ts
Modify IOS additional css that we add.
https://coveord.atlassian.net/browse/JSUI-1369
> Update viewport for all example pages

- sass/_Breadcrumb.scss
- src/ui/Facet/BreadcrumbValuesList.ts
change padding on max-width 800px;
https://coveord.atlassian.net/browse/JSUI-1373
> remove special case for mobile breadcrumb.

- lib/coveoanalytics.d.ts
- package.json
https://coveord.atlassian.net/browse/JSUI-1378
> update coveo.analytics lib

- src/ui/Templates/CoreHelpers.ts
- src/utils/StreamHighlightUtils.ts
- test/utils/StreamHighlightUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-1358
> modify termsToHighlight check for highlightStreamHTML

- sass/_Result.scss
https://coveord.atlassian.net/browse/JSUI-1363
> Only show blue card hover when Result has class coveo-clickable

- src/rest/SearchEndpoint.ts
- src/ui/ExportToExcel/ExportToExcel.ts
- test/ui/ExportToExcelTest.ts
https://coveord.atlassian.net/browse/JSUI-1355
> Add support for fieldsToInclude in ExportToExcel

- src/ui/Templates/TemplateCache.ts
https://coveord.atlassian.net/browse/JSUI-1251
> Add a mechanism to scan template when we fail to find them on the first try

- src/ui/Querybox/Querybox.ts
https://coveord.atlassian.net/browse/JSUI-1382
> update doc for enableQuerySyntax option

- src/ui/Backdrop/Backdrop.ts
- src/ui/Base/ComponentOptions.ts
- src/ui/CardActionBar/CardActionBar.ts
- src/ui/CardOverlay/CardOverlay.ts
- src/ui/ResultLayout/ResultLayout.ts
- src/ui/ResultList/ResultList.ts
- src/ui/Tab/Tab.ts
- test/ui/FoldingTest.ts
Revised public documentation related to JSUI-862
> Revised result layout public documentation

- src/ui/FacetSlider/FacetSlider.ts
https://coveord.atlassian.net/browse/JSUI-1351
> Add the needed css class to hide on disable

- src/rest/QueryResult.ts
- src/rest/SearchEndpoint.ts
- src/ui/Icon/Icon.ts
- src/ui/ResultAttachments/ResultAttachments.ts
- src/ui/ResultFolding/ResultFolding.ts
- src/ui/ResultList/ResultList.ts
- src/ui/Templates/CoreHelpers.ts
- src/utils/EmailUtils.ts
- src/utils/HtmlUtils.ts
- src/utils/QueryUtils.ts
- src/utils/TimeSpanUtils.ts
- test/Fake.ts
- test/Test.ts
- test/tsconfig.json
- test/ui/CoreHelpersTest.ts
- test/ui/FoldingTest.ts
There was a lot of missing test coverage, and public documentation about some available helpers.
https://coveord.atlassian.net/browse/JSUI-1321
> Improve template helpers coverage + fix some issue in helpers

- sass/_FullSearchGrid.scss
- sass/_Icons.scss
- sass/_ResultList.scss
Before :
After : 
https://coveord.atlassian.net/browse/JSUI-1365
> Improve mobile display of ResultLayout selector and Card results

- sass/_Breadcrumb.scss
- sass/_FullSearchGrid.scss
- sass/_ResponsiveComponents.scss
- sass/_ResultList.scss
> JSUI-1365 - Mobile display of results header

- src/ui/ResultLayout/ResultLayout.ts
- test/ui/ResultLayoutTest.ts
https://coveord.atlassian.net/browse/JSUI-1366
> JSUI-1366 Add keyboard activation of ResultLayout selectors

- sass/_FieldTable.scss
- sass/_ResultFolding.scss
- sass/_Variables.scss
- src/rest/SearchEndpoint.ts
- templates/GoogleDrive/CardGoogleDrive.html
update template google drive
https://coveord.atlassian.net/browse/JSUI-1401
> change colors for clickable link

- sass/_ResponsiveFacets.scss
https://coveord.atlassian.net/browse/JSUI-1412
> white space : initial when going into small mode for facet header

- src/ui/Facet/FacetHeader.ts
https://coveord.atlassian.net/browse/JSUI-1398
> Render eraser before toggling icon so we get a nicer effect in the header.

- sass/_CardOverlay.scss
- src/ui/CardActionBar/CardActionBar.ts
- src/ui/CardOverlay/CardOverlay.ts
> Improve tab navigation for CardOverlay and CardActionBar

- src/utils/HashUtils.ts
- test/utils/HashUtilsTest.ts
UT
https://coveord.atlassian.net/browse/JSUI-1419
> Defensive code against undefined values in HashUtils

- src/rest/RevealQuerySuggest.ts
- src/ui/Omnibox/RevealQuerySuggestAddon.ts
- src/ui/PipelineContext/PipelineContext.ts
- templates/YouTube/CardYouTubeVideo.html
- test/MockEnvironment.ts
- test/Test.ts
- test/ui/ExportToExcelTest.ts
- test/ui/PipelineContextTest.ts
- test/ui/RevealQuerySuggestAddonTest.ts
Document PipelineContext
Add UT for PipelineContext and RevealQuerySuggestAddon
> Add context to reveal query suggest call

- src/ui/Searchbox/Searchbox.ts
> DOC-458 Searchbox documentation revision

- src/ui/SearchButton/SearchButton.ts
> DOC-458 SearchButton documentation revision

- src/ui/Settings/Settings.ts
> DOC-458 Settings documentation revision

- src/ui/ShareQuery/ShareQuery.ts
> DOC-458 ShareQuery documentation revision

- src/ui/Sort/Sort.ts
> DOC-458 Sort documentation revision

- src/ui/Tab/Tab.ts
> DOC-458 Tab documentation revision

- src/ui/ResultRating/ResultRating.ts
> DOC-458 ResultRating documentation revision

- src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
- src/ui/ResultsPerPage/ResultsPerPage.ts
> ResultsFiltersPreferences documentation revision

- src/ui/ResultLink/ResultLink.ts
> DOC-458 ResultLink documentation revision.

- src/ui/SearchAlerts/FollowItem.ts
- src/ui/SearchAlerts/SearchAlerts.ts
- src/ui/SearchAlerts/SearchAlertsMessage.ts
Also includes FollowItem and SearchAlertsMessage documentation revision
> DOC-458 SearchAlerts documentation revision

- src/SearchboxIndex.ts
- src/ui/SearchInterface/SearchInterface.ts
- test/ui/StandaloneSearchInterfaceTest.ts
https://coveord.atlassian.net/browse/JSUI-1427
> Merge fragment and query string params when doing a standalone search page redirection

- src/ui/Pager/Pager.ts
> DOC-458 Pager documentation revision

- src/ui/PreferencesPanel/PreferencesPanel.ts
> DOC-458 PreferencesPanel documentation revision

- src/ui/PrintableUri/PrintableUri.ts
> DOC-458 PrintableUri documentation revision

- src/ui/QueryDuration/QueryDuration.ts
- src/ui/Querybox/Querybox.ts
> Querybox doc revision

- src/ui/QuerySummary/QuerySummary.ts
> DOC-458 QuerySummary documentation revision

- src/ui/ResultList/ResultList.ts
> DOC-458 ResultList documentation revision

- src/ui/ResultFolding/ResultFolding.ts
> DOC-458 ResultFolding documentation revision

- src/ui/Matrix/Matrix.ts
> DOC-458 Matrix documentation revision

- package.json
- webpackConfigFiles/webpack.common.config.js
https://coveord.atlassian.net/browse/JSUI-1428
> use expose loader to have Globalize on the window object

- src/ui/SearchInterface/SearchInterface.ts
- src/ui/Templates/Template.ts
This ensure we do not get null ref in some corner cases
https://coveord.atlassian.net/browse/JSUI-1429
> Add some defaults value for the Template rendering methods

- docs/theme/assets/css/overrides.css
> DOC-477 JsSearchRef - Enlarge font for option names

- src/ui/Breadcrumb/Breadcrumb.ts
> DOC-458 Breadcrumb documentation revision

- src/ui/DidYouMean/DidYouMean.ts
> DOC-458 DidYouMean documentation revision

- src/ui/ErrorReport/ErrorReport.ts
> DOC-458 ErrorReport documentation revision

- src/ui/Excerpt/Excerpt.ts
> DOC-458 Excerpt documentation revision

- src/ui/Facet/Facet.ts
> DOC-458 Facet - Fixed several minor display issues in rendered doc

- src/ui/FieldSuggestions/FieldSuggestions.ts
> DOC-458 FieldSuggestions documentation revision

- src/ui/Folding/Folding.ts
> DOC-458 Folding documentation revision

- src/ui/ImageResultList/ImageResultList.ts
> DOC-458 ImageResultList documentation revision

- src/ui/Logo/Logo.ts
> DOC-458 Logo documentation revision

- src/ui/Omnibox/Omnibox.ts
> DOC-458 Omnibox documentation revision

- src/ui/ResultAttachments/ResultAttachments.ts
> DOC-458 ResultAttachments documentation revision

- src/ui/Omnibox/Omnibox.ts
> DOC-458 Omnibox - Removed outdated information from public doc.

- src/ui/Icon/Icon.ts
> DOC-458 Icon - Changed default value of `small` option in public doc

- src/ui/Recommendation/Recommendation.ts
> DOC-458 Recommendation documentation revision

- src/ui/Facet/Facet.ts
> DOC-578 Change the example of the DependsOn property

- src/ui/Base/BaseComponent.ts
https://coveord.atlassian.net/browse/JSUI-1447
> fix compute css class

- sass/_CardActionBar.scss
- sass/_Result.scss
> Fix issues with Safari and ActionBar in card layout

- src/ui/FacetSlider/FacetSlider.ts
- src/ui/Misc/Slider.ts
- test/ui/SliderTest.ts
> Add a max number of steps for slider

- src/ui/Facet/FacetSearch.ts
https://coveord.atlassian.net/browse/JSUI-1439
> Add input to list of ignored elements for facet search blur

- sass/_FacetSearch.scss
- sass/_FacetValues.scss
- src/ui/Facet/FacetSearch.ts
- src/ui/Facet/FacetSearchParameters.ts
- src/ui/Facet/ValueElement.ts
https://coveord.atlassian.net/browse/JSUI-1320
> Improve issues with facet search regarding excluding values

- sass/_Logo.scss
- sass/_Pager.scss
- sass/_ResultList.scss
- sass/_ResultsPerPage.scss
https://coveord.atlassian.net/browse/JSUI-1403
> adjustment to bottom of result list

- src/ui/Omnibox/Omnibox.ts
- test/ui/OmniboxTest.ts
https://coveord.atlassian.net/browse/JSUI-1416
> Change default value to true for query suggest

- src/ui/Analytics/LiveAnalyticsClient.ts
- src/ui/SearchAlerts/FollowItem.ts
- src/utils/QueryUtils.ts
- test/ui/FollowItemTest.ts
- test/ui/LiveAnalyticsClientTest.ts
https://coveord.atlassian.net/browse/JSUI-1466
> Change to use permanentid instead of uniqueid

- src/ui/FieldTable/FieldValue.ts
- test/ui/FieldValueTest.ts
https://coveord.atlassian.net/browse/JSUI-1322
> Filter out helper options that match the current helper

- src/ui/Facet/FacetSort.ts
- src/ui/Facet/FacetValuesOrder.ts
- strings/strings.json
- test/ui/FacetTest.ts
https://coveord.atlassian.net/browse/JSUI-1488
> Fix issues with no sort set on available sorts

- pages/SalesforceCase.html
https://coveord.atlassian.net/browse/JSUI-1484
> Change title for @objecttype facet in SFCase page

- src/ui/FacetSlider/FacetSlider.ts
https://coveord.atlassian.net/browse/JSUI-1493
> Update slider as if it was moving when updating appearance.

- src/utils/StreamHighlightUtils.ts
- test/utils/StreamHighlightUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-1390
> Escape regex sensitive character when building the highlighting regex

- src/ui/Base/ComponentOptions.ts
- src/ui/FacetSlider/FacetSlider.ts
- test/ui/FacetTest.ts
https://coveord.atlassian.net/browse/JSUI-1492
> Add informative message when we detect an option configured out of the min or max bounds possible on an option

- templates/All/Card.html
- templates/Chatter/CardChatter.html
- templates/Dropbox/CardDropbox.html
- templates/DynamicsCrm/CardDynamicsCrm.html
- templates/DynamicsCrmCase/CardDynamicsCrmCase.html
- templates/Email/CardEmailThread.html
- templates/GoogleDrive/CardGoogleDrive.html
- templates/Lithium/CardLithiumThread.html
- templates/People/CardPeople.html
- templates/Salesforce/CardSalesforce.html
- templates/SalesforceCase/CardSalesforceCase.html
- templates/SharePoint/CardSharePoint.html
- templates/SharePoint/CardSharePointList.html
- templates/Slack/CardSlack.html
- templates/YouTube/CardYouTubePlaylistItem.html
- templates/YouTube/CardYouTubeVideo.html
https://coveord.atlassian.net/browse/JSUI-1402
> Modify card to align middle icon with title

- src/ui/Facet/Facet.ts
https://coveord.atlassian.net/browse/JSUI-1346
> Ensure the unpin and pinned flag variables are always reset, no matter the current state of the facet when we try to unpin

- src/ui/Facet/FacetSearch.ts
https://coveord.atlassian.net/browse/JSUI-1508
> use translated string for SelectAll

- sass/_CardOverlay.scss
- src/ui/CardOverlay/CardOverlay.ts
https://coveord.atlassian.net/browse/JSUI-1473
> Add minimum height for card overlay when it's opened

- src/ui/Misc/Slider.ts
- test/ui/SliderTest.ts
Work on UT for Slider
https://coveord.atlassian.net/browse/JSUI-1514
> Handle corner case where range value can be a single point with no x axis width

- src/ui/Thumbnail/Thumbnail.ts
- test/ui/ThumbnailTest.ts
> create icon if result has no thumbnail

- src/ui/Folding/Folding.ts
- src/ui/Folding/FoldingForThread.ts
- src/ui/ResultAttachments/ResultAttachments.ts
- src/ui/ResultFolding/ResultFolding.ts
- Made some minor corrections / modifications in result folding components documentation.
- Added links to new topic on developers.coveo.com about result folding
> DOC-666 Document the Folding feature in detail

- sass/_Omnibox.scss
https://coveord.atlassian.net/browse/JSUI-1528
> remove hover backgroud color css rule

- package.json
> Fix tsc not finding moment typings

- src/ui/Searchbox/Searchbox.ts
> DOC-674 Typo in jsui searchbox example

- src/ui/Facet/Facet.ts
- Added some links to IGroupByRequest.sortCriteria rather than duplicating the existing information
> DOC-673 Add description for facet sort options

- src/rest/QueryResults.ts
- src/rest/QuerySuggest.ts
- src/rest/SearchEndpoint.ts
- src/rest/SearchEndpointInterface.ts
- src/rest/SearchEndpointWithDefaultCallOptions.ts
- src/ui/Analytics/PendingSearchEvent.ts
- src/ui/Base/ComponentOptions.ts
- src/ui/Omnibox/Omnibox.ts
- src/ui/Omnibox/QuerySuggestAddon.ts
- src/ui/PipelineContext/PipelineContext.ts
- test/MockEnvironment.ts
- test/Test.ts
- test/rest/SearchEndpointTest.ts
- test/ui/ComponentOptionsTest.ts
- test/ui/OmniboxTest.ts
- test/ui/QuerySuggestAddonTest.ts
https://coveord.atlassian.net/browse/JSUI-1450
> Remove references for Reveal

- docs/theme/partials/header.hbs
- Used new option name in doc site header template
> DOC-815 Remove references to Reveal in JS UI

- docs/theme/layouts/default.hbs
Changed component title format to improve findability
> DOC-857 Improve findability of JS UI component reference documentation

- src/ui/Facet/FacetSearchParameters.ts
completeFacetWithStandardValues should always be false if allowedValues is set
> JSUI-1572 - Facet allowed values ignore when show more is clicked

- strings/strings.json
https://coveord.atlassian.net/browse/JSUI-1498
> Fixed typo in ''QueryExceptionInvalidTerm''

- src/controllers/FacetSliderQueryController.ts
- test/ui/FacetSliderTest.ts
Changed controller so ranges values are added if the custom ranges are set.
https://coveord.atlassian.net/browse/SC-1863
> Added support for custom ranges when automatic range isn't available.

- src/controllers/FacetSliderQueryController.ts
- src/ui/FacetSlider/FacetSlider.ts
- test/Test.ts
- test/controllers/FacetSliderQueryControllerTest.ts
- test/ui/FacetSliderTest.ts
> Changes to Facet Slider to handle simpler config with non-automatic range

- src/ui/Querybox/Querybox.ts
- src/ui/ResultsPreferences/ResultsPreferences.ts
- Updated ResultsPreferences and Querybox doc to add necessary information
> Doc-905 - Option in advanced search for Enable query syntax (On/Off/Automatic)

- README.md
> use full readme image path for it to appear properly on npmjs.com

- webpack.config.js
https://coveord.atlassian.net/browse/JSUI-1599
> Add provide plugin to auto shim Promise when needed. (IE11)

- src/ui/Facet/Facet.ts
- test/ui/FacetTest.ts
Remove flaky voodoo magic for preserve position in facet
https://coveord.atlassian.net/browse/JSUI-1612
> Better logic for padding container

- src/controllers/FacetSliderQueryController.ts
- src/utils/PublicPathUtils.ts
- test/utils/PublicPathUtilsTest.ts
> Issue with "simpleSliderConfig" not formatting date field properly

- sass/_Debug.scss
- sass/vapor/_Checkbox.scss
- src/ui/Debug/DebugHeader.ts
- test/ui/DebugHeaderTest.ts
Allows to bypass the "automatically select fields to include" set on the result list
https://coveord.atlassian.net/browse/JSUI-1622
> Add checkbox to request all fields in debug panel

- sass/_InitializationPlaceholder.scss
- src/ui/Base/Initialization.ts
- src/ui/Base/InitializationPlaceholder.ts
- src/ui/Base/RegisteredNamedMethods.ts
- src/ui/ResultList/ResultList.ts
- test/ui/InitializationTest.ts
- test/ui/ResultListTest.ts
Better placeholder.
Fix issue with eager loading complaining that recommendation is unavailable
Fix issue with result list trying to get fields to include on a non-initialized component (result list inside a recommendation component).
https://coveord.atlassian.net/browse/JSUI-1454
> Various improvements for Recommendation intialization

- src/ui/Facet/FacetValuesOrder.ts
- test/ui/FacetValuesOrderTest.ts
https://coveord.atlassian.net/browse/JSUI-1614
> Add locale compare for FacetValuesOrder

- src/ui/Analytics/Analytics.ts
https://coveord.atlassian.net/browse/JSUI-1646
> Simplify check for analytics recommendation

- src/ui/AdvancedSearch/AdvancedSearch.ts
- src/ui/ResultList/ResultList.ts
- test/ui/AdvancedSearch/AdvancedSearchTest.ts
Issue with result list rendering order.
https://coveord.atlassian.net/browse/JSUI-1650
> Changes with advanced search on breadcrumb clear

- src/ui/ResultLayout/ResultLayout.ts
- test/ui/ResultLayoutTest.ts
https://coveord.atlassian.net/browse/JSUI-1634
> Issue with result layouts stuck in "hidden" mode.

- sass/_InitializationPlaceholder.scss
https://coveord.atlassian.net/browse/JSUI-1655
> Improve placeholder loading for different type of facets

- sass/notifications/_SubscriptionsMessages.scss
- src/ui/SearchAlerts/SearchAlertsMessage.ts
https://coveord.atlassian.net/browse/JSUI-1629
> z index for subscriptions messages

- src/rest/SearchEndpoint.ts
> add missing return for renewAccessToken callback

- sass/_Quickview.scss
https://coveord.atlassian.net/browse/JSUI-1630
> Css issue for quickview in cards

- strings/strings.json
https://coveord.atlassian.net/browse/JSUI-1675
> Capitalize string

- src/controllers/HierarchicalFacetQueryController.ts
https://coveord.atlassian.net/browse/JSUI-1667
> Add check for exclude value in facet search

- src/ui/Debug/Debug.ts
- src/ui/Debug/DebugHeader.ts
https://coveord.atlassian.net/browse/JSUI-1670
> Debug header should stays persistent between debug panel instance

- src/ui/Debug/Debug.ts
- src/ui/Debug/DebugHeader.ts
https://coveord.atlassian.net/browse/JSUI-1688
> Fix couple issue with facet debug search

- src/misc/PromisesShim.ts
- src/ui/PrintableUri/PrintableUri.ts
https://coveord.atlassian.net/browse/JSUI-1698
> Change the way the shim is done to patch the global object first

- templates/YouTube/CardYouTubeVideo.html
https://coveord.atlassian.net/browse/JSUI-1689
> Display inline-block for default YouTube card views and duration

- src/ui/ResultList/ResultList.ts
- test/ui/ResultListTableRendererTest.ts
- test/ui/ResultListTest.ts
https://coveord.atlassian.net/browse/JSUI-1707
> Change the handling of the "displayedResult" state in ResultList

- sass/_PrintableUri.scss
- src/ui/PrintableUri/PrintableUri.ts
https://coveord.atlassian.net/browse/JSUI-1710
> PrintableUri styling problem

- src/ui/ResultList/ResultList.ts
- src/ui/ResultList/ResultListCardRenderer.ts
https://coveord.atlassian.net/browse/JSUI-1711
> Block "single" card in a single row for card layout with infinite scrolling

- src/misc/L10N.ts
- test/misc/L10NTest.ts
https://coveord.atlassian.net/browse/JSUI-1687
> Remove parameters from translated string if none are provided

- src/ui/Analytics/PendingSearchAsYouTypeSearchEvent.ts
- src/ui/Analytics/PendingSearchEvent.ts
- test/ui/PendingSearchAsYouTypeSearchEventTest.ts
https://coveord.atlassian.net/browse/JSUI-1708
> Add mechanism to keep original value of "q" with pending search event

- src/ui/Facet/BreadcrumbValuesList.ts
https://coveord.atlassian.net/browse/JSUI-1706
> Remove overlapped SVG icon when breadcrumb has a lot of results

- sass/_ResultRating.scss
https://coveord.atlassian.net/browse/JSUI-1721
> fix alignment result rating star

- gulpTasks/filetypes.js
- pages/index.html
- sass/_CardOverlay.scss
- src/ui/Base/ComponentOptions.ts
- src/ui/CardOverlay/CardOverlay.ts
- test/ui/CardOverlayTest.ts
> Jsui 1724 card overlay icons

- sass/_Email.scss
- sass/_Quickview.scss
https://coveord.atlassian.net/browse/JSUI-1724
> fix styling email quickview

- sass/_SimpleFilter.scss
https://coveord.atlassian.net/browse/JSUI-1729
> Margin to separate SimpleFilters when there a more than one in the page.

- sass/_InitializationPlaceholder.scss
- sass/_SimpleFilter.scss
- src/ui/SimpleFilter/SimpleFilter.ts
https://coveord.atlassian.net/browse/JSUI-1733
> Hide SimpleFilter(s) during initialization

- sass/_SimpleFilter.scss
- src/ui/SimpleFilter/SimpleFilter.ts
https://coveord.atlassian.net/browse/JSUI-1730
> SimpleFilter circle hidden when no values selected.

- sass/_SimpleFilter.scss
https://coveord.atlassian.net/browse/JSUI-1732
> Removed left padding for simplefilter wrapper

- src/ui/SimpleFilter/SimpleFilter.ts
https://coveord.atlassian.net/browse/JSUI-1734
> SimpleFilter HTML titles for each label.

- sass/_SimpleFilter.scss
- src/ui/SimpleFilter/SimpleFilter.ts
https://coveord.atlassian.net/browse/JSUI-1736
> SimpleFilter min and max width instead of hardcoded width.

- src/ui/Base/Initialization.ts
- src/ui/Base/RegisteredNamedMethods.ts
- src/utils/PublicPathUtils.ts
- test/utils/PublicPathUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-1739
> fix typo "ressource" for "resource"

- sass/_SimpleFilter.scss
- src/ui/SimpleFilter/SimpleFilter.ts
https://coveord.atlassian.net/browse/JSUI-1737
> Left align simpleFilter text, right align toggle down arrow SVG

- sass/_SimpleFilter.scss
- src/ui/SimpleFilter/SimpleFilter.ts
https://coveord.atlassian.net/browse/JSUI-1735
> Add tabindex for SimpleFilter keyboard navigation

- src/ui/SimpleFilter/SimpleFilter.ts
- test/ui/SimpleFilterTest.ts
https://coveord.atlassian.net/browse/JSUI-1747
> SimpleFilter: Modified a test and fixed getValueCaption

- package.json
- src/ui/SimpleFilter/SimpleFilter.ts
- style.transform.js
- webpack.config.js
> allow blocking dynamic styles loading

- src/ui/PipelineContext/PipelineContext.ts
https://coveord.atlassian.net/browse/JSUI-1750
> PipelineContext doc : corrected typo and added example.

- docs/playground/src/PlaygroundConfiguration.ts
- Added a result list (showing 3 results) in the live example
- Also added a `coveo-sort-section` div to make the `Sort` component look
better in live example
> DOC-1269 Example of Sort not showing anything relevant

- strings/strings.json
provisioning
- Fixed some typos in French strings.
> DOC-1272 [String] Display friendly message when org is not done

- src/ui/Base/ComponentOptions.ts
So yeah, it took me a while to decide to dive in the code and figure this out on my own 😐 
@fbeaudoincoveo, care to have a look at this? 😸 
> Added note for "float:true" in buildNumberOption to build a float option

- sass/notifications/_SubscriptionsMessages.scss
- src/ui/SearchAlerts/SearchAlertsMessage.ts
https://coveord.atlassian.net/browse/JSUI-1742
> Follow Item message was partially hidden in MobileView

- src/rest/SearchEndpoint.ts
https://coveord.atlassian.net/browse/JSUI-1686
> Referer, visitorId and isGuestUser sent to searchAPI

- src/ui/Templates/HtmlTemplate.ts
- src/ui/Templates/Template.ts
- src/ui/Templates/UnderscoreTemplate.ts
- strings/strings.json
https://coveord.atlassian.net/browse/JSUI-1741
> UnderScoreTemplates fall back to default if they fail.

- src/models/QueryStateModel.ts
- src/ui/Base/RegisteredNamedMethods.ts
- Also revised the `Coveo.state` documentation.
> DOC-1283 - Revise content of Class QueryStateModel

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/SimpleFilter/SimpleFilter.ts
- src/ui/Templates/Template.ts
https://coveord.atlassian.net/browse/JSUI-1757
> SimpleFilter usage analytics

- src/rest/GroupByRequest.ts
> DOC-783 - Improve IGroupByRequest documentation

- src/ExternalModulesShim.ts
- src/ui/Omnibox/Omnibox.ts
- src/ui/Querybox/Querybox.ts
- webpack.config.js
https://coveord.atlassian.net/browse/JSUI-1783
> use webpack alias, use unminifed external modules in dev server

- webpack.config.js
> full path for provide plugin, failed me when using link npm package magicbox

- src/ui/PipelineContext/PipelineContext.ts
- src/ui/Querybox/Querybox.ts
https://coveord.atlassian.net/browse/JSUI-1789
> remove autofocus option, fix variable type

- gulpTasks/test.js
- karma.conf.js
https://coveord.atlassian.net/browse/JSUI-1796
> Testing travis build with flaky UT

- .travis.yml
- package-lock.json
https://coveord.atlassian.net/browse/JSUI-1798
> update node/npm version

- src/ui/ResultLayout/ResultLayout.ts
- src/ui/ResultList/ResultList.ts
- test/ui/ResultLayoutTest.ts
https://coveord.atlassian.net/browse/JSUI-1781
Please advise if this case be accounted for in a unit test.
> JSUI-1781 Prevent duplicate ResultLayouts from appearing in the UI

- src/ui/QuerySummary/QuerySummary.ts
- strings/strings.json
- test/ui/QuerySummaryTest.ts
https://coveord.atlassian.net/browse/JSUI-1803
> Recall the search term in query summary

- src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdown.ts
https://coveord.atlassian.net/browse/JSUI-1813
> Add missing css class for ResponsiveDropdown

- sass/mixins/_resultsHeaderElement.scss
https://coveord.atlassian.net/browse/JSUI-1814
> Change default outline for result header section elements

- pages/All.html
- pages/Recommendation.html
- pages/index.html
https://coveord.atlassian.net/browse/JSUI-1785
> Remove search alerts from default search pages

- src/ui/ErrorReport/ErrorReport.ts
- test/ui/ErrorReportTest.ts
https://coveord.atlassian.net/browse/JSUI-1815
> Remove duplicate error report options

- package-lock.json
- package.json
https://coveord.atlassian.net/browse/JSUI-1823
> Update magic box dependency

- src/events/DistanceEvents.ts
- src/ui/Distance/DistanceResources.ts
- src/ui/Distance/GoogleApiPositionProvider.ts
- src/ui/Distance/NavigatorPositionProvider.ts
- src/ui/Distance/StaticPositionProvider.ts
- Reviewed `DistanceResources` related reference documentation.
- Removed some unused imports.
- Also removed a pipe from the Facet availableSorts buildListOption
template; there was an error when building the docs site.
> Documentation revision for DistanceResources

- pages/Email.html
- pages/Jira.html
- pages/SalesforceCase.html
https://coveord.atlassian.net/browse/IE-152
Note: Interface editor will need to update package.json to use the latest JSUI for the change to appear.
> adding periods to template descriptions

- src/ui/Base/ExpressionBuilder.ts
https://coveord.atlassian.net/browse/JSUI-1842
> accessor for the parts of an expression builder

- src/ui/Templates/DefaultRecommendationTemplate.ts
https://coveord.atlassian.net/browse/JSUI-1839
> Remove icon label for default Recommendation template

- templates/Chatter/FeedComment.html
https://coveord.atlassian.net/browse/JSUI-1870
> Use default icon for FeedComment

- src/ui/Quickview/QuickviewDocument.ts
> Small quickview fix for High resolution quickview

- src/ui/Facet/BreadcrumbValuesList.ts
- templates/Chatter/FeedComment.html
- test/Test.ts
- test/ui/BreadcrumbValuesListTest.ts
Add UT for BreadcrumbValuesList
https://coveord.atlassian.net/browse/JSUI-1872
> Fix issue with Breadcrumb not adding excluded with selected values

- src/ui/FieldValue/FieldValue.ts
- templates/YouTube/YouTubeVideo.html
UT for this were passing as we are doing tests with "eager loading" only for unit tests.
I'm still wondering what exactly we could do to trap those (and if there's anything we actually wanna do), without making the tests excessively intrusive, hard to maintain and a pain to write ...
https://coveord.atlassian.net/browse/JSUI-1884
> Handle facet reference properly with Lazy Loading

- src/ui/Debug/Debug.ts
- src/ui/Debug/DebugHeader.ts
https://coveord.atlassian.net/browse/JSUI-1892
> Update search functionality in debug panel when body of the debug panel gets updated

- src/ui/ExportToExcel/ExportToExcel.ts
- test/ui/ExportToExcelTest.ts
https://coveord.atlassian.net/browse/JSUI-1853
> Removed fields to include from the query when not specified explicitely in the export to excel component

- src/ui/ResultsPreferences/ResultsPreferences.ts
https://coveord.atlassian.net/browse/JSUI-1885
> Check for label match in preferences

- src/ui/ResultLink/ResultLink.ts
- test/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-1893
> Better click event tracking

- src/ui/FormWidgets/Checkbox.ts
- src/ui/SimpleFilter/SimpleFilter.ts
- test/ui/SimpleFilterTest.ts
https://coveord.atlassian.net/browse/JSUI-1848
> Improvements for keyboard navigation for SimpleFilter

- pages/SalesforceCase.html
https://coveord.atlassian.net/browse/JSUI-1826
> Change the tab for Cases in Salesforce

- sass/_Debug.scss
- sass/_FullSearchGrid.scss
- sass/_ResponsiveComponents.scss
https://coveord.atlassian.net/browse/JSUI-1874
> Add padding to debug header + fix some css issues with variable usage in sass

- src/rest/AnalyticsEndpoint.ts
- src/rest/EndpointCaller.ts
- src/rest/SearchEndpoint.ts
- src/ui/Debug/DebugHeader.ts
- src/utils/HashUtils.ts
- src/utils/Utils.ts
- test/Test.ts
- test/utils/UtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-1900
> Changes usage of encodeURIComponent to a "safe" versions that handles invalid characters

- .travis.yml
- webpack.config.js
https://coveord.atlassian.net/browse/JSUI-1896
> Add minimization for css files

- sass/_FacetHeader.scss
- src/ui/Facet/FacetSettings.ts
https://coveord.atlassian.net/browse/JSUI-1934
> Use vertical align for facet header svg

- src/ui/ResponsiveComponents/ResponsiveComponentsManager.ts
https://coveord.atlassian.net/browse/JSUI-1947
> JSUI-1947 Switching resize debouncer immediate to false

- sass/_ResultsPreferences.scss
- src/ui/ResultsPreferences/ResultsPreferences.ts
https://coveord.atlassian.net/browse/JSUI-1907
> Display block for ResultsPreferences checkbox-label

- src/ui/Omnibox/FieldAddon.ts
- test/ui/OmniboxTest.ts
https://coveord.atlassian.net/browse/JSUI-1940
> Always return '@' for FieldAddon proposing field values.

- .travis.yml
- sass/mixins/_slider.scss
- src/ui/Misc/Slider.ts
https://coveord.atlassian.net/browse/JSUI-1860
> Modify tooltip positioning when outside the viewport.

- src/Core.ts
- webpack.config.js
New polyfill trigger that will detect existing polyfills
> Changed Promise polyfill trigger [JSUI-1957]

- sass/_SimpleFilter.scss
https://coveord.atlassian.net/browse/JSUI-1908
> Fix height for SimpleFilter component selection

- pages/All.html
- pages/Chatter.html
- pages/Confluence.html
- pages/Dropbox.html
- pages/DynamicsCrm.html
- pages/Email.html
- pages/GoogleDrive.html
- pages/Jira.html
- pages/Lithium.html
- pages/People.html
- pages/Recommendation.html
- pages/Salesforce.html
- pages/SalesforceCase.html
- pages/SharePoint.html
- pages/Slack.html
- pages/YouTube.html
- pages/index.html
- sass/_DidYouMean.scss
Also some automatic code formatting in all .html pages
https://coveord.atlassian.net/browse/JSUI-1955
Accompanied by : 
https://coveord.atlassian.net/browse/IE-269
> Update did you mean look + position in sample pages

- package.json
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-1958
> update magicbox dependency

- package.json
- src/ui/ResponsiveComponents/ResponsiveTabs.ts
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-1904
> Small tweaks to responsive tab logic

- src/ui/Omnibox/Omnibox.ts
- src/ui/Querybox/Querybox.ts
https://coveord.atlassian.net/browse/JSUI-1960
> Change default value for query on clear

- src/ui/Base/ComponentOptions.ts
https://coveord.atlassian.net/browse/JSUI-1993
> add alias for buildtemplateoption in ComponentOptions to avoid breaking change

- sass/_SearchInterface.scss
https://coveord.atlassian.net/browse/JSUI-1992
> add more specific display flex

- src/utils/DomUtils.ts
https://coveord.atlassian.net/browse/JSUI-1972
> fix default title for quickview

- src/misc/PromisesShim.ts
I left a debugger statement in the previous PR. Obviously, that's bad.
> JSUI-1996, typo

- src/ui/YouTube/YouTubeThumbnail.ts
- src/utils/DomUtils.ts
- test/utils/DomUtilsTest.ts
> youtube thumbnail fix

- src/ui/Querybox/Querybox.ts
- Explain how partial match deals with repeated keywords and thesaurus/stemming expansions
- Minor/cosmetic documentation changes
> DOC-1420 Thoroughly document the partial match feature

- sass/_FullSearchGrid.scss
- sass/mixins/_default_display_properties.scss
- src/ui/Querybox/Querybox.ts
- src/ui/SearchInterface/SearchInterface.ts
> reset to default display styles after init

- src/controllers/HistoryController.ts
- src/ui/SearchInterface/SearchInterface.ts
- test/controllers/HistoryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-1998
> revert change to history controller signature

- gulpTasks/definition.js
- src/controllers/HistoryController.ts
- src/ui/SearchInterface/SearchInterface.ts
- test/controllers/HistoryControllerTest.ts
> remove undefined type from search-ui definitions

- src/misc/SentryLogger.ts
https://coveord.atlassian.net/browse/JSUI-2006
> Add return value to Sentry onerror handler [JSUI-2006]

- src/ui/AnalyticsSuggestions/AnalyticsSuggestions.ts
> Fixed typo

- src/ui/Folding/Folding.ts
> Add note in `field` option documentation

- src/ui/CardActionBar/CardActionBar.ts
- Remove example from component description
- Review component documentation (cosmetic changes)
> DOC-2359 Remove h3 in CardActionBar component documentation

- src/ui/Sort/Sort.ts
> Doc 2453 update Sort component documentation

- src/ui/Base/QueryBuilder.ts
> [DOC-2375] Update `context`, `addContext`, and `addContextValue` documentation

- src/controllers/HistoryController.ts
- test/MockEnvironment.ts
- test/controllers/HistoryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2031
> dont set hash when it has't changed on the first hash change

- src/ui/ResultList/ResultList.ts
> minor documentation glitch in ResultLink

- gulpTasks/dev.js
- src/ui/FacetRange/FacetRange.ts
- test/ui/FacetRangeTest.ts
https://coveord.atlassian.net/browse/JSUI-1932
> Uniformize the date output for facet range

- src/ui/Facet/Facet.ts
- src/ui/Facet/FacetValues.ts
- test/ui/FacetValuesTest.ts
https://coveord.atlassian.net/browse/JSUI-2028
> Always import from active list as 0 occurences if not returned

- src/ui/FacetSlider/FacetSlider.ts
No UT, because I think it more properly tested with functional tests (since it's closely linked to visual appearance, which is hard to test for properly in UT).
https://coveord.atlassian.net/browse/JSUI-1975
> Defer update appearance for FacetSlider

- src/ui/QuerySummary/QuerySummary.ts
- strings/strings.json
- test/ui/QuerySummaryTest.ts
https://coveord.atlassian.net/browse/JSUI-2046
> Auto configure query summary in infinite scroll

- sass/_SimpleFilter.scss
- sass/_Variables.scss
https://coveord.atlassian.net/browse/JSUI-1962
> Visual tweaks for SimpleFilter + background dropdown

- sass/_Debug.scss
https://coveord.atlassian.net/browse/JSUI-2007
> Add min-width to debug modal content

- src/misc/SuggestionsCache.ts
- test/misc/SuggestionsCacheTest.ts
https://coveord.atlassian.net/browse/JSUI-2004
> Change SuggestionCache to requests suggestions when there is no text in searchbox

- src/ui/Base/QueryBuilder.ts
- src/ui/Sort/Sort.ts
- src/ui/Sort/SortCriteria.ts
- test/ui/SortCriteriaTest.ts
- test/ui/SortTest.ts
> Support adding multiple Sort criteria for multi sort in the index.

- src/ui/FacetValueSuggestions/FacetValueSuggestions.ts
https://coveord.atlassian.net/browse/JSUI-2088
> Fix number of suggestions missing 1 result

- src/ui/FacetValueSuggestions/FacetValueSuggestions.ts
- test/ui/FacetValueSuggestionsTest.ts
https://coveord.atlassian.net/browse/JSUI-2088
> Handle corner case + UT for numberOfSuggestions

- src/ui/FacetValueSuggestions/FacetValueSuggestions.ts
- test/ui/FacetValueSuggestionsTest.ts
https://coveord.atlassian.net/browse/JSUI-2089
> Handle empty search box in FacetValueSuggestions

- sass/_RelevanceInspector.scss
https://coveord.atlassian.net/browse/JSUI-2092
> Fixed word-break RelevanceInspector

- src/ui/Templates/CoreHelpers.ts
Added syntax as well as functionality examples in comments for clarity.
> Added documentation comment to ISizeOptions for clarity

- src/ui/Templates/TemplateFromAScriptTag.ts
- test/ui/TemplateFromAScriptTagTest.ts
https://coveord.atlassian.net/browse/JSUI-2091
> Support underscore and dots in fields condition

- templates/Chatter/FeedComment.html
https://coveord.atlassian.net/browse/JSUI-2076
> Tweaks feed comment template

- sass/_HiddenQuery.scss
https://coveord.atlassian.net/browse/JSUI-2086
> Change alignment to vertical-align middle

- src/utils/DateUtils.ts
> DOC-2868 added legend for date format

- src/ui/Omnibox/Omnibox.ts
- src/ui/Templates/CoreHelpers.ts
Further improved the formatting as well as fixed grammatical errors.
> Doc 2272 add more infor in the doc for isizeoptions

- src/ui/Tab/Tab.ts
- Added link to data-tab/data-tab-not external topic
- Removed info about data-tab/data-tab-not reference doc
> Add reference to data-tab external docs in Tab reference

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryFacetSearch.ts
- src/ui/CategoryFacet/CategoryValue.ts
- test/ui/CategoryFacet/CategoryFacetTest.ts
Small PR for analytics calls for the category facet.
> category facet - add analytics

- README.md
- src/controllers/FacetSliderQueryController.ts
- src/ui/FacetSlider/FacetSlider.ts
- test/ui/FacetSliderTest.ts
https://coveord.atlassian.net/browse/JSUI-2069
> Draw facet slider when the group by results are empty

- sass/_FacetSearch.scss
- sass/_FacetSettings.scss
- sass/_FieldTable.scss
- sass/_ResultsPerPage.scss
- sass/_Tab.scss
- sass/_Variables.scss
- sass/mixins/_pagerList.scss
- src/ui/Facet/FacetSettings.ts
https://coveord.atlassian.net/browse/JSUI-2121
> Change color contrast for default "clickable" stuff

- pages/index.html
- src/ui/CategoryFacet/CategoryFacet.ts
https://coveord.atlassian.net/browse/JSUI-2140
> remove categoryfacet component from index.html, comment out jsdoc

- sass/_ResultTagging.scss
https://coveord.atlassian.net/browse/JSUI-2146
> Specify the selector for ResultTagging

- src/ui/SimpleFilter/SimpleFilter.ts
https://coveord.atlassian.net/browse/JSUI-2142
> Check for non null related target

- src/ui/FacetSlider/FacetSlider.ts
- unitTests/ui/FacetSliderTest.ts
https://coveord.atlassian.net/browse/JSUI-2129
> Add a check before calling "onMoving"

- sass/_Debug.scss
https://coveord.atlassian.net/browse/JSUI-2151
> Change from word-wrap: pre to pre-wrap to allow word wrapping

- src/magicbox/InputManager.ts
- src/ui/Omnibox/Omnibox.ts
- unitTests/Simulate.ts
- unitTests/ui/OmniboxTest.ts
> Handle tabpress in magicbox more "naturally"

- src/controllers/FacetQueryController.ts
- src/ui/Base/QueryBuilder.ts
- src/ui/Base/QueryBuilderExpression.ts
- unitTests/controllers/FacetQueryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2156
> Do not add useless query overrides to facet that do not need them

- src/ui/Quickview/Quickview.ts
> [DOC-3107] - added note about quickview limitations

- src/ui/Base/InitializationPlaceholder.ts
- src/ui/SearchInterface/SearchInterface.ts
- src/ui/Settings/Settings.ts
- unitTests/Simulate.ts
- unitTests/ui/SearchInterfaceTest.ts
> Switch back the interface to "waiting mode" when the search box is manually cleared by the end user

- src/ui/FormWidgets/Checkbox.ts
- src/ui/FormWidgets/FormGroup.ts
- unitTests/ui/CheckboxTest.ts
- unitTests/ui/FormGroupTest.ts
https://coveord.atlassian.net/browse/JSUI-2179
> Prevent XSS + tests in some basic form elements

- src/ui/Facet/Facet.ts
- unitTests/ui/FacetTest.ts
- unitTests/ui/TimespanFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2137
> Facet ID should not support white spaces

- sass/_OmniboxResultList.scss
https://coveord.atlassian.net/browse/JSUI-2074
> Specify omnibox result list selectors to take different layouts into account

- src/ui/Omnibox/Omnibox.ts
- src/ui/Querybox/Querybox.ts
- src/ui/Querybox/QueryboxOptionsProcessing.ts
- src/ui/SearchInterface/SearchInterface.ts
- unitTests/ui/OmniboxTest.ts
- unitTests/ui/QueryboxTest.ts
- unitTests/ui/SearchInterfaceTest.ts
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-2188
> Better handling for corner case for allowQueriesWithoutKeywords

- src/ui/Base/ComponentOptions.ts
- src/ui/Facet/Facet.ts
- src/ui/FacetSlider/FacetSlider.ts
- src/ui/FieldSuggestions/FieldSuggestions.ts
- src/ui/Folding/Folding.ts
- src/ui/OmniboxResultList/OmniboxResultList.ts
- src/ui/SearchInterface/SearchInterface.ts
- src/ui/Tab/Tab.ts
- unitTests/ui/ComponentOptionsTest.ts
https://coveord.atlassian.net/browse/JSUI-2172
Added a dedicated option type for "QueryExpression"
> Added a dedicated option type for "QueryExpression"

- src/magicbox/MagicBox.ts
- src/magicbox/MagicBoxClear.ts
- unitTests/Test.ts
- unitTests/magicbox/MagicBoxClearTest.ts
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-2169
> Magic box, clear button : Accessibility fixes.

- src/utils/DateUtils.ts
- unitTests/ui/DateUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-2181
> Fix dateTimeToString to always respect predefined format

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/Facet/Facet.ts
- unitTests/ui/FacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2108
> Log custom event on facet update sort

- src/ui/Debug/Debug.ts
- src/ui/Debug/DebugHeader.ts
- src/ui/Pager/Pager.ts
- unitTests/ui/DebugHeaderTest.ts
- unitTests/ui/PagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2155
> Executing queries while inside the debug panel should not "reset" the pager

- src/ui/SimpleFilter/SimpleFilter.ts
Some minor issues found while investigating this jira
https://coveord.atlassian.net/browse/JSUI-2077
> Minor tweaks to SimpleFilter

- src/ui/Facet/DependentFacetManager.ts
- src/ui/Facet/Facet.ts
- unitTests/ui/FacetTest.ts
> JSUI-2189  Resetting dependent facets when no parent facet options are selected

- package.json
- src/ui/Folding/Folding.ts
- unitTests/ui/FoldingTest.ts
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-2149
> Log and trap error on folding expand

- accessibilityTest/AccessibilityCardOverlay.ts
- accessibilityTest/AccessibilityResultList.ts
- sass/_Debug.scss
- sass/_FacetBreadcrumb.scss
- sass/_FieldTable.scss
- sass/_HiddenQuery.scss
- sass/_ResultLink.scss
- sass/_ResultsFiltersPreferences.scss
- sass/_SimpleFilter.scss
- sass/_Variables.scss
- sass/mixins/_pagerList.scss
https://coveord.atlassian.net/browse/JSUI-2201
> Modify links color with dark background + new accessibility tests

- src/controllers/HistoryController.ts
- unitTests/controllers/HistoryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2202
> Ignore hash change when simply replacing the state

- src/ui/QuerySummary/QuerySummary.ts
- unitTests/ui/QuerySummaryTest.ts
https://coveord.atlassian.net/browse/JSUI-2203
> Adjust how we escape html in query summary custom message

- gulpTasks/doc.js
Check if json is defined and non-empty
Check that all attributes are defined correctly
Check that some specific doc elements are present
https://coveord.atlassian.net/browse/JSUI-2168
> Add post-build test to check if docgen.json is generated correctly

- src/ui/ResultLayoutSelector/ResultLayoutSelector.ts
- src/ui/Sort/Sort.ts
- src/utils/AccessibleButton.ts
- strings/strings.json
- unitTests/ui/SortTest.ts
- unitTests/utils/AccessibleButtonTest.ts
> JSUI-2234 Improving labels for layout selector and result sort buttons.

- src/ui/Quickview/Quickview.ts
Only build the tooltip if the parent is not a card. There is not tooltip on cards quickview elements
https://coveord.atlassian.net/browse/JSUI-2207
> JSUI-2207 Only build the quickview tooltip if the parent is not a card

- src/magicbox/InputManager.ts
- strings/strings.json
https://coveord.atlassian.net/browse/JSUI-2235
> JSUI-2235 Adding search box explanation in title attribute

- sass/_Debug.scss
https://coveord.atlassian.net/browse/JSUI-2180
Result:
> Modify styling of the checkbox & checkbox label in the Debug modal

- src/ui/Templates/Template.ts
- unitTests/ui/TemplateTest.ts
https://coveord.atlassian.net/browse/JSUI-2232
> JSUI-2232 Adding accessibility attributes to result root element

- sass/_ResponsiveTabs.scss
- src/ui/ResponsiveComponents/ResponsiveTabs.ts
> JSUI-2238 Adding text-overflow ellipsis to cut-off long tab names

- src/ui/Quickview/Quickview.ts
- src/ui/ResultFolding/ResultFolding.ts
- unitTests/ui/QuickviewTest.ts
- unitTests/ui/ResultFoldingTest.ts
- unitTests/utils/QueryUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-2213
> JSUI-2213 Link childrenResult to resultElement & prevent quickview propagation

- sass/_CategoryFacet.scss
https://coveord.atlassian.net/browse/JSUI-2250
> Display block for category facet breadcrumb

- sass/_CategoryFacet.scss
- sass/_CategoryFacetSearch.scss
https://coveord.atlassian.net/browse/JSUI-2247
> CSS adjustment to CategoryFacet color + Search button

- src/controllers/FacetSliderQueryController.ts
- src/ui/FacetSlider/FacetSlider.ts
- unitTests/controllers/FacetSliderQueryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2222
> Rework the query sent for full range of the slider to filter out invalid documents

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryFacetSearch.ts
- src/ui/CategoryFacet/CategoryValue.ts
- unitTests/Simulate.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2265
> Improve breadcrumb support + UT for CategoryFacet

- sass/_CategoryFacet.scss
- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryValue.ts
- src/ui/CategoryFacet/CategoryValueChildrenRenderer.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2256
> Change CategoryFacet to remove no-op click for current active filter

- src/models/QueryStateModel.ts
- src/ui/CategoryFacet/CategoryFacet.ts
- unitTests/models/QueryStateModelTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
- unitTests/ui/InitializationPlaceholderTest.ts
https://coveord.atlassian.net/browse/JSUI-2261
> Better "no results" handling for CategoryFacet

- src/ui/CategoryFacet/CategoryFacet.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2260
> Fix CategoryFacet ellipse position

- lib/jasmine/index.d.ts
- src/controllers/CategoryFacetQueryController.ts
- unitTests/Test.ts
- unitTests/controllers/CategoryFacetQueryControlllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2258
> CategoryFacetSearch should try to return values ordered by the path length

- src/ui/CategoryFacet/CategoryFacet.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2257
> Add check on existence of CategoryFacetSearch + tests

- sass/_CategoryFacetSearch.scss
- src/ui/CategoryFacet/CategoryFacetSearch.ts
https://coveord.atlassian.net/browse/JSUI-2255
> Add CSS tweaks for very long path in facet search + title

- sass/_FacetSettings.scss
- sass/_ResponsiveFacets.scss
https://coveord.atlassian.net/browse/JSUI-2242
> Remove duplicate z-index on FacetSettings popup

- src/magicbox/MagicBox.ts
- src/magicbox/SuggestionsManager.ts
- unitTests/magicbox/SuggestionsManagerTest.ts
This issue was introduced when working on JSUI-2130
https://coveord.atlassian.net/browse/JSUI-2229
> Do not process "keyboardFocusedSuggestion" twice in a row.

- src/utils/Dom.ts
- unitTests/utils/DomTest.ts
User can use native js event by doing something like
```javascript
Coveo.Dom.useNativeJavascriptEvents = true;
```
> Add an option to force native javascript event on the Dom class JSUI-2249

- README.md
> DOC-3765 update download links in README

- src/ui/CategoryFacet/CategoryFacetSearch.ts
- src/ui/Facet/FacetSearchElement.ts
- unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts
https://coveord.atlassian.net/browse/JSUI-2286
> Do not render "last" child value in facet search values

- src/utils/QuerySummaryUtils.ts
- unitTests/ui/QuerySummaryTest.ts
https://coveord.atlassian.net/browse/JSUI-2285
> Use underscore escape function instead of DOM escape

- src/ui/ResponsiveComponents/ResponsiveTabs.ts
- src/utils/Utils.ts
- unitTests/ui/ResponsiveComponents/ResponsiveTabsTest.ts
https://coveord.atlassian.net/browse/JSUI-2290
> Shenanigans to ensure Tab components order when resizing the page

- src/ui/FieldValue/FieldValue.ts
- unitTests/ui/FieldValueTest.ts
https://coveord.atlassian.net/browse/JSUI-2294
> Use translated values for title and aria label

- package.json
- src/ui/FieldValue/FieldValue.ts
- src/utils/UrlUtils.ts
- unitTests/utils/UrlUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-2307
> Support adding cache=0 in query string param search endpoint config.

- src/ui/ResponsiveComponents/ResponsiveFacetColumn.ts
- src/ui/ResponsiveComponents/ResponsiveTabs.ts
- unitTests/ui/ResponsiveComponents/ResponsiveFacetsTest.ts
- unitTests/ui/ResponsiveComponents/ResponsiveTabsTest.ts
https://coveord.atlassian.net/browse/JSUI-2312
> Properly support medium and large mode

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryFacetTemplates.ts
"Less button" and "All Categories" are now "tabbable"
https://coveord.atlassian.net/browse/JSUI-2316
> JSUI-2316 Fix tabindex on facet-less, add tabindex on all-categories-caption

- src/models/QueryStateModel.ts
- src/ui/Base/QueryBuilder.ts
- src/ui/ResultsPerPage/ResultsPerPage.ts
- unitTests/ui/ResultsPerPageTest.ts
https://coveord.atlassian.net/browse/JSUI-2313
> JSUI-2313 Synchronizing ResultsPerPage components using new #rpp attribute in QSM

- src/ui/Misc/Slider.ts
- unitTests/ui/SliderTest.ts
Not sure how to unit test this correctly, but before the fix, the unit test I added was causing the infinite loop problem
> JSUI-2319 Prevent division by 0 issue in the Slider graph data

- .travis.yml
- src/magicbox/SuggestionsManager.ts
- unitTests/magicbox/SuggestionsManagerTest.ts
> JSUI-2320 Prevent adding new aria-expanded elements

- src/utils/StreamHighlightUtils.ts
- unitTests/ui/CoreHelpersTest.ts
- unitTests/utils/StreamHighlightUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-2241
> JSUI-2241 Prevent highlighting of the same piece of text twice

- src/controllers/FacetQueryController.ts
- src/ui/Base/QueryBuilderExpression.ts
- unitTests/controllers/FacetQueryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2324
> Additional filter shenanigans

- src/controllers/CategoryFacetQueryController.ts
- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryFacetBreadcrumb.ts
- unitTests/controllers/CategoryFacetQueryControlllerTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetBreadcrumbTest.ts
https://coveord.atlassian.net/browse/JSUI-2264
> Inactive category facet should not set a filter in the query

- src/controllers/CategoryFacetQueryController.ts
- src/ui/CategoryFacet/CategoryFacet.ts
- unitTests/controllers/CategoryFacetQueryControlllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2262
> Take base path into account when performing category facet searches

- src/ui/ResultLayoutSelector/ResultLayoutSelector.ts
- unitTests/ui/ResultLayoutTest.ts
https://coveord.atlassian.net/browse/JSUI-2220
> Changing logic to allow enabling layout for a disabled result list

- sass/_SearchInterface.scss
https://coveord.atlassian.net/browse/JSUI-2299
> Move coveo scoped highlight rule to global scope

- src/ui/Facet/FacetUtils.ts
- src/ui/SimpleFilter/SimpleFilter.ts
- unitTests/Test.ts
- unitTests/utils/FacetUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-2297
> Do not translate "month" field with invalid month value

- sass/_PrintableUri.scss
https://coveord.atlassian.net/browse/JSUI-2160
> Add line height for PrintableURI in card layout

- src/ui/Analytics/AnalyticsActionListMeta.ts
- unitTests/ui/SimpleFilterTest.ts
https://coveord.atlassian.net/browse/JSUI-2147
> Change UA string for deselect value

- src/magicbox/SuggestionsManager.ts
- unitTests/magicbox/SuggestionsManagerTest.ts
> JSUI-2329 [Accessibility] Only render the suggestions container if there are suggestions

- sass/_CategoryFacet.scss
- sass/_ResultsFiltersPreferences.scss
- src/ui/CategoryFacet/CategoryFacetBreadcrumb.ts
- src/ui/ResultLink/ResultLink.ts
- src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
- unitTests/ui/CategoryFacet/CategoryFacetBreadcrumbTest.ts
- unitTests/ui/ResultsFiltersPreferencesTest.ts
https://coveord.atlassian.net/browse/JSUI-2316
> JSUI-2316 Make the Category Facet Breadcrumb & Preference Breadcrumb Accessible

- src/ui/ResponsiveComponents/ResponsiveTabs.ts
https://coveord.atlassian.net/browse/JSUI-2336
> Fix un-elegant console error when related target not available in focus event

- src/ui/Facet/FacetHeader.ts
https://coveord.atlassian.net/browse/JSUI-2281
> Add keyboard support for facet toggle operator

- sass/_ResponsiveTabs.scss
https://coveord.atlassian.net/browse/JSUI-2347
> Left align text in tabs

- sass/_Facet.scss
https://coveord.atlassian.net/browse/JSUI-2339
> Enforce no border on timespan facet

- src/ui/ResultList/ResultList.ts
- unitTests/ui/ResultListTest.ts
https://coveord.atlassian.net/browse/JSUI-2352
> JSUI-2352 Supporting coveo-show-if-results class on layout switch

- src/rest/SearchEndpoint.ts
- unitTests/rest/SearchEndpointTest.ts
https://coveord.atlassian.net/browse/JSUI-2341
> JSUI-2341 Adding timezone to the list of parameters sent in the GET request

- src/ui/Facet/Facet.ts
> Fix typo in Facet dependsOn markup configuration example

- src/ui/CategoryFacet/CategoryFacet.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2351
> Change category value breadcrumb for corner case with base path

- src/ui/CategoryFacet/CategoryFacetSearch.ts
https://coveord.atlassian.net/browse/JSUI-2354
> Dismiss search when clicking on another category facet search container

- src/ui/Facet/Facet.ts
https://coveord.atlassian.net/browse/JSUI-2355
> JSUI-2355 Remove camelcase alphaAscending & alphaDescending

- src/utils/DateUtils.ts
- unitTests/ui/DateUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-2360
> JSUI-2360 Support yyyy in the predefined format

- sass/_FacetHeader.scss
- sass/_Variables.scss
- src/Eager.ts
- src/Lazy.ts
- src/ui/NoNameFacet/LazyNoNameFacet.ts
- src/ui/NoNameFacet/NoNameFacet.ts
- src/ui/NoNameFacet/NoNameFacetHeader.ts
- src/ui/NoNameFacet/NoNameFacetOptions.ts
- src/utils/ComponentsTypes.ts
- unitTests/Test.ts
- unitTests/ui/NoNameFacet/NoNameFacetHeaderTest.ts
> JSUI-2357 [NoName Facets] Create the UI of the header component

- src/Eager.ts
- src/Lazy.ts
Will be more prudent to do it before merging those 😄 
https://coveord.atlassian.net/browse/JSUI-2357
> JSUI-2357 Temporarely comment out NoNameFacet

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryFacetSearch.ts
- src/ui/CategoryFacet/CategoryValue.ts
- src/ui/Facet/Facet.ts
- src/ui/Facet/FacetHeader.ts
- src/ui/Facet/FacetSearch.ts
- src/ui/Facet/FacetSearchElement.ts
- src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdown.ts
- strings/strings.json
- unitTests/ui/ResponsiveComponents/ResponsiveDropdownTest.ts
I have requested answers on this JIRA but I guess we can start reviewing this maintenance case
https://coveord.atlassian.net/browse/JSUI-2367
> JSUI-2367 Accessibility details

- src/ui/Pager/Pager.ts
- unitTests/ui/PagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2371
> Protection against invalid page

- accessibilityTest/AccessibilityFacet.ts
- src/ui/Facet/FacetSearchElement.ts
https://coveord.atlassian.net/browse/JSUI-2367
> JSUI-2367 Facet search accessibility: toggle aria attribute when elements are shown

- src/ui/Facet/Facet.ts
Also add links to TimespanFacet and CategoryFacet documentation
> [DOC-4321] Remove link to HierarchicalFacet documentation

- src/ui/Omnibox/Omnibox.ts
- unitTests/ui/OmniboxTest.ts
https://coveord.atlassian.net/browse/JSUI-2383
> JSUI-2383 Triggering a cancelled query when the lastQuery and omnibox text match

- src/ui/Omnibox/Omnibox.ts
> [DOC-4457] Fix links in Omnibox docs

- .travis.yml
Test whether VERACODE_WRAPPER_VERSION is set to a non-empty string before getting/running the .jar
> [DOC-4481] Make Travis build work with PRs created from forks

- src/controllers/FacetQueryController.ts
- unitTests/controllers/FacetQueryControllerTest.ts
> JSUI-2388 Add basic query override only when there is an additional filter 

- package.json
- src/ui/SearchInterface/SearchInterface.ts
- yarn.lock
Removed from the project with yarn.
No test fails.
See the jira detail for more informations.
> Remove FastClick JSUI-2392

- src/ui/CategoryFacet/CategoryFacet.ts
https://coveord.atlassian.net/browse/JSUI-2395
> JSUI-2395 Logging a warning that the CategoryFacet search box is disabled

- src/ui/MLFacet/MLFacetValues/MLFacetValueRenderer.ts
- unitTests/Test.ts
- unitTests/ui/MLFacet/MLFacetHeader/MLFacetHeaderButtonTest.ts
- unitTests/ui/MLFacet/MLFacetHeader/MLFacetHeaderCollapseToggleTest.ts
- unitTests/ui/MLFacet/MLFacetHeader/MLFacetHeaderTest.ts
- unitTests/ui/MLFacet/MLFacetTestUtils.ts
- unitTests/ui/MLFacet/MLFacetValues/MLFacetValueRendererTest.ts
- unitTests/ui/MLFacet/MLFacetValues/MLFacetValueTest.ts
- unitTests/ui/MLFacet/MLFacetValues/MLFacetValuesTest.ts
Moved some files in sub folders
Mostly the new code is in MLFacetValueTest & MLFacetValueRendererTest
> JSUI-2373 Add unit tests for facet values

- src/ui/Omnibox/QuerySuggestAddon.ts
- unitTests/ui/QuerySuggestAddonTest.ts
https://coveord.atlassian.net/browse/JSUI-2404
> JSUI-2404 Don't send the "tab" parameter to querySuggest if it's an empty string

- src/ui/MLFacet/MLFacet.ts
- unitTests/Test.ts
- unitTests/ui/MLFacet/MLFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2402
> JSUI-2402 Add Unit Tests for MLFacet Component

- src/controllers/MLFacetQueryController.ts
- src/rest/Facet/FacetRequest.ts
- src/rest/Facet/FacetResponse.ts
- src/rest/Facet/FacetSortCriteria.ts
- src/rest/Facet/FacetValueState.ts
- src/rest/Query.ts
- src/rest/QueryResults.ts
- src/ui/Base/QueryBuilder.ts
- src/ui/MLFacet/MLFacet.ts
- src/ui/MLFacet/MLFacetOptions.ts
- src/ui/MLFacet/MLFacetValues/MLFacetValue.ts
- src/ui/MLFacet/MLFacetValues/MLFacetValueRenderer.ts
- src/ui/MLFacet/MLFacetValues/MLFacetValues.ts
- unitTests/Test.ts
- unitTests/controllers/MLFacetQueryControllerTest.ts
- unitTests/rest/Facet/FacetSortCriteriaTest.ts
- unitTests/ui/MLFacet/MLFacetTest.ts
- unitTests/ui/MLFacet/MLFacetTestUtils.ts
- unitTests/ui/MLFacet/MLFacetValues/MLFacetValueTest.ts
- unitTests/ui/MLFacet/MLFacetValues/MLFacetValuesTest.ts
- Change selected boolean to a state enum (like the api)
- Add options
- Create MLFacetQueryController and connect to the API
I will add further tests and functionalities in the next PRs, I just tough it was getting big
> JSUI-2405 Start to Link the ML Facets with the SearchAPI

- yarn.lock
> Update yarn lock file for vulnerabilities

- sass/MLFacet/_MLFacetHeader.scss
- sass/MLFacet/_MLFacetValues.scss
- sass/_Variables.scss
- src/controllers/MLFacetQueryController.ts
- src/ui/MLFacet/MLFacet.ts
- src/ui/MLFacet/MLFacetValues/MLFacetValues.ts
- unitTests/controllers/MLFacetQueryControllerTest.ts
- unitTests/ui/MLFacet/MLFacetTest.ts
- unitTests/ui/MLFacet/MLFacetValues/MLFacetValuesTest.ts
I'm about to come up with some UTs for this
https://coveord.atlassian.net/browse/JSUI-2414
> JSUI-2414 Implement show more/less feature & style components

- sass/MLFacet/_MLFacet.scss
- sass/MLFacet/_MLFacetHeader.scss
- sass/MLFacet/_MLFacetValues.scss
- src/ui/MLFacet/MLFacet.ts
- src/ui/MLFacet/MLFacetHeader/MLFacetHeader.ts
- src/ui/MLFacet/MLFacetHeader/MLFacetHeaderCollapseToggle.ts
- unitTests/ui/MLFacet/MLFacetHeader/MLFacetHeaderCollapseToggleTest.ts
- unitTests/ui/MLFacet/MLFacetHeader/MLFacetHeaderTest.ts
- unitTests/ui/MLFacet/MLFacetTest.ts
- unitTests/ui/MLFacet/MLFacetTestUtils.ts
> JSUI-2415 Add Collapse/Expand Facet Values Functionality

- .travis.yml
- deploy.beta.js
- package.json
> JSUI-2433 Setting node to latest v8 in travis.yml file

- src/ui/Facet/Facet.ts
- src/ui/Omnibox/Omnibox.ts
- src/ui/Querybox/Querybox.ts
- src/ui/Tab/Tab.ts
> JSUI-2430 Regrouping options into different sections

- package.json
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-2438
> JSUI-2438 Snyk played itself, fix vulnerability

- .travis.yml
https://coveord.atlassian.net/browse/JSUI-2448
> JSUI-2448 Yaml: change Veracode condition and fix quotes

- sass/MLFacet/_MLFacetBreadcrumbs.scss
- sass/_AdvancedSearch.scss
- sass/_Breadcrumb.scss
- sass/_CategoryFacet.scss
- sass/_FacetBreadcrumb.scss
- sass/_HiddenQuery.scss
- sass/_ResultsFiltersPreferences.scss
- sass/_SimpleFilter.scss
- sass/_Variables.scss
- sass/mixins/_breadcrumb.scss
- src/ui/AdvancedSearch/AdvancedSearch.ts
- src/ui/Breadcrumb/Breadcrumb.ts
- src/ui/CategoryFacet/CategoryFacetBreadcrumb.ts
- src/ui/Facet/BreadcrumbValueElement.ts
- src/ui/HiddenQuery/HiddenQuery.ts
- src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
- src/ui/SimpleFilter/SimpleFilter.ts
https://coveord.atlassian.net/browse/JSUI-2449
> JSUI-2449 Normalize breadcrumbs markup & style

- package.json
- sass/MLFacet/_MLFacetBreadcrumbs.scss
- sass/_AdvancedSearch.scss
- sass/_Breadcrumb.scss
- sass/_CategoryFacet.scss
- sass/_Common.scss
- sass/_FacetBreadcrumb.scss
- sass/_HiddenQuery.scss
- sass/_ResultsFiltersPreferences.scss
- sass/_SimpleFilter.scss
- sass/_Variables.scss
- sass/mixins/_breadcrumb.scss
- src/controllers/MLFacetQueryController.ts
- src/ui/AdvancedSearch/AdvancedSearch.ts
- src/ui/Breadcrumb/Breadcrumb.ts
- src/ui/CategoryFacet/CategoryFacetBreadcrumb.ts
- src/ui/Facet/BreadcrumbValueElement.ts
- src/ui/HiddenQuery/HiddenQuery.ts
- src/ui/MLFacet/MLFacet.ts
- src/ui/MLFacet/MLFacetBreadcrumbs.ts
- src/ui/MLFacet/MLFacetValues/MLFacetValues.ts
- src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
- src/ui/SimpleFilter/SimpleFilter.ts
- unitTests/Test.ts
- unitTests/ui/MLFacet/MLFacetBreadcrumbsTest.ts
- unitTests/ui/MLFacet/MLFacetHeader/MLFacetHeaderTest.ts
- unitTests/ui/MLFacet/MLFacetTest.ts
- unitTests/ui/MLFacet/MLFacetValues/MLFacetValuesTest.ts
There is another PR coming that will refactor the breadcrumbs to all use the same style
> JSUI-2416 Integrate MLFacet breadcrumbs

- src/controllers/MLFacetQueryController.ts
- src/rest/Facet/FacetRequest.ts
- unitTests/controllers/MLFacetQueryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2464
> JSUI-2397 Implement isFieldExpanded

- sass/MLFacet/_MLFacetHeader.scss
- sass/MLFacet/_MLFacetValues.scss
- sass/_Variables.scss
- src/ui/MLFacet/MLFacetValues/MLFacetValues.ts
Addresses those 3 issues
https://coveord.atlassian.net/browse/JSUI-2474
https://coveord.atlassian.net/browse/JSUI-2476
https://coveord.atlassian.net/browse/JSUI-2477
> JSUI-2477 Various CSS fixes

- package.json
- src/ui/DynamicFacetManager/DynamicFacetManager.ts
- unitTests/ui/DynamicFacetManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2490
> JSUI-2490 Manager to retrieve previously deleted facets

- src/ui/OmniboxResultList/OmniboxResultList.ts
- unitTests/ui/OmniboxResultListTest.ts
https://coveord.atlassian.net/browse/JSUI-2441
> Flag omnibox query as search as you type

- src/rest/SearchEvent.ts
- src/ui/Analytics/PendingSearchEvent.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacetManager/DynamicFacetManager.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
~UTs are coming for this~ they're here!
https://coveord.atlassian.net/browse/JSUI-2397
> JSUI-2397 Add facetsState to Usage Analytics (previously removed)

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetPadding.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueRenderer.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValues.ts
- src/ui/FacetPadding/FacetPadding.ts
- unitTests/Test.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/FacetPaddingTest.ts
Im not sure this is well unit testable, I did a couple tests that made sense on DynamicFacet, but testing FacetPadding is kinda tricky...
I was thinking of adapting the feature for other facets in later PRs
> JSUI-2442 Add padding feature for the DynamicFacet

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValues.ts
- src/ui/FieldValue/FieldValue.ts
- unitTests/ui/FieldValueTest.ts
> JSUI-2482 Adapt FieldValue to work with Dynamic Facets

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValues.ts
- unitTests/ui/DynamicFacet/DynamicFacetBreadcrumbsTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTestUtils.ts
- unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts
https://coveord.atlassian.net/browse/JSUI-2498
> JSUI-2498 Add position (facet + value) to analytics facet state

- sass/_InitializationPlaceholder.scss
https://coveord.atlassian.net/browse/JSUI-2509
> JSUI-2509 Add InitializationPlaceholder styling for DynamicFacets too

- src/ui/MissingTerm/MissingTerms.ts
https://coveord.atlassian.net/browse/JSUI-2524
> [documentation] Expose MissingTerms options in public reference docs

- docs/playground/src/Playground.ts
- docs/playground/src/PlaygroundConfiguration.ts
- docs/theme/assets/js/searchUIrefDoc.js
- docs/theme/layouts/default.hbs
> JSUI-2525 [documentation] Add live example for MissingTerms

- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValues.ts
Was breaking IE11
https://coveord.atlassian.net/browse/JSUI-2531
> JSUI-2351 replace new DocumentFragment by document.createDocumentFragment

- src/ui/CategoryFacet/CategoryFacetSearch.ts
https://coveord.atlassian.net/browse/JSUI-2533
> JSUI-2533 Use correct formatting for CategoryFacetSearch results

- sass/_CategoryFacet.scss
https://coveord.atlassian.net/browse/JSUI-2532
> JSUI-2532 Move height from the container to the children

- src/ui/DynamicFacetManager/DynamicFacetManager.ts
https://coveord.atlassian.net/browse/JSUI-2535
> JSUI-2525 Export DynamicFacetManager correctly

- src/ui/DynamicFacet/DynamicFacet.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2536
> JSUI-2536 Get facet position from the API's response

- sass/MagicBox/MagicBox.scss
https://coveord.atlassian.net/browse/JSUI-2541
> JSUI-2541 Change position left for padding in magic box

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/TimespanFacet/TimespanFacet.ts
https://coveord.atlassian.net/browse/JSUI-2542
> JSUI-2542 Marking Category and Timespan facets as not supported in salesforcefree

- src/events/AnalyticsEvents.ts
- src/ui/Analytics/LiveAnalyticsClient.ts
- src/ui/Analytics/PendingSearchEvent.ts
https://coveord.atlassian.net/browse/JSUI-2543
> JSUI-2543 Event data pushed to GTM data layer should match what is sent to Coveo UA

- src/rest/AnalyticsEvent.ts
- src/rest/ClickEvent.ts
- src/rest/CustomEvent.ts
- src/rest/SearchEvent.ts
> JSUI-2550 Document click / custom / search event interfaces

- src/rest/SearchEvent.ts
- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/Analytics/PendingSearchEvent.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeader.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts
- unitTests/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts
https://coveord.atlassian.net/browse/JSUI-2547
> JSUI-2547 Refactor DynamicFacets analytics meta 

- sass/MagicBox/MagicBox.scss
- sass/_Omnibox.scss
- sass/_Querybox.scss
- sass/_Searchbox.scss
- src/ui/Querybox/Querybox.ts
https://coveord.atlassian.net/browse/JSUI-2534
> JSUI-2534 Fix Querybox style & centralize flex grow

- package.json
https://coveord.atlassian.net/browse/JSUI-2500
> JSUI-2500 Move snyk into devDependencies

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/MissingTerm/MissingTermManager.ts
- src/ui/MissingTerm/MissingTerms.ts
- src/ui/SearchInterface/SearchInterface.ts
- unitTests/ui/MissingTermManagerTest.ts
- unitTests/ui/MissingTermsTest.ts
https://coveord.atlassian.net/browse/JSUI-2545
Log UA when clicking on the term in the breadcrumb
> JSUI-2545 added UA when removing a mustContain word

- sass/MagicBox/MagicBox.scss
- sass/_Omnibox.scss
https://coveord.atlassian.net/browse/JSUI-2555
> JSUI-2555 Fix highlight and Searchbox resize

- src/ui/FormWidgets/TextInput.ts
- unitTests/ui/TextInputTest.ts
https://coveord.atlassian.net/browse/JSUI-2552
> JSUI-2552 Addendum: Don't put required on the TextInput at all when option is false

- src/controllers/FacetQueryController.ts
- unitTests/controllers/FacetQueryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2576
> JSUI-2576 Not adding current facet expression to the aq when additional filter is specified

- src/ui/FacetValueSuggestions/FacetValueSuggestions.ts
- unitTests/ui/FacetValueSuggestionsTest.ts
https://coveord.atlassian.net/browse/JSUI-2578
> Add options to specify categoryField + delimiter for FacetValueSuggestions

- src/Eager.ts
- src/Lazy.ts
- src/ui/OmniboxResultList/OmniboxResultList.ts
- src/ui/QuerySuggestPreview/LazyQuerySuggestPreview.ts
- src/ui/QuerySuggestPreview/QuerySuggestPreview.ts
https://coveord.atlassian.net/browse/JSUI-2569
Move what I added to the omniboxResultList to a new component since I didn't use anything specific from it and we may want to add option preview specific.
> JSUI-2569 new component QuerySuggestPreview

- accessibilityTest/AccessibilityDynamicFacet.ts
- src/controllers/DynamicFacetQueryController.ts
- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/Facet/Facet.ts
- unitTests/controllers/DynamicFacetQueryControllerTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
Realized I needed this because of a bug in my new feature (https://github.com/coveo/search-ui/pull/1165)
https://coveord.atlassian.net/browse/JSUI-2462
> JSUI-2462 Implement isolated queries for the DynamicFacet show more/less

- src/ui/ResultList/ResultList.ts
- src/ui/Templates/TemplateToHtml.ts
https://coveord.atlassian.net/browse/JSUI-2582
Refactor for buildResult and buildResults that were in the resultList
> JSUI-2582 Refactor buildResult(s) in the ResultList

- src/ui/CategoryFacet/CategoryFacet.ts
https://coveord.atlassian.net/browse/JSUI-2587
Referenced on discuss
https://discuss.coveo.com/t/sort-coveocategoryfacet/2301/4?u=jfthibodeau
> JSUI-2587 Correct valueCaption documentation for the CategoryFacet

- src/ui/DynamicFacet/DynamicFacet.ts
because of this story: 
[DynamicFacet] Remove Facet Padding Feature & scroll to top instead
https://coveord.atlassian.net/browse/JSUI-2504
Now the preserveOption is useless and should also be deleted.
> JSUI-2504 Remove preservePosition option

- src/ui/DynamicFacet/DynamicFacet.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2588
> JSUI-2588 Fix JS Error when disabling search and interacting with facet

- src/ui/ResultLayoutSelector/ResultLayoutSelector.ts
https://coveord.atlassian.net/browse/JSUI-2590
> JSUI-2590 ResultLayoutSelector: Add componentOptions to the doc

- src/ui/Templates/TemplateToHtml.ts
https://coveord.atlassian.net/browse/JSUI-2591
> JSUI-2591 Log a warning when a ResultTemplate does not contain a CoveoResultLink component

- src/ui/Omnibox/Omnibox.ts
- strings/strings.json
https://coveord.atlassian.net/browse/JSUI-2597
> JSUI-2597 Always set new SubmitSearch string as the input aria label

- src/ui/Facet/ValueElementRenderer.ts
- unitTests/ui/ValueElementRendererTest.ts
> JSUI-2599 Adding aria-hidden to checkbox input which has style display: none

- sass/_Quickview.scss
https://coveord.atlassian.net/browse/JSUI-2563
> JSUI-2563 Add max width to the quickview icon

- sass/_FacetValues.scss
https://coveord.atlassian.net/browse/JSUI-2600
> JSUI-2600 Lower z-index value for exclude icon

- sass/_ResultFolding.scss
- src/ui/ResultFolding/ResultFolding.ts
- unitTests/ui/ResultFoldingTest.ts
https://coveord.atlassian.net/browse/JSUI-2559
> JSUI-2559 Not able to access `Show Complete Thread` option by using keyboard

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryFacetValuesTree.ts
- unitTests/Test.ts
- unitTests/ui/CategoryFacet/CategoryFacetValuesTreeTest.ts
> Store seen category facet values in memory; generate breadcrumb from seen values

- src/ui/Facet/ValueElementRenderer.ts
- src/ui/FormWidgets/Checkbox.ts
- unitTests/ui/CheckboxTest.ts
- unitTests/ui/ValueElementRendererTest.ts
https://coveord.atlassian.net/browse/JSUI-2599
> JSUI-2599 Add aria label to stop SiteImprove warning

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2604
> JSUI-2604 Add title to the DynamicFacet analytics

- src/ui/SearchInterface/SearchInterface.ts
- src/ui/TimespanFacet/TimespanFacet.ts
- src/utils/ComponentsTypes.ts
- unitTests/utils/ComponentsTypesTest.ts
Issue: Duplicate ID warning logged when using a TimespanFacet
https://coveord.atlassian.net/browse/JSUI-2593
> JSUI-2593 Filter out TimespanFacet from the duplicateFacets

- docs/playground/src/PlaygroundConfiguration.ts
- src/ui/FacetValueSuggestions/FacetValueSuggestions.ts
> DOC-4074 Improve FacetValueSuggestions reference documentation

- src/ui/FacetValueSuggestions/FacetValueSuggestions.ts
https://coveord.atlassian.net/browse/JSUI-1065
> JSUI-1065 Documentation revision - fix typo

- src/ui/Base/Component.ts
> DOC-5711 Fix typos in Component class documentation

- src/ui/Omnibox/Omnibox.ts
- src/ui/SearchButton/SearchButton.ts
- unitTests/ui/OmniboxTest.ts
https://coveord.atlassian.net/browse/JSUI-2606
> JSUI-2606 Reset filters when the user enters a new query

- src/controllers/FacetSearchController.ts
- unitTests/controllers/FacetSearchControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2619
> JSUI-2619 Add search value captions for months

- templates/YouTube/CardYouTubePlaylist.html
https://coveord.atlassian.net/browse/JSUI-2620
> JSUI-2620 Change youtube playlist template link bg color

- src/ui/ResponsiveComponents/ResponsiveRecommendation.ts
https://coveord.atlassian.net/browse/JSUI-2628
> JSUI-2628 ResponsiveRecommendation: Filter facets and remove the clearing of facet search results

- src/magicbox/InputManager.ts
- src/magicbox/MagicBox.ts
- src/magicbox/SuggestionsManager.ts
- src/ui/Base/Component.ts
- src/ui/Omnibox/Omnibox.ts
- src/ui/Querybox/Querybox.ts
- unitTests/magicbox/MagicBoxClearTest.ts
- unitTests/magicbox/SuggestionsManagerTest.ts
- unitTests/ui/QuerySuggestPreviewTest.ts
https://coveord.atlassian.net/browse/JSUI-2631
> JSUI-2631 Refactor root for QuerySuggestPreview, was breaking older versions

- src/ui/DynamicFacetManager/DynamicFacetManager.ts
- unitTests/ui/DynamicFacetManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2637
> JSUI-2637 Still append facets without values to the DynamicFacetManager container

- src/ui/DynamicFacetManager/DynamicFacetManager.ts
- unitTests/ui/DynamicFacet/DynamicFacetRangeTestUtils.ts
- unitTests/ui/DynamicFacetManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2638
> JSUI-2638 Add DynamicFacetRange compatibility for the Manager

- src/ui/Base/ComponentOptions.ts
- src/ui/Base/QueryBuilder.ts
- src/ui/Distance/DistanceResources.ts
- src/ui/ErrorReport/ErrorReport.ts
- src/ui/Facet/Facet.ts
- src/ui/FacetSlider/FacetSlider.ts
- src/ui/FieldSuggestions/FieldSuggestions.ts
- src/ui/Folding/Folding.ts
- src/ui/FollowItem/FollowItem.ts
- src/ui/Logo/Logo.ts
- src/ui/Omnibox/Omnibox.ts
- src/ui/PipelineContext/PipelineContext.ts
- src/ui/PromotedResultsBadge/PromotedResultsBadge.ts
- src/ui/Querybox/Querybox.ts
- src/ui/Quickview/QuickviewDocumentIframe.ts
- src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
- src/ui/ResultsPreferences/ResultsPreferences.ts
- src/ui/SearchAlerts/SearchAlerts.ts
- src/ui/SearchInterface/SearchInterface.ts
- src/ui/Tab/Tab.ts
- src/ui/Text/Text.ts
- unitTests/ui/LogoTest.ts
https://coveord.atlassian.net/browse/JSUI-2636
> Update documentation links to point to https

- src/ui/FacetSlider/FacetSlider.ts
- unitTests/ui/FacetSliderTest.ts
https://coveord.atlassian.net/browse/JSUI-2644
> Change how isEmpty is determined for facet slider

- src/ui/Pager/Pager.ts
- unitTests/ui/PagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2649
> Added handling of numberOfResults per page change

- src/ui/ResponsiveComponents/ResponsiveTabs.ts
https://coveord.atlassian.net/browse/JSUI-2646
> JSUI-2646 Prevent parentnode error by returning appended tab

- src/controllers/DynamicFacetQueryController.ts
- src/rest/Facet/FacetRequest.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts
- unitTests/controllers/DynamicFacetQueryControllerTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTestUtils.ts
- unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts
https://coveord.atlassian.net/browse/JSUI-2650
> JSUI-2650 Update QSM on API response so autoselection is represented in the QSM

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetCommonOptions.ts
- src/ui/DynamicFacet/DynamicFacetRange.ts
- unitTests/ui/DynamicFacet/DynamicFacetRangeTest.ts
https://coveord.atlassian.net/browse/JSUI-2651
> JSUI-2651 Update DynamicFacetRange options documentation

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/Facet/Facet.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/FacetTest.ts
- unitTests/utils/DependsOnManagerTest.ts
> JSUI-2643 Write component agnostic tests for the DependsOnManager & write specific test for each facet type

- src/controllers/DynamicFacetQueryController.ts
- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/Facet/Facet.ts
- src/utils/DependsOnManager.ts
- unitTests/controllers/DynamicFacetQueryControllerTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTestUtils.ts
- unitTests/ui/FacetTest.ts
- unitTests/utils/DependsOnManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2643
> JSUI-2643 Add DependsOn feature for the DynamicFacet

- src/ui/PipelineContext/PipelineContext.ts
> Update & streamline PipelineContext description

- src/magicbox/MagicBox.ts
- src/magicbox/SuggestionsManager.ts
- unitTests/magicbox/SuggestionsManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2661
> JSUI-2661 Clear Keyboard focused element when editing input content

- .travis.yml
- accessibilityTest/AccessibilityDynamicFacet.ts
- accessibilityTest/AccessibilityFacet.ts
- src/ui/DynamicFacet/DynamicFacetRange.ts
This is going on the release
https://coveord.atlassian.net/browse/JSUI-2663
> JSUI-2663 Update doc duplicate & add more delay for facet search accessibility tests

- src/controllers/HistoryController.ts
- src/controllers/QueryController.ts
- src/ui/Analytics/Analytics.ts
- src/ui/Base/Component.ts
- src/ui/SearchInterface/SearchInterface.ts
- unitTests/MockEnvironment.ts
- unitTests/controllers/HistoryControllerTest.ts
- unitTests/ui/RecommendationAnalyticsClientTest.ts
- unitTests/ui/RegisteredNamedMethodsTest.ts
~Gonna add a few UT for that, won't be too long~ they're here
https://coveord.atlassian.net/browse/JSUI-2518
> JSUI-2518Update the SearchInterface Analytics client directly when enabling/disabling UA

- src/magicbox/MagicBox.ts
- src/ui/QuerySuggestPreview/QuerySuggestPreview.ts
https://coveord.atlassian.net/browse/JSUI-2677
> JSUI-2677 Remove LEFT/RIGHT magicbox arrow handlers

- src/rest/Query.ts
- src/ui/Base/QueryBuilder.ts
- unitTests/ui/QueryBuilderTest.ts
> [COM-158] add commerce catalogId to queryBuilder

- src/magicbox/InputManager.ts
https://coveord.atlassian.net/browse/JSUI-2688
This is a hotfix for a client
Again this part of the code doesn't look unit tested, a refactor is coming from @btaillon which I guess will contain some tests.
> JSUI-2688 Remove click handler on the Input Manager

- src/controllers/DynamicCategoryFacetQueryController.ts
- src/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValue.ts
- src/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValueRenderer.ts
- unitTests/Test.ts
- unitTests/ui/CategoryFacet/CategoryFacetTestUtils.ts
- unitTests/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValueRendererTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValueTest.ts
Will add 'values' (management of multiple values) in a future PR, let's not make this too long
https://coveord.atlassian.net/browse/JSUI-2675
> JSUI-2675 Add CategoryFacetValue

- .travis.yml
https://coveord.atlassian.net/browse/JSUI-2717
> JSUI-2717 Remove Veracode integration from the Travis pipeline

- src/rest/SearchEndpoint.ts
> DOC-5366 Clarify SearchEndpoint reference documentation

- src/rest/SearchEvent.ts
- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/Analytics/IAnalyticsFacetState.ts
- src/ui/Analytics/PendingSearchEvent.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetBreadcrumbs.ts
- src/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeader.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts
- unitTests/ui/DynamicFacet/DynamicFacetBreadcrumbsTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts
Look at the AnalyticsActionListMeta.ts file to make sure everything is there.
https://coveord.atlassian.net/browse/JSUI-2721
> JSUI-2721 Refactor DynamicFacets custom analytics data

- src/ui/CategoryFacet/CategoryFacet.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2728
> JSUI-2728 Hide CategoryFacet with base path configured when there are no results

- pages/All.html
- pages/Chatter.html
- pages/Confluence.html
- pages/Dropbox.html
- pages/DynamicsCrm.html
- pages/Email.html
- pages/GoogleDrive.html
- pages/Jira.html
- pages/Lithium.html
- pages/People.html
- pages/Recommendation.html
- pages/Salesforce.html
- pages/SalesforceCase.html
- pages/ServiceNow.html
- pages/SharePoint.html
- pages/YouTube.html
- pages/index.html
https://coveord.atlassian.net/browse/JSUI-2724
> Use DNE in default page

- sass/CategoryFacet/_CategoryFacetValues.scss
- sass/DynamicFacet/_DynamicFacetValues.scss
- sass/mixins/_dynamicFacet.scss
- src/controllers/DynamicCategoryFacetQueryController.ts
- src/controllers/DynamicFacetQueryController.ts
- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryFacetDebug.ts
- src/ui/CategoryFacet/CategoryFacetSearch.ts
- src/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValue.ts
- src/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValues.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueMoreLessButton.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValues.ts
- strings/strings.json
- unitTests/Test.ts
- unitTests/controllers/DynamicCategoryFacetQueryControllerTest.ts
- unitTests/controllers/DynamicFacetQueryControllerTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetTestUtils.ts
- unitTests/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValueTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValuesTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
Don't worry about circular dependencies or the cleanup of the old facet values, this will be done soon.
https://coveord.atlassian.net/browse/JSUI-2704
> JSUI-2704 Add CategoryFacet "Show more" and "Show less" feature

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/Analytics/IAnalyticsFacetState.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts
- unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts
https://coveord.atlassian.net/browse/JSUI-2737
> JSUI-2737 Update analytics for DynamicFacetRange

- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetRangeValueParser.ts
https://coveord.atlassian.net/browse/JSUI-2749
> JSUI-2749 Add options for DynamicFacetRange dateToString in order to be more consistent

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/ResultList/ResultList.ts
> DOC-5417 Clarify enableScrollToTop documentation

- src/magicbox/QueryProcessor.ts
- unitTests/magicbox/QueryProcessorTest.ts
https://coveord.atlassian.net/browse/JSUI-2764
> JSUI-2764 Ensure order of query results in QueryProcessor

- src/controllers/DynamicCategoryFacetQueryController.ts
- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryFacetBreadcrumb.ts
- src/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValue.ts
- src/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValueRenderer.ts
- src/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValues.ts
- src/ui/CategoryFacet/ICategoryFacet.ts
- src/ui/DynamicFacet/IDynamicFacet.ts
- unitTests/controllers/DynamicCategoryFacetQueryControllerTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetTestUtils.ts
- unitTests/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValueRendererTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValueTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValuesTest.ts
https://coveord.atlassian.net/browse/JSUI-2673
> JSUI-2673 Fix Circular dependencies for the CategoryFacet

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/ICategoryFacet.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2708
> Add DynamicFacetManager/CategoryFacet compatibility

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/CategoryFacet/CategoryFacetBreadcrumb.ts
- src/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValue.ts
- src/ui/CategoryFacet/ICategoryFacet.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValueTest.ts
https://coveord.atlassian.net/browse/JSUI-2773
> JSUI-2773 Part 1: Remove legacy CategoryFacet stuff before name change

- accessibilityTest/AccessibilityDynamicHierarchicalFacet.ts
- accessibilityTest/Test.ts
https://coveord.atlassian.net/browse/JSUI-2778
> JSUI-2778 DynamicHierarchicalFacet  Accessibility Tests

- src/controllers/DynamicFacetQueryController.ts
- src/controllers/DynamicFacetRangeQueryController.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/IDynamicFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- unitTests/controllers/DynamicFacetQueryControllerTest.ts
- unitTests/controllers/DynamicFacetRangeQueryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2752
> JSUI-2752 [DynamicFacet] Pass injectionDepth option

- sass/DynamicHierarchicalFacet/_DynamicHierarchicalFacetValues.scss
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueRenderer.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValues.ts
https://coveord.atlassian.net/browse/JSUI-2519
> [DynamicHierarchicalFacet] Add titles and css fix

- src/ui/DynamicFacet/DynamicFacetRange.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetRangeValueParser.ts
- src/ui/DynamicFacet/IDynamicFacetRange.ts
- src/utils/NumberUtils.ts
- unitTests/ui/DynamicFacet/DynamicFacetRangeTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetRangeValueParserTest.ts
https://coveord.atlassian.net/browse/JSUI-2656
> JSUI-2656 Add currency valueFormat and currencySymbol for ranges

- sass/DynamicHierarchicalFacet/_DynamicHierarchicalFacetValues.scss
https://coveord.atlassian.net/browse/JSUI-2519
> JSUI-2519 Have only one level space for DynamicHierarchicalFacet

- src/ui/FacetValueSuggestions/FacetValueSuggestions.ts
https://coveord.atlassian.net/browse/JSUI-2519
> [DynamicHierarchicalFacet] Update doc for FacetValueSuggestions

- accessibilityTest/AccessibilityDynamicHierarchicalFacet.ts
https://coveord.atlassian.net/browse/JSUI-2778
> [JSUI-2778] DynamicHierarchicalFacet accessibilityTests change field to champion_categories

- sass/_SimpleFilter.scss
- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/SimpleFilter/SimpleFilter.ts
- strings/strings.json
- unitTests/ui/SimpleFilterTest.ts
Add a clear button to SimpleFilter
Add analytics event to log the clearing of a SimpleFilter
Add unit tests for clear functionality
Add a loop to test all the previous existing tests with different enableClearButton combinations
https://coveord.atlassian.net/browse/JSUI-2686
> JSUI-2686 Add clear to simple filter

- src/controllers/DynamicHierarchicalFacetQueryController.ts
- src/rest/Facet/FacetSortCriteria.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- src/ui/DynamicHierarchicalFacet/IDynamicHierarchicalFacet.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2787
> JSUI-2787 [DynamicHierarchicalFacet] Implement the sortCriteria option

- sass/_ResponsiveFacets.scss
https://coveord.atlassian.net/browse/JSUI-2790
> JSUI-2790 Add hierarchical values padding

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/IDynamicFacet.ts
- src/ui/DynamicFacetManager/DynamicFacetManager.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- unitTests/ui/DynamicFacetManagerTest.ts
UT checks it correctly, hidden dependantFacets were not taken into consideration and were expanded. using isCurrentlyDisplayed method will consider facets hidden by depends on
https://coveord.atlassian.net/browse/JSUI-2789
> JSUI-2789 Use isCurrentlyDisplayed() instead of hasDisplayedValues, will work with dependsOn

- pages/Chatter.html
- pages/Confluence.html
- pages/Dropbox.html
- pages/Email.html
- pages/GoogleDrive.html
- pages/Jira.html
- pages/SharePoint.html
- sass/DynamicFacet/_DynamicFacetHeader.scss
https://coveord.atlassian.net/browse/JSUI-2793
> JSUI-2793 Make DynamicFacet titles capitalized and add localized strings where available

- src/ui/DynamicFacet/DynamicFacet.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts
- unitTests/utils/DependsOnManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2797
> JSUI-2797 Fix toggleDependentFacet for DynamicFacet and add UTs

- sass/DynamicHierarchicalFacet/_DynamicHierarchicalFacetValues.scss
https://coveord.atlassian.net/browse/JSUI-2804
> JSUI-2804 Reduce level space

- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValues.ts
- src/ui/DynamicHierarchicalFacet/IDynamicHierarchicalFacet.ts
- strings/strings.json
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValuesTest.ts
UT coming soon!
https://coveord.atlassian.net/browse/JSUI-2807
> JSUI-2807 Add option for the "All Categories" label

- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2810
> JSUI-2810 Change method called by dependsOnReset to reset and add UT

- src/ui/StarRating/StarRating.ts
https://coveord.atlassian.net/browse/JSUI-2812
> Remove require:false from StarRating numberOfRatingsField option

- src/ui/PromotedResultsBadge/PromotedResultsBadge.ts
https://coveord.atlassian.net/browse/JSUI-2774
> JSUI-2774 Update PromotedResultsBadge documentation

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacetManager/DynamicFacetManager.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicFacetManagerTest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2822
> JSUI-2822 Replace querySuccess with deferredQuerySuccess in DynamicFacets

- pages/Chatter.html
- pages/Confluence.html
- pages/Dropbox.html
- pages/DynamicsCrm.html
- pages/Email.html
- pages/GoogleDrive.html
- pages/Lithium.html
- pages/Salesforce.html
- pages/SalesforceCase.html
- pages/ServiceNow.html
- pages/SharePoint.html
- pages/YouTube.html
https://coveord.atlassian.net/browse/JSUI-2823
> JSUI-2823 Put unique Ids for repetitive DynamicFacets in pages

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetRange.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
Will make it cleaner in the interface editor
https://coveord.atlassian.net/browse/JSUI-2502
> JSUI-2502 Tweak DNE components options

- src/ui/DynamicFacet/DynamicFacetRange.ts
> DOC-6504 DynamicFacetRange documentation revision

- src/ui/Facet/Facet.ts
https://coveord.atlassian.net/browse/JSUI-2825
> Changed `FacetSearch`'s label

- src/ui/DynamicFacet/DynamicFacetRange.ts
> Add link to the value formats enum for the DynamicFacetRange

- src/rest/Query.ts
- src/ui/DynamicFacetManager/DynamicFacetManager.ts
- unitTests/ui/DynamicFacetManagerTest.ts
Sorry for the UT refactor but there a easier to read now :D 
https://coveord.atlassian.net/browse/JSUI-2806
> JSUI-2806 Refactor manager collapsing feature to work with freezeFacetOrder

- src/controllers/DynamicFacetQueryController.ts
- src/controllers/DynamicFacetRangeQueryController.ts
- src/controllers/DynamicHierarchicalFacetQueryController.ts
- src/rest/Facet/FacetRequest.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/DynamicFacetBreadcrumbs.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueRenderer.ts
- src/ui/DynamicFacet/IDynamicFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValue.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueRenderer.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValues.ts
- src/ui/DynamicHierarchicalFacet/IDynamicHierarchicalFacet.ts
- unitTests/controllers/DynamicFacetQueryControllerTest.ts
- unitTests/controllers/DynamicFacetRangeQueryControllerTest.ts
- unitTests/controllers/DynamicHierarchicalFacetQueryControllerTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetBreadcrumbsTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTestUtils.ts
- unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueRendererTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTestUtils.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValuesTest.ts
SEARCHAPI-4233 will be required for it to work
https://coveord.atlassian.net/browse/JSUI-2832
> JSUI-2832 Move autoselect prevention to the facet level

- sass/_StarRating.scss
- src/ui/StarRating/StarRating.ts
- strings/strings.json
- unitTests/ui/StarRatingTest.ts
https://coveord.atlassian.net/browse/JSUI-2814
> JSUI-2814 Made the `StarRating` component accessible

- src/ui/CategoryFacet/CategoryValue.ts
- unitTests/ui/CategoryFacet/CategoryValueTest.ts
https://coveord.atlassian.net/browse/JSUI-2827
> JSUI-2827 Fixed plural label for `CategoryValue`

- src/ui/CategoryFacet/CategoryFacetSearch.ts
- unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts
https://coveord.atlassian.net/browse/JSUI-2828
> JSUI-2828 Changed role and label of `CategoryFacetSearch`

- src/controllers/FacetQueryController.ts
- unitTests/controllers/FacetQueryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2830
> JSUI-2830 Make allowed values work with regex characters

- src/utils/CookieUtils.ts
https://coveord.atlassian.net/browse/JSUI-2839
> JSUI-2839 Add SameSite=Lax when setting Cookie

- src/ui/Querybox/Querybox.ts
> DOC-6420 Update partial match documentation

- src/ui/SearchInterface/SearchInterface.ts
- src/ui/Tab/Tab.ts
> DOC-6178 Clarify enableDuplicateFiltering documentation

- src/rest/Plan.ts
- src/rest/SearchEndpoint.ts
- src/rest/SearchEndpointInterface.ts
- src/rest/SearchEndpointWithDefaultCallOptions.ts
- unitTests/rest/SearchEndpointTest.ts
https://coveord.atlassian.net/browse/JSUI-2847
I probably need more help documenting this correctly @fbeaudoincoveo. If you need more information about the projet, ask away!
> JSUI-2847 Create /plan endpoint

- src/rest/Facet/FacetRequest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTestUtils.ts
Oups forgot to push
https://coveord.atlassian.net/browse/JSUI-2736
> JSUI-2736 PR fixes for previous PR

- src/utils/AccessibleModal.ts
- unitTests/utils/AccessibleModalTest.ts
https://coveord.atlassian.net/browse/JSUI-2866
Added a role to the close button of `Quickview` and `YoutubeThumbnail`.
> JSUI-2866 Added `button` role to `AccessibleModal`'s close button

- src/ui/DynamicFacetManager/DynamicFacetManager.ts
https://coveord.atlassian.net/browse/JSUI-1065
> JSUI-1065 Update broken link in DynamicFacetManager

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
https://coveord.atlassian.net/browse/JSUI-1065
> JSUI-1065 Correction: filterFacetCount is `false` if folded results are requested; `true` otherwise.

- sass/_SimpleFilter.scss
https://coveord.atlassian.net/browse/JSUI-2871
> JSUI-2871 Use padding instead of margin for eraser in SimpleFilter

- sass/DynamicHierarchicalFacet/_DynamicHierarchicalFacetValues.scss
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValues.ts
https://coveord.atlassian.net/browse/JSUI-2875
> JSUI-2875 Add back arrow to HierarchicalFacet's ALL buttton

- docs/playground/src/PlaygroundConfiguration.ts
https://coveord.atlassian.net/browse/JSUI-2877
> JSUI-2877 Add SortDropdown to the playground

- src/rest/SearchEndpoint.ts
> Fix link in SearchEndpoint class documentation

- sass/_SimpleFilter.scss
https://coveord.atlassian.net/browse/JSUI-2871
> JSUI-2871 Add flex's justify-content property on the simplefilter eraser

- sass/_SimpleFilter.scss
https://coveord.atlassian.net/browse/JSUI-2871
> JSUI-2871 Even bigger padding for the SimpleFilter erase/clear

- src/ui/FormWidgets/Dropdown.ts
- src/ui/SortDropdown/SortDropdown.ts
- unitTests/ui/DropdownTest.ts
- unitTests/ui/SortDropdownTest.ts
https://coveord.atlassian.net/browse/JSUI-2884
The previous solution (setting hidden on the option) did not work for IE11
> JSUI-2884 Rebuild dropdown options intead of hidding them

- src/models/Model.ts
- src/utils/HashUtils.ts
- unitTests/utils/HashUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-2896
> JSUI-2896 Check if encoded bracket is present before comparing indicies

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/IDynamicFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- src/ui/DynamicHierarchicalFacet/IDynamicHierarchicalFacet.ts
- src/ui/Facet/Facet.ts
- src/utils/DependsOnManager.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts
- unitTests/ui/FacetTest.ts
- unitTests/utils/DependsOnManagerTest.ts
I will have to document the option itself
https://coveord.atlassian.net/browse/JSUI-2902
> JSUI-2902 Add DependsOnCondition option and refactor the internals of the DependsOnManager

- src/ui/FieldValue/FieldValue.ts
- src/ui/Templates/CoreHelpers.ts
- src/utils/NumberUtils.ts
- templates/YouTube/CardYouTubePlaylistItem.html
- templates/YouTube/CardYouTubeVideo.html
- templates/YouTube/YouTubeVideo.html
- unitTests/ui/CoreHelpersTest.ts
https://coveord.atlassian.net/browse/JSUI-2909
> JSUI-2909 Support data-helper="number" & data-helper-options-format="n0"

- src/ui/Omnibox/Omnibox.ts
- strings/strings.json
https://coveord.atlassian.net/browse/JSUI-2918
> JSUI-2918 Changed the label for `Searchbox`

- src/ui/FacetValueSuggestions/FacetValueSuggestions.ts
I also have a PR open for changes in [docs.coveo.com](https://bitbucket.org/coveord/doc_jekyll-public-site/pull-requests/3450/doc-6798/diff).
> DOC-6798-Facet-Value-Suggestions-Fileld-Should-Be-Facetable

- docs/playground/src/PlaygroundConfiguration.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
> DOC-6968 Small fixes in DynamicHierarchicalFacet documentation

- src/ui/Facet/ValueElementRenderer.ts
https://coveord.atlassian.net/browse/JSUI-2926
> JSUI-2926 Fixed localization for `ValueElementRenderer`

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/SearchInterface/SearchInterface.ts
- unitTests/ui/StandaloneSearchInterfaceTest.ts
https://coveord.atlassian.net/browse/JSUI-2915
> JSUI-2915 Send the query as part of the redirection UA

- .travis.yml
- accessibilityTest/AccessibilityCategoryFacet.ts
- accessibilityTest/Test.ts
- sass/_CategoryFacetSearch.scss
- sass/_FacetValues.scss
https://coveord.atlassian.net/browse/JSUI-2930
> JSUI-2930 Improved contrast for `CategoryFacetSearch`

- src/utils/ComponentsTypes.ts
- src/utils/DependsOnManager.ts
- unitTests/ui/CategoryFacet/CategoryFacetTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts
- unitTests/ui/FacetTest.ts
- unitTests/utils/DependsOnManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2902
> JSUI-2902 Setup depends on after components initlization event is triggered 

- src/ui/CategoryFacet/CategoryFacetSearch.ts
- unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts
https://coveord.atlassian.net/browse/JSUI-2953
> JSUI-2953 Improved localization for `CategoryFacetSearch`'s results

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicFacet/IDynamicFacet.ts
- src/ui/Facet/Facet.ts
- src/ui/FieldValue/FieldValue.ts
- src/ui/FieldValue/IFieldValueCompatibleFacet.ts
- unitTests/ui/FieldValueTest.ts
FieldValue file went from 13006 lines down to 550 lines
https://coveord.atlassian.net/browse/JSUI-2964
> JSUI-2964 Remove DynamicFacet & Facet Dependencies in FieldValue

- src/ui/Omnibox/Omnibox.ts
> DOC-7259 Fix broken link

- src/ui/FacetsMobileMode/FacetsMobileMode.ts
https://coveord.atlassian.net/browse/JSUI-2975
> JSUI-2975 Make FacetsMobileMode work in eager mode

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts
Also fixed a bug with expanding
https://coveord.atlassian.net/browse/JSUI-2978
> JSUI-2978 DynamicHierarchicalFacet search should be disabled by default

- src/ui/FormWidgets/TextInput.ts
- unitTests/ui/TextInputTest.ts
https://coveord.atlassian.net/browse/JSUI-2994
> JSUI-2994 Add autocomplete="off" to TextInput (used for DNE search)

- src/ui/ResultLink/ResultLink.ts
- unitTests/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-2969
> JSUI-2969 Blacklist javascript protocol for ResultLink 

- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/Facet/Facet.ts
- src/ui/FieldValue/FieldValue.ts
- src/ui/FieldValue/IFieldValueCompatibleFacet.ts
- unitTests/ui/DynamicFacet/DynamicFacetTest.ts
- unitTests/ui/FacetTest.ts
- unitTests/ui/FieldValueTest.ts
https://coveord.atlassian.net/browse/JSUI-3000
> JSUI-3000 Allowed `FieldValue` to use `Facet` and `DynamicFacet`'s captions.

- src/rest/AnalyticsEndpoint.ts
https://coveord.atlassian.net/browse/JSUI-3002
> Change default analytics token duration to 1 year

- src/ui/DynamicFacet/DynamicFacetBreadcrumbs.ts
- src/utils/Dom.ts
- unitTests/ui/DynamicFacet/DynamicFacetBreadcrumbsTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetTestUtils.ts
https://coveord.atlassian.net/browse/JSUI-3004
> JSUI-3004 Escape dynamic facet value breadcrumb to prevent XSS

- sass/_CategoryFacetSearch.scss
https://coveord.atlassian.net/browse/JSUI-3016
> Add permanent margin on CategoryFacetSearch

- src/ui/Facet/FacetSearchElement.ts
- unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts
https://coveord.atlassian.net/browse/JSUI-3017
> Handle ESC key when focusing on the CategoryFacetSearch results

- src/ui/CategoryFacet/CategoryFacet.ts
[DOC-7531](https://coveord.atlassian.net/browse/DOC-7531)
> Review displaySearchOnTop/displaySearchButton docs

- src/controllers/FacetSearchController.ts
- src/controllers/HierarchicalFacetSearchController.ts
- src/ui/DynamicFacetSearch/DynamicFacetSearch.ts
- src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearch.ts
- unitTests/Test.ts
- unitTests/controllers/FacetSearchControllerTest.ts
- unitTests/controllers/HierarchicalFacetSearchControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-3020
> JSUI-3020 Only use ignorePaths and ignoreValues for active value(s)/path in FacetSearch

- src/controllers/HistoryController.ts
- unitTests/controllers/HistoryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-3027
> JSUI-3027 Parse hash values to string before comparing

- src/ui/CardActionBar/CardActionBar.ts
- unitTests/ui/CardActionBarTest.ts
https://coveord.atlassian.net/browse/JSUI-3031
> JSUI-3031 Show/Hide CardActionBar when focusing in and out of it

- src/rest/EndpointCaller.ts
- unitTests/rest/EndpointCallerTest.ts
- unitTests/rest/SearchEndpointTest.ts
- unitTests/ui/AnalyticsEndpointTest.ts
https://coveord.atlassian.net/browse/JSUI-3034
> JSUI-3034 Remove the quotes around UTF-8 for charset

- deploy.beta.js
https://coveord.atlassian.net/browse/JSUI-3038
> JSUI-3038 Update NPM username with env variable

- src/ui/Base/Initialization.ts
https://coveord.atlassian.net/browse/JSUI-3036
> JSUI-3036 Document registerComponentFields correctly

- sass/_SmartSnippet.scss
- src/ui/SmartSnippet/HeightLimiter.ts
- src/ui/SmartSnippet/UserFeedbackBanner.ts
https://coveord.atlassian.net/browse/JSUI-3033
> JSUI-3033 Improved accessibility for `UserFeedbackBanner` and `HeightLimiter`

- sass/_AttachShadowPolyfill.scss
- sass/_SmartSnippet.scss
- src/misc/AttachShadowPolyfill.ts
- src/ui/SmartSnippet/HeightLimiter.ts
- src/ui/SmartSnippet/SmartSnippet.ts
- src/ui/SmartSnippet/UserFeedbackBanner.ts
- strings/strings.json
- unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3021
> JSUI-3021 Made `SmartSnippet` compatible with IE11

- src/rest/Highlight.ts
- src/ui/Templates/CoreHelpers.ts
- src/utils/CurrencyUtils.ts
> [DOC-7620] Add missing links in ICoreHelpers documentation

- sass/_SmartSnippet.scss
- src/ui/SmartSnippet/UserFeedbackBanner.ts
https://coveord.atlassian.net/browse/JSUI-3044
> JSUI-3044 Fixed SmartSnippet's appearance for Chrome

- src/ui/Quickview/Quickview.ts
- src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdownContent.ts
https://coveord.atlassian.net/browse/JSUI-3054
> JSUI-3054 Remove quickview listeners & add Dropdown custom listeners

- src/ui/Triggers/Triggers.ts
- unitTests/ui/TriggersTest.ts
https://coveord.atlassian.net/browse/JSUI-3055
> JSUI-3055 Escape content returned by #notify trigger

- CODEOWNERS
https://coveord.atlassian.net/browse/JSUI-2958
> JSUI-2958 Update codeowners

- .travis.yml
- karma.accessibility.test.conf.js
- karma.unit.test.conf.js
- package.json
- src/ui/Base/CoveoUnderscore.ts
- unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts
- unitTests/ui/QuerySummaryTest.ts
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-3019
This PR reduces the security audit to the following:
| high | Missing Origin Validation |
| --- | --- |
| Package | webpack-dev-server |
| Patched in | \>=2.11.4 \<3.0.0 \|\| \>=3.1.11 |
| Dependency of | webpack-dev-server |
| Path | webpack-dev-server |
| More info | https://www.npmjs.com/advisories/725 |
| moderate | XSS via Angular Expression |
| --- | --- |
| Package | ag-grid |
| Patched in | No patch available |
| Dependency of | @types/ag-grid |
| Path | @types/ag-grid \> ag-grid |
| More info | https://www.npmjs.com/advisories/327 |
> JSUI-3019 Updated dependencies to fix vulnerabilities

- src/ui/DynamicFacet/DynamicFacetRange.ts
Woups!
https://coveord.atlassian.net/browse/JSUI-3065
> JSUI-3065 Make ranges option not required on DynamicFacetRange component

- sass/_Breadcrumb.scss
- sass/_ResultList.scss
- src/ui/Breadcrumb/Breadcrumb.ts
- src/ui/Facet/BreadcrumbValueElement.ts
- src/ui/ResultList/ResultList.ts
https://coveord.atlassian.net/browse/JSUI-3078
> JSUI-3078 Manage keyboard focus in facet breadcrumbs

- src/ui/Facet/ValueElementRenderer.ts
- src/utils/SVGDom.ts
- unitTests/ui/ValueElementRendererTest.ts
https://coveord.atlassian.net/browse/JSUI-3074
> Set aria-hidden on exclude icon

- src/ui/Facet/FacetSettings.ts
- src/utils/AccessibleButton.ts
- unitTests/ui/FacetSettingsTest.ts
- unitTests/utils/AccessibleButtonTest.ts
https://coveord.atlassian.net/browse/JSUI-3071
> JSUI-3071 Made buttons in `FacetSettings` toggleable

- sass/_FacetFooter.scss
https://coveord.atlassian.net/browse/JSUI-3069
IE11 (white on black):
Firefox (white on black):
IE11 (black on white):
Firefox (black on white):
> JSUI-3069 Improved contrast for facet expand/collapse on high contrast mode

- accessibilityTest/AccessibilityDynamicHierarchicalFacetSearch.ts
- sass/_Combobox.scss
- src/controllers/FacetSearchController.ts
- src/controllers/HierarchicalFacetSearchController.ts
- src/rest/Facet/FacetSearchResponse.ts
- src/ui/Combobox/Combobox.ts
- src/ui/Combobox/ComboboxInput.ts
- src/ui/Combobox/ComboboxValues.ts
- src/ui/Combobox/ICombobox.ts
- src/ui/DynamicFacetSearch/DynamicFacetSearch.ts
- src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearch.ts
- src/utils/KeyboardUtils.ts
- unitTests/controllers/FacetSearchControllerTest.ts
- unitTests/controllers/HierarchicalFacetSearchControllerTest.ts
- unitTests/ui/Combobox/ComboboxInputTest.ts
- unitTests/ui/Combobox/ComboboxTest.ts
- unitTests/ui/Combobox/ComboboxValuesTest.ts
Both for DynamicFacet and DynamicHierarchicalFacet
Unit tests still on the way! 😄 
https://coveord.atlassian.net/browse/JSUI-3092
> JSUI-3092 Add Scrollbar on Facet Search Results

- src/ui/FieldValue/FieldValue.ts
https://coveord.atlassian.net/browse/JSUI-3089
> JSUI-3089 Remove `aria-label` from field values

- package.json
- sass/DynamicHierarchicalFacet/_DynamicHierarchicalFacetValues.scss
- src/rest/Facet/FacetResponse.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValue.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueRenderer.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValues.ts
- src/ui/DynamicHierarchicalFacet/IDynamicHierarchicalFacet.ts
- src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearch.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTestUtils.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueRendererTest.ts
https://coveord.atlassian.net/browse/JSUI-2907
> JSUI-2907 [DynamicHierarchicalFacet] Should display if a value has children

- src/ui/CategoryFacet/CategoryFacetSearch.ts
- src/ui/CategoryFacet/CategoryValue.ts
- src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValue.ts
- src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearchValueRenderer.ts
- src/ui/Facet/ValueElementRenderer.ts
- strings/strings.json
- unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueTest.ts
- unitTests/ui/DynamicHierarchicalFacetSearchValueRendererTest.ts
- unitTests/ui/ValueElementRendererTest.ts
Also modified the unitTest related to the changes. 
Removed tests that are not relevant anymore.
https://coveord.atlassian.net/browse/JSUI-3057
> JSUI-3057 Modified the  "Select" and "Exclude" strings for the "aria-label" attribut of facets

- src/ui/ResultList/ResultList.ts
- src/ui/Sort/Sort.ts
- unitTests/ui/SortTest.ts
https://coveord.atlassian.net/browse/JSUI-3056
> JSUI-3056 Link `Sort` component to `ResultList` with `aria-controls`

- src/ui/FieldImage/ImageFieldValue.ts
> DOC-7913 Fix links in ImageFieldValue documentation

- strings/strings.json
- unitTests/ui/BreadcrumbValuesListTest.ts
- unitTests/ui/CategoryFacet/CategoryFacetBreadcrumbTest.ts
- unitTests/ui/DynamicFacet/DynamicFacetBreadcrumbsTest.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetBreadcrumbTest.ts
- unitTests/ui/ResultsFiltersPreferencesTest.ts
https://coveord.atlassian.net/browse/JSUI-3101
> JSUI-3101 Modified the breadcrumb aria-label values to match the facet values labels 

- accessibilityTest/AccessibilitySort.ts
https://coveord.atlassian.net/browse/JSUI-3056
> JSUI-3056 Add result list component to sort accessibility tests

- package.json
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-3102
> JSUI-3102 Update npm-cli-login package

- src/ui/Combobox/ComboboxValues.ts
- src/ui/Combobox/ICombobox.ts
- src/ui/DynamicFacetSearch/DynamicFacetSearch.ts
- src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearch.ts
- unitTests/ui/Combobox/ComboboxValuesTest.ts
https://coveord.atlassian.net/browse/JSUI-2979
> JSUI-2979 Highlighting part of the results that matches user's input

- src/ui/Combobox/ComboboxInput.ts
- unitTests/ui/Combobox/ComboboxInputTest.ts
https://coveord.atlassian.net/browse/JSUI-3105
> JSUI-3105 Prevent focusout for IE11 's scrollbar

- sass/DynamicHierarchicalFacet/_DynamicHierarchicalFacetValues.scss
https://coveord.atlassian.net/browse/JSUI-3103
> JSUI-3103 Fix IE11 left arrow in DynamicHierarchicalFacet

- src/controllers/FacetSearchController.ts
- src/controllers/HierarchicalFacetSearchController.ts
- src/ui/DynamicFacetSearch/DynamicFacetSearch.ts
- src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearch.ts
- unitTests/controllers/FacetSearchControllerTest.ts
- unitTests/controllers/HierarchicalFacetSearchControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-3104
> JSUI-3104 Change numberOfValues for facet searches

- src/ui/Combobox/ComboboxValues.ts
- src/ui/Combobox/ICombobox.ts
- src/ui/DynamicFacetSearch/DynamicFacetSearch.ts
- src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearch.ts
- unitTests/ui/Combobox/ComboboxTest.ts
https://coveord.atlassian.net/browse/JSUI-3109
> JSUI-3109 Set static dropdown height of 250 fr facet search

- src/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderButton.ts
- unitTests/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderButtonTest.ts
https://coveord.atlassian.net/browse/JSUI-3035
> JSUI-3035 Fixed the focus state for the `DynamicFacetHeader` collapse button

- package.json
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-3053
You can now add the following to your `.vscode/settings.json`:
```json
"[typescript]": {
"editor.formatOnSave": true,
"editor.defaultFormatter": "esbenp.prettier-vscode"
}
```
> JSUI-3053 Updated prettier

- accessibilityTest/AccessibilitySmartSnippetSuggestions.ts
- accessibilityTest/Test.ts
- sass/_SmartSnippetSuggestions.scss
- src/Eager.ts
- src/Lazy.ts
- src/misc/AttachShadowPolyfill.ts
- src/rest/QuestionAnswerResponse.ts
- src/ui/SmartSnippet/LazySmartSnippetSuggestions.ts
- src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts
- src/ui/SmartSnippet/SmartSnippetSuggestions.ts
- strings/strings.json
- unitTests/Test.ts
- unitTests/ui/SmartSnippetSuggestionsTest.ts
This PR aims to add the new `SmartSnippetSuggestions` component.
Everything up until e534e67 has already been reviewed.
Unit tests incoming.
> JSUI-3052 Added SmartSnippetSuggestions component

- src/ui/ResultLink/ResultLink.ts
- unitTests/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-3126
> Fix issue with highlights appearing in title

- sass/_FacetValues.scss
https://coveord.atlassian.net/browse/JSUI-3135
> JSUI-3135 Add flex-shrink: 0; to facet value checkbox

- sass/_ResponsiveFacets.scss
https://coveord.atlassian.net/browse/JSUI-3149
> JSUI-3149 Remove facet title vertical padding inside responsive move

- src/ui/Querybox/Querybox.ts
> [DOC-8387] Add note about search-as-you-type and potential QPM surge

- src/ui/SearchInterface/SearchInterface.ts
> [DOC-8390] Add warning about setting enableHistory to true in C4SF

- .deployment.config
- Jenkinsfile
- build/deployment-pipeline.deploy.js
- build/npm.deploy.js
- build/npm.utilities.js
- build/tag.utilities.js
- gulpTasks/injectTag.js
- invalidate.cloudfront.js
- package.json
- yarn.lock
This PR adds support for the prod steps, where
1. The beta package is marked as latest.
2. The files are uploaded to s3 to be served by the CDN.
> Support npm package promotion, and cdn upload

- sass/_SmartSnippetSuggestions.scss
- src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts
- unitTests/ui/SmartSnippetSuggestionsTest.ts
https://coveord.atlassian.net/browse/JSUI-3120
> JSUI-3102 Added animation to `SmartSnippetCollapsibleSuggestion`

- src/ui/ExportToExcel/ExportToExcel.ts
- unitTests/ui/ExportToExcelTest.ts
https://coveord.atlassian.net/browse/JSUI-3184
> JSUI-3184 Fixed `ExportToExcel` download for IE11

- docs/playground/src/Playground.ts
- docs/theme/layouts/default.hbs
> DOC-8613 Fix playground

- src/ui/ResultList/ResultList.ts
- unitTests/ui/ResultListTest.ts
https://coveord.atlassian.net/browse/JSUI-3190
The scroll to top is a bit confusing, updated the option doc & tests to be more clear.
> JSUI-3190 Only scroll ResultList to top "once" when the page changes

- .github/workflows/updateOrCreateBranch.yml
- build/release-version.js
Miscellaneous tweaks and fixes to make the script work correctly.
https://coveord.atlassian.net/browse/JSUI-3202
> JSUI-3202 Fix release version logic

- src/ui/FacetSlider/FacetSlider.ts
Due to this PR here: https://github.com/coveo/search-ui/pull/1700
Basically, @samisayegh , you were right ;) 
And I merged that too quickly last week for the release, before addressing the comments.
https://coveord.atlassian.net/browse/JSUI-3206
> Fix issues with facet slider initial setup from query results

- src/ui/CommerceQuery/CommerceQuery.ts
- unitTests/Simulate.ts
- unitTests/ui/CommerceQueryTest.ts
https://coveord.atlassian.net/browse/JSUI-3218
> Added support for buildingQuerySuggest to CommerceQuery

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/Base/RegisteredNamedMethods.ts
This PR is a direct clone of [Tom's submission](https://github.com/coveo/search-ui/pull/1723) to have the changes run on CI, and ensure the changes are associated with a jira.
> JSUI-3224 Improve analytics log function types

- src/ui/AnalyticsSuggestions/AnalyticsSuggestions.ts
Added a link to the `topQueries` call following this discussion https://coveord.atlassian.net/wiki/spaces/PRODUCT/pages/781385736/How+can+topQueries+be+removed?focusedCommentId=2322203108#comment-2322203108
> [DOC-9057] added link to the topQueries call

- src/ui/Analytics/AnalyticsInformation.ts
- unitTests/ui/AnalyticsInformationTest.ts
https://coveord.atlassian.net/browse/SPAAS-716
> SPAAS-716 Prevent interacting with the __coveo.analytics.history cookie to avoid browser warning

- src/ui/SmartSnippet/SmartSnippet.ts
- src/ui/SmartSnippet/SmartSnippetSuggestions.ts
https://coveord.atlassian.net/browse/JSUI-3230
> Documentation smart snippet

- src/ui/ErrorReport/ErrorReport.ts
- strings/strings.json
- unitTests/ui/ErrorReportTest.ts
https://coveord.atlassian.net/browse/JSUI-3235
> Handle OrganizationIsPausedException error message

- strings/strings.json
https://coveord.atlassian.net/browse/JSUI-3244
> add precision on inactivity

- src/ui/ErrorReport/ErrorReport.ts
- strings/strings.json
- unitTests/ui/ErrorReportTest.ts
Again....
Should be the last time :famouslastwords:
https://coveord.atlassian.net/browse/JSUI-3246
> change wording for paused organization

- src/ui/SmartSnippet/SmartSnippet.ts
- unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3238
More info in JIRA.
> Added custom field & href template to SmartSnippet

- src/ui/Breadcrumb/Breadcrumb.ts
https://coveord.atlassian.net/browse/JSUI-3255
> JSUI-3255 Removed redundant labels on clear filters button

- src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearchValueRenderer.ts
- strings/strings.json
- unitTests/ui/DynamicHierarchicalFacetSearchValueRendererTest.ts
https://coveord.atlassian.net/browse/JSUI-3256
> JSUI-3256 Made hierarchical facet search root localization fully changeable

- src/rest/AccessToken.ts
- src/rest/SearchEndpoint.ts
- src/rest/SearchEndpointInterface.ts
- src/rest/SearchEndpointWithDefaultCallOptions.ts
- src/ui/AuthenticationProvider/AuthenticationProvider.ts
- unitTests/ui/AuthenticationProviderTest.ts
https://coveord.atlassian.net/browse/JSUI-3260
> JSUI-3260 exchange SAML token in url for access token

- src/ui/AuthenticationProvider/AuthenticationProvider.ts
- unitTests/MockEnvironment.ts
- unitTests/ui/AuthenticationProviderTest.ts
https://coveord.atlassian.net/browse/JSUI-3267
> JSUI-3267 Prevent multiple CoveoAuthProvider instances from shaking hands at the same time

- src/ui/AuthenticationProvider/AuthenticationProvider.ts
- unitTests/MockEnvironment.ts
- unitTests/ui/AuthenticationProviderTest.ts
https://coveord.atlassian.net/browse/JSUI-3266
> JSUI-3266 Remove handshakeToken from url after exchange

- src/ui/SmartSnippet/SmartSnippet.ts
- unitTests/ui/SmartSnippetTest.ts
When the returned result is not a top level result, we need to try and find it in either `childResults` or `attachments` section of the result set (folded results).
Also reset `lastRenderedResult` to null when not found, otherwise you can end up with a scenario where: 
* Query 1 does not find any associated result, so no result link is present.
* After that, query 2 finds an associated result, and a result link is correctly added
* Re-execute query 1: Net result is that you see the incorrect result link (query 2) being associated with query 1
https://coveord.atlassian.net/browse/JSUI-3270
> fix smart snippet result resolution with folding

- src/ui/Analytics/AnalyticsActionListMeta.ts
- src/ui/ResultLink/ResultLink.ts
- src/ui/ResultLink/ResultLinkOptions.ts
- src/ui/SmartSnippet/SmartSnippet.ts
- src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts
- unitTests/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-3282
Demo: https://ypc9n.csb.app/
> JSUI-3282 Added specific documentOpen analytics for SmartSnippet and SmartSnippetSuggestions

- src/ui/Analytics/Analytics.ts
- unitTests/Simulate.ts
- unitTests/ui/AnalyticsTest.ts
- unitTests/ui/InitializationTest.ts
https://coveord.atlassian.net/browse/JSUI-3293
> support doNotTrack navigator property for analytics

- src/rest/AnalyticsEndpoint.ts
- unitTests/ui/AnalyticsEndpointTest.ts
https://coveord.atlassian.net/browse/JSUI-3294
> change default endpoint UA

- package.json
- pages/index.html
- src/ui/MissingTerm/MissingTerms.ts
- unitTests/ui/MissingTermsTest.ts
https://coveord.atlassian.net/browse/JSUI-3327
https://discuss.coveo.com/t/support-00074462-coveomissingterms-and-folding-component-issue/6913/5
> JSUI-3327 MissingTerms should respect related results (folding)

- src/ui/FieldValue/FieldValue.ts
- unitTests/ui/FieldValueTest.ts
The most famous type of JavaScript bug since 1985.
https://coveord.atlassian.net/browse/JSUI-3334
> fix display falsy value for field value component

- src/controllers/QueryController.ts
https://coveord.atlassian.net/browse/JSUI-3336
> missing facets and lq in query hash

- src/ui/SmartSnippet/ExplanationModal.ts
- unitTests/ui/ExplanationModalTest.ts
- unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3341
> JSUI-3341 Fixed `ExplanationModal` not opening

- src/ui/DidYouMean/DidYouMean.ts
- unitTests/ui/DidYouMeanTest.ts
https://coveord.atlassian.net/browse/JSUI-3343
> JSUI-3343 Add DidYouMean check to prevent multiple retries after receiving no results

- src/ui/Folding/Folding.ts
- unitTests/ui/FoldingTest.ts
https://coveord.atlassian.net/browse/JSUI-3353
Context https://discuss.coveo.com/t/folding-show-more-query-including-facet-in-aq/7206/11
> JSUI-3353 Remove facets, categoryFacets & facetOptions from folding "show more" request

- src/controllers/QueryController.ts
- src/rest/SearchEndpoint.ts
- src/rest/SearchEndpointInterface.ts
- src/ui/Analytics/Analytics.ts
- src/ui/Analytics/AnalyticsClient.ts
- src/ui/Analytics/AnalyticsInformation.ts
- src/ui/Analytics/LiveAnalyticsClient.ts
- src/ui/Analytics/MultiAnalyticsClient.ts
- src/ui/Analytics/NoopAnalyticsClient.ts
- unitTests/controllers/QueryControllerTest.ts
- unitTests/rest/SearchEndpointTest.ts
https://coveord.atlassian.net/browse/JSUI-3359
> add parameters to analytics payload for search API

- .deployment.config.json
https://coveord.atlassian.net/browse/JSUI-3363
I don't have time to test it yet, but I based this off [our doc](https://coveord.atlassian.net/wiki/spaces/CM/pages/2892824652/Snyk+Code+Certifier) and the [commit in coveo.analytics.js](https://github.com/coveo/coveo.analytics.js/commit/fa486ab5d0e593319170bb0f08edad741751c340).
> JSUI-3363 Added snyk configuration

- .deployment.config.json
https://coveord.atlassian.net/browse/JSUI-3364
See issue for details
> Stop veracode from scanning

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/DynamicFacet/DynamicFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- src/ui/Facet/Facet.ts
- src/ui/Facet/FacetHeader.ts
- src/ui/Facet/FacetSettings.ts
- src/ui/FacetSlider/FacetSlider.ts
- src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdown.ts
- src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdownContent.ts
- src/ui/ResponsiveComponents/ResponsiveFacetColumn.ts
- src/ui/ResponsiveComponents/ResponsiveRecommendation.ts
- src/utils/AccessibleModal.ts
- unitTests/ui/ResponsiveComponents/ResponsiveDropdownContentTest.ts
- unitTests/ui/ResponsiveComponents/ResponsiveDropdownTest.ts
- unitTests/ui/ResponsiveFacetColumnTest.ts
https://coveord.atlassian.net/browse/JSUI-3374
Goes along with https://github.com/coveo/search-ui/pull/1863
Reverts these PRs, putting the accessible modal as the facets modal & follow up fixes
https://github.com/coveo/search-ui/pull/1820
https://github.com/coveo/search-ui/pull/1832
https://github.com/coveo/search-ui/pull/1835
> JSUI-3374 Revert JSUI-3332 & JSUI-3351

- package.json
- src/ui/MissingTerm/MissingTerms.ts
- src/utils/UrlUtils.ts
- src/utils/Utils.ts
- unitTests/ui/MissingTermsTest.ts
- unitTests/utils/UtilsTest.ts
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-3373
Bug & fix is explained here in more details https://coveord.atlassian.net/browse/JSUI-3373?focusedCommentId=529680
Snippet to help test out the feature with sample endpoint
```
Coveo.$$(root).on("preprocessResults", function (e, args) {
args.results.results.forEach(function (result, index) {
// Missing terms "President" and "Zelensky" in query "Ukraine President Zelensky"
// No missing terms in query "Ukraine President.Zelensky"
if (index === 0) {
result.absentTerms = ["President", "Zelensky"];
}
// Missing phrase "President Zelensky" in query "Ukraine President.Zelensky" or "Ukraine President Zelensky"
if (index === 1) {
result.absentTerms = ['"President Zelensky"'];
}
// Missing terms "President" and "Zelensky" in query "Ukraine President …
```
> JSUI-3373 Handle "absent phrases" in the MissingTerms component

- package.json
- src/utils/DateUtils.ts
- unitTests/ui/DateUtilsTest.ts
- yarn.lock
more info in the jira --> https://coveord.atlassian.net/browse/JSUI-3393
> JSUI-3393 Upgrade moment

- .deployment.config.json
- Jenkinsfile
- JenkinsfileCloudfrontInvalidation
- invalidate.cloudfront.js
https://coveord.atlassian.net/browse/JSUI-3398
Job: https://searchuibuilds.dev.cloud.coveo.com/job/search_ui/job/cloudfront_invalidation/
> JSUI-3398 create new invalidate cloudfront job in prod

- src/ui/CategoryFacet/CategoryFacet.ts
- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
- src/ui/FacetSlider/FacetSlider.ts
- src/ui/HierarchicalFacet/HierarchicalFacet.ts
- src/ui/TimespanFacet/TimespanFacet.ts
https://coveord.atlassian.net/browse/JSUI-3402
> JSUI-3402 Added explicit `isFieldValueCompatible` to all facets

- src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
- unitTests/ui/ResultsFiltersPreferencesTest.ts
https://coveord.atlassian.net/browse/JSUI-3406
> JSUI-3406 Escape single quotes for ResultsFiltersPreferences captions

- src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts
- src/ui/SmartSnippet/SmartSnippetSuggestions.ts
- unitTests/ui/SmartSnippetSuggestionsTest.ts
https://coveord.atlassian.net/browse/JSUI-3385
Looks like a very long time ago I completely lost track of this issue, and I even still had the branch saved locally...
> JSUI-3385 added titleField and hrefTemplate to SmartSnippetSuggestions

- src/ui/PreferencesPanel/PreferencesPanel.ts
https://coveord.atlassian.net/browse/JSUI-3417
> JSUI-3417 Make the PreferencesPanel Modal Accessible

- package.json
- yarn.lock
https://coveord.atlassian.net/browse/JSUI-3418
> JSUI-3418 Upgade MomentJS

- src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
- strings/strings.json
https://coveord.atlassian.net/browse/JSUI-3417
> JSUI-3417 Make preferences buttons accessible

- src/ui/RelevanceInspector/RankingInfoParser.ts
- unitTests/Fake.ts
- unitTests/ui/RelevanceInspector/RankingInfoParserTest.ts
https://coveord.atlassian.net/browse/JSUI-3422
> JSUI-3422 allow for negative score for QRE weights

- src/ui/HierarchicalFacet/HierarchicalFacet.ts
https://coveord.atlassian.net/browse/JSUI-3420
> make old hierarchical facet expand toggle keyboard usable

- src/utils/ResultListUtils.ts
- unitTests/utils/ResultListUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-3441
For posterity, a page to reproduce the original issue with the pager
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, height=device-height">
<title>Title</title>
<link rel="stylesheet" href="./css/CoveoFullSearch.css" />
<script class="coveo-script" src="js/CoveoJsSearch.Lazy.js"></script>
<script src="js/templates/templates.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
Coveo.SearchEndpoint.configureSampleEndpointV2();
Coveo.init(document.body);
})
//Recommendations Component settings
document.addEventListener('DOMContentLoaded', function () { 
searchRecRoot = document.querySelector("#search_recommendations"); …
```
> JSUI-3441 Exclude recommendation interface from scroll to top

- src/rest/AnalyticsEvent.ts
- src/rest/ClickEvent.ts
- src/rest/SearchEvent.ts
- src/ui/Analytics/LiveAnalyticsClient.ts
- unitTests/ui/LiveAnalyticsClientTest.ts
https://coveord.atlassian.net/browse/JSUI-3443
> JSUI-3443 Added searchQueryUid to custom analytics events

- src/utils/QuerySummaryUtils.ts
- unitTests/utils/QuerySummaryUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-3439
> JSUI-3439 add specific classes to query summary highlights

- src/ui/CategoryFacet/CategoryFacet.ts
> Fix broken link

- src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetBreadcrumb.ts
- unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetBreadcrumbTest.ts
https://coveord.atlassian.net/browse/JSUI-3454
> escape dynamic breadcrumb facet caption

- yarn.lock
https://coveord.atlassian.net/browse/JSUI-3459
> JSUI-3459 edit - fix yarn lock
