src/ui/Facet/BreadcrumbValuesList.ts, strings/strings.json
With this PR, collapsed breadcrumbs will now show "10 more..." instead of "10", the latter of which being confusing when using a numerical filter such as Year.
**Before:**
**After:**
https://coveord.atlassian.net/browse/JSUI-798
=> Fix separators appearing in newDesign + Add "n more..." string

src/ui/ResultList/ResultList.ts, src/ui/Templates/CoreHelpers.ts, src/ui/Templates/TemplateHelpers.ts, test/Test.ts, test/ui/ResultListTest.ts
This cause problem at run time, as use strict is declared, and this is not allowed.
Instead, use the ResultList to specify the currently rendered result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/35)
=> Core Helper -> Remove usage of arguments.caller

src/utils/HashUtils.ts
Causing problems when serializing Standalone searchbox's 'firstQueryMeta'. It was serializing with single-quotes, which caused the JSON parsing to fail on initializing the search page. (JSON.parse doesn't like single-quotes for key/value delimiter)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/53)
=> Fix HashEncoding using single quotes

src/ui/Recommendation/Recommendation.ts, src/ui/Templates/DefaultRecommendationTemplate.ts, test/ui/RecommendationTest.ts
I also fixed a small bug in the default recommendation result template.
https://coveord.atlassian.net/browse/JSUI-907
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/61)
=> Recommendation: Only send actionsHistory in the triggered query

src/ui/Base/RegisteredNamedMethods.ts
After updating to the most recent version, it was causing a compile problem on our side on the line `Coveo.state(this.element, "sort", this.options.defaultSortCriteriaLowercase);` :smile: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/141)
=> Fix missing ellipsis args

src/Index.ts, src/UIBaseModules.ts, src/ui/Base/CoveoJQuery.ts
For legacy reason and older code in the wild that still reference the old module, export the Initialization module under both name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/149)
=> Alias Initialization and CoveoJQuery module

src/rest/EndpointCaller.ts, src/rest/GenericParam.ts, src/rest/SearchEndpoint.ts, test/rest/EndpointCallerTest.ts, test/rest/SearchEndpointTest.ts
This will allow external code to modify all requests parameters before they are sent by the browser.
This will allow, for example, to modify the request headers, the request method, the queryString, etc.
…ll requests sent by the browser.
https://coveord.atlassian.net/browse/JSUI-1044
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/159)
=> Add a requestModifier function on endpoint calls

src/ui/Querybox/Querybox.ts, src/ui/Recommendation/Recommendation.ts, test/ui/RecommendationTest.ts
Better UT for the option.
https://coveord.atlassian.net/browse/JSUI-1118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/171)
=> Add check for hideIfNoResults options before hiding the Recommendation Component

sass/_FieldTable.scss, src/ui/FieldTable/FieldTable.ts, src/ui/Thumbnail/Thumbnail.ts, test/ui/RecommendationTest.ts, test/ui/ThumbnailTest.ts
This allows the "toggle" animation to work correctly when the Thumbnail content is resized.
https://coveord.atlassian.net/browse/JSUI-1116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/172)
=> Resize FieldTable when a thumbnail is loaded

src/ui/Base/ComponentOptions.ts, src/ui/Sort/Sort.ts, test/ui/ComponentOptionsTest.ts, test/ui/SortTest.ts
This ensure that the UI will not fail on initialization if any component is badly configured.
We should not have these kind of behaviour where a single badly configured component can crash the whole initialization. It's better if that single component does not work correctly, but the rest of the interface keeps working.
https://coveord.atlassian.net/browse/JSUI-1123
=> Modified the required check on component options

src/Index.ts, src/ui/ShareQuery/ShareQuery.ts, src/ui/TemplateLoader/TemplateLoader.ts, src/ui/Templates/CoreHelpers.ts, src/utils/Dom.ts, src/utils/StreamHighlightUtils.ts, test/Fake.ts, test/Test.ts, test/ui/DebugTest.ts, test/ui/ShareQueryTest.ts, test/utils/DomTest.ts, test/utils/StreamHighlightUtilsTest.ts, tsconfig.json, typings/browser.d.ts, typings/main.d.ts
This will make it so that any file that reference jQuery will stop compiling.
Re-import old tests for StreamHighlightUtils.
Export all template helpers under the Coveo namespace for backward compatibility.
https://coveord.atlassian.net/browse/JSUI-1125
=> Remove jQuery from ambient typings file

plop/plopTemplates/plop.component.template.hbs, plop/plopTemplates/plop.component.test.template.hbs
Now, when using Plop, our beloved *pretty-typescript* shouldn't complain anymore.
https://coveord.atlassian.net/browse/JSUI-1148
=> JSUI-1148 - Update Plop generator to make linter quite content

src/ui/Recommendation/Recommendation.ts, test/ui/RecommendationTest.ts
If the recommendation component is linked to a main search interface, autoTriggerQuery should automatically switch to false, because the main search interface should be the one managing the query.
https://coveord.atlassian.net/browse/JSUI-1197
=> Arrange for autoTriggerQuery to be false

src/ui/AdvancedSearch/AdvancedSearch.ts, src/ui/AdvancedSearch/Form/Dropdown.ts, src/ui/Analytics/AnalyticsActionListMeta.ts, src/ui/Base/Initialization.ts, test/ui/AdvancedSearch/AdvancedSearchTest.ts, test/ui/AdvancedSearch/Form/DropdownTest.ts
Add a parameter so that select drop does not trigger a query on load.
Add UT
https://coveord.atlassian.net/browse/JSUI-1194
=> Log a generic analytics event for advanced search.

sass/_Tab.scss
Make it so that it's visible when it's focused with keyboard navigation
https://coveord.atlassian.net/browse/JSUI-1202
=> Change outline rule for Tabs 

sass/_AdvancedSearch.scss, src/ui/AdvancedSearch/DocumentInput/SizeInput.ts
Add a section wrapper for date, so it all align nicely on mobile
https://coveord.atlassian.net/browse/JSUI-1209
=> Add flex wrap rule for input section

src/ui/AnalyticsSuggestions/AnalyticsSuggestions.ts, src/ui/Omnibox/Omnibox.ts
This can cuase issue with reveal suggestions on select
Find element only when there is something to search in AnalyticsSuggestions
https://coveord.atlassian.net/browse/JSUI-1232
=> Compact values before trying to build the analytics custom data

src/events/SearchAlertEvents.ts, src/rest/Subscription.ts, src/ui/Facet/BreadcrumbValuesList.ts, src/ui/Facet/Facet.ts, src/ui/FacetSlider/FacetSlider.ts, src/ui/HierarchicalFacet/HierarchicalBreadcrumbValuesList.ts, src/ui/HierarchicalFacet/HierarchicalFacet.ts, src/ui/SearchAlerts/FollowItem.ts, src/ui/SearchAlerts/SearchAlerts.ts, src/ui/SearchAlerts/SearchAlertsMessage.ts, test/rest/SearchEndpointTest.ts, test/ui/SearchAlertsTest.ts
This adds support for the "name" property in the search alert service.
This name property will be populated by the facets in the interface, much like they do for the breadcrumb.
=> Support for "name" when interacting with search alerts

README.md
This link will always download the last coveo-search-ui 1.0 version
=> Fix link to latest version

src/ui/ResultLink/ResultLink.ts, src/ui/ResultLink/ResultLinkOptions.ts, test/ui/ResultLinkTest.ts
*titleTemplate*: allows you to define a display template for what will be displayed as text for the ResultLink. It supports the same syntax as the hrefTemplate and behaves the same way.
It supports terms highlighting via the `StreamHighlightUtils.highlightStreamText()`.
Modified the method parseHrefTemplate and made it into the more generic parseStringTemplate. The same method is now used for both hrefTemplate and titleTemplate.
Added a logger warning when using this template parser for when the key entered is undefined.
Added the corresponding tests.
=> Added a new option on ResultLink

src/ui/Quickview/Quickview.ts, src/ui/ResultLink/ResultLink.ts, src/utils/DomUtils.ts
This bug appeared when jquery was removed. In the jquery days, we used to be able to pass a jquery element or a string to the modal box to set the title. The quickview used this to set the result link. An onclick event was registered on a span then passed to the modal box. Now, since only strings can be passed to the modal box, the onclick event was lost in the process.
Fixed it by replacing the span by an anchor tag which causes the result link to use an href. I also verified that this was not happening anywhere else. To have an onclick event on the title element of the modal box, the event must be registered on the element in the modalbox, not the one that is passed to it.
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a …
=> Fix quickview header title not redirecting to result

src/controllers/FacetQueryController.ts, src/ui/Facet/FacetSearchParameters.ts, test/controllers/FacetQueryControllerTest.ts, test/ui/FacetSearchParametersTest.ts
Use the `q` and `aq` field to launch a search in the facet search. Originally the basic and advanced expression were merged to build the query. This caused problems when using `disableQuerySyntax` and having an advanced expression at the same time.
Even though it is not used anymore, I didn't remove the `expressionToUseForFacetSearch` member on the FacetQueryController since its public and removing it could possibly break some implementations.
=> Properly use the advanced expression in facet search

src/ui/Debug/Debug.ts, src/ui/Omnibox/RevealQuerySuggestAddon.ts, test/ui/DebugTest.ts
At this [line](https://github.com/coveo/search-ui/compare/coveo:9742fee...coveo:f5d7f08#diff-258d9a1f7022d7f279028fcdfa32d240R79) we expect the field to be a string with values separated by semi-colons. In V2 it looks like it has been changed to an array. Added a check to make sure the field is a string before trying to call `split` on the value.
Also added some tests.
=> Field with splitGroupByField could be an array

sass/_ResponsiveComponents.scss, src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdownHeader.ts, src/ui/ResponsiveComponents/ResponsiveFacets.ts, src/ui/ResponsiveComponents/ResponsiveRecommendation.ts, test/ui/ResponsiveComponents/ResponsiveFacetsTest.ts, test/ui/ResponsiveComponents/ResponsiveRecommendationTest.ts
When there are no results or a query error, hide the ResponsiveRecommendation and ResponsiveFacets component.
=> Hide specific responsive components on no results / query error.

deploy.beta.js, src/ui/Folding/Folding.ts, test/ui/FoldingTest.ts
For example, we were missing fieldsToInclude.
Instead of going with a whitelist approach, I clone every property, and remove/modify those that are needed.
https://coveord.atlassian.net/browse/JSUI-1377
=> Clone folding query, and then snipe some properties that should be removed afterward

src/controllers/QueryController.ts, src/events/ResultListEvents.ts, src/ui/Analytics/AnalyticsActionListMeta.ts, src/ui/ResultLayout/ResultLayout.ts, src/ui/ResultList/ResultList.ts, test/controllers/QueryControllerTest.ts, test/ui/ResultLayoutTest.ts
Retrieve last results if possible, instead of doing a new query on layout change.
https://coveord.atlassian.net/browse/JSUI-1370
=> rework ResultLayout to remove possible multiple queries + analytics events

sass/_ResponsiveTabs.scss, sass/_Result.scss, src/ui/ResponsiveComponents/ResponsiveTabs.ts, src/utils/Dom.ts
https://coveord.atlassian.net/browse/JSUI-1375
When checking if the large format of the tab section would overflow, insert the fake tab section before the actual tab section. It was originally placed after the last child of the root interface which caused problems when the tab section was not placed in a way that it could use the whole width.
Also, fixed a small alignment issue with the "more" button for the responsive tabs.
=> Fix overflow check for tab section in unusual contexts

sass/notifications/_SubscriptionsPanel.scss
https://coveord.atlassian.net/browse/JSUI-1413
=> remove min-width on smaller screen for manage alerts panel so that it can scroll laterally.

src/ui/ResultsPreferences/ResultsPreferences.ts
=> DOC-458 ResultsPreferences documentation review

src/ui/Settings/Settings.ts
Removed FollowItem from the list of components that can populate the Settings menu.
=> DOC-458 Settings doc rev: removed FollowItem 

src/ui/ExportToExcel/ExportToExcel.ts
=> DOC-458 ExportToExcel documentation revision

src/ui/FieldTable/Badge.ts, src/ui/FieldTable/FieldTable.ts, src/ui/FieldTable/FieldValue.ts
=> DOC-458 FieldTable documentation revision

src/ui/HiddenQuery/HiddenQuery.ts
=> DOC-458 HiddenQuery documentation revision

src/ui/Icon/Icon.ts
=> DOC-458 Icon documentation revision

src/ui/OmniboxResultList/OmniboxResultList.ts
=> DOC-458 OmniboxResultList documentation revision

src/ui/FacetSlider/FacetSlider.ts
=> DOC-458 FacetSlider documentation revision

src/ui/Omnibox/Omnibox.ts
We weren't able to localized the placeholder attribute on the Omnibox component. This should hopefully resolve that.
=> Allow placeholder attribute to be localized.

src/ui/AdvancedSearch/DocumentInput/AdvancedFieldInput.ts, src/ui/AdvancedSearch/DocumentInput/SimpleFieldInput.ts, src/ui/AdvancedSearch/DocumentInput/SizeInput.ts, test/ui/AdvancedSearch/DocumentInput/AdvancedFieldInputTest.ts, test/ui/AdvancedSearch/DocumentInput/SimpleFieldInputTest.ts
Use query builder instead of string concat for AdvancedSearch component queries, in order to handle corner case more gracefully.
=> Improve AdvancedSearch queries robustness

src/ui/Omnibox/Omnibox.ts, src/ui/ResultLink/ResultLink.ts
Added some information about the option behavior when a search page contains a ResultsPreferences component
- Fixed some link spelling mistakes in Omnibox
- Made option names "prettier" in generated doc site for ResultLink component
https://coveord.atlassian.net/browse/JSUI-1418
=> JSUI-1418 (DOC) - ResultLink.alwaysOpenInNewWindow / ResultsPreferences interaction

sass/mixins/_loader.scss, src/ui/ResultList/ResultList.ts, src/utils/DomUtils.ts, test/ui/ResultListTest.ts
Add some UT in result list for layouts
https://coveord.atlassian.net/browse/JSUI-1461
=> Add spacer for result list in card layout only when it's not infinite scrolling

gulpTasks/test.js, sass/_SearchButton.scss, src/ui/SearchAlerts/FollowItem.ts, test/ui/FacetTest.ts, test/ui/FollowItemTest.ts
Blind keypress action for follow item
Add UT
Will allow to select and navigate the item using tab / enter for accessibility.
https://coveord.atlassian.net/browse/JSUI-1457
=> Add tabindex to follow item

gulpTasks/test.js, src/ui/ResultList/ResultList.ts, test/ui/FacetTest.ts, test/ui/ResultListTest.ts
We cannot reliably detect the correct "infiniteScrollContainer" automatically in every cases.
Since it's very complicated to do so reliably in every cases, I added a way to block successive results that tries to fill the scrolling container automatically.
I also improved documentation, and added a warning in the console when we detect that we are in a bad state.
https://coveord.atlassian.net/browse/JSUI-1462
=> Add a blocking mechanism to stop runaway request that makes browsers very unresponsive with infinite scroll corner cases

src/ui/ResultsPreferences/ResultsPreferences.ts, test/ui/FacetTest.ts, test/ui/ResultsPreferencesTest.ts
UT
https://coveord.atlassian.net/browse/JSUI-1489
=> Add mechanism to check for incoherent configuration versus what exists in local storage for results preferences

src/ui/Omnibox/Omnibox.ts, src/ui/Querybox/Querybox.ts
https://coveord.atlassian.net/browse/JSUI-1529
Having the ability to autofocus the searchbox caused the omnibox suggestions to appear automatically on load. It could also cause other issues such as stealing the focus from another element in the page.
=> remove autofocus option on querybox

src/ui/FacetSlider/FacetSlider.ts, src/ui/ResponsiveComponents/ResponsiveComponentsManager.ts, test/ui/ResponsiveComponents/ResponsiveComponentsManagerTest.ts
caused the facet slider to not be drawn on load, in mobile.
https://coveord.atlassian.net/browse/JSUI-1542
=> register component when responsive class has already been instanciated

sass/_Searchbox.scss
With this simple markup:
```html
<div class='coveo-search-section'>
<div class="CoveoSettings"></div>
<span>blublu</span>
<div class="CoveoSearchbox" data-enable-omnibox="true"></div>
</div>
```
Before the change:
After the change:
In Coveo for Sitecore, Sitecore automatically adds a `code` tag that is invisible in the markup, so our UI is really ugly even though the end result should be the same. This change fixes it quite cleanly.
We could have put a workaround on our side, but I think it is also a small improvement on your side :)
=> Allows CoveoSettings to preceed CoveoSearchbox instead of requiring a direct neighbour

src/ui/AnalyticsSuggestions/AnalyticsSuggestions.ts, src/ui/Omnibox/Omnibox.ts
- Marked the `AnalyticsSuggestions` component as deprecated and indicated the recommended alternative.
- Also changed the link to a more relevant Online Help topic in the `Omnibox` `enableQuerySuggestAddon` option doc.
=> DOC-8 Add JSUI Omnibox code example from search.coveo.com

src/Lazy.ts, src/ui/Base/Initialization.ts, src/ui/Base/RegisteredNamedMethods.ts, src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts, src/utils/DomUtils.ts, test/ui/InitializationTest.ts, test/ui/RegisteredNamedMethodsTest.ts, test/utils/PublicPathUtilsTest.ts
Add a `.load` top level function so that external code that extends a base component in lazy mode can now do something like this : 
```
export function myLazyCustomSearchbox() {
return Coveo.load<Searchbox>('Searchbox').then((Searchbox) => {
class MyCustomSearchbox extends Searchbox {
[ ... ]
}
Coveo.Initialization.registerAutoCreateComponent(MyCustomSearchbox);
return MyCustomSearchbox;
})
}
Coveo.LazyInitialization.registerLazyComponent('MyCustomSearchbox', myLazyCustomSearchbox);
```
Then, after that, a component registered like this would be usable in both ways : lazy and eager.
Meaning, someone can include 
* `CoveoJsSearch.Lazy.js` and then `customstuff.js`, or 
* `CoveoJsSearch.js` and then `customstuff.js`
Both would work.
This will be used in Salesforce integration, for example. …
=> Mechanism for custom component extending base component

src/ui/Facet/Facet.ts, src/ui/FacetSlider/FacetSlider.ts, src/ui/FieldSuggestions/FieldSuggestions.ts, src/ui/ResultLink/ResultLink.ts, src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
DOC-690 - Document the usage of Coveo.options
(these two documentation issues were somehow related)
- Added link to the **Normalizing Facet Value Captions** article in `Facet.options.valueCaption`
- Changed the note that misleadingly said some options could only be set in the `init` call, added relevant links, and modified examples for:
- `Facet.options.valueCaption`
- `FacetSlider.options.getSteps`
- `FacetSlider.options.valueCaption`
- `FieldSuggestions.options.onSelect`
- `ResultLink.options.onClick`
- `ResultsFiltersPreferences.options.filters`
- Made mostly cosmetic changes to the `Facet`, `FacetSlider`, `FieldSuggestions`, `ResultLink`, and `ResultsFiltersPreferences` documentation.
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/pipelines/a35351 …
=> DOC-2 Document how to normalize facet values

src/ui/Searchbox/Searchbox.ts
- Fixed documentation mistake
- Made some cosmetic changes to `Searchbox` reference documentation
=> DOC-900 Replace data-place-holder with data-placeholder

src/ui/Facet/ValueElement.ts, src/utils/KeyboardUtils.ts
When returning false in an event handler, the behaviour is not the same when in a jQuery event, see here http://stackoverflow.com/questions/1357118/event-preventdefault-vs-return-false. Return false will call `preventDefault` and `stopPropagation` when using jQuery. Doing the same thing using the native method `addEventListener` will have no effect. 
The `keypressAction` method would always return false which would break keyboard navigation when using jQuery. 
https://coveord.atlassian.net/browse/JSUI-1585
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> dont always return false in keyboard utils

src/ui/AuthenticationProvider/AuthenticationProvider.ts, src/ui/Facet/Facet.ts, src/ui/SearchAlerts/SearchAlerts.ts
https://coveord.atlassian.net/browse/JSUI-1578
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/459)
=> add doc for value caption disabling alphabetical sort

src/ui/ResultsPreferences/ResultsPreferences.ts, src/ui/ShareQuery/ShareQuery.ts, strings/strings.json
- `ResultsPreferences`: used valid localized string for `ResultLinks`
- `ShareQuery`: removed colons after `Link` and `CompleteQuery` strings
- strings: fixed some minor casing issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coveo/search-ui/462)
=> ADUI-2562 - Need to fix style for Preferences in Content Browser

sass/_FullSearchGrid.scss, sass/neat/grid/_grid.scss, src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts
Also fix an issue with border box being set globally on the page.
https://coveord.atlassian.net/browse/JSUI-1621
=> Return empty array when there's no tab in the page for results preference

src/rest/SearchEndpoint.ts, src/ui/Recommendation/Recommendation.ts, test/rest/SearchEndpointTest.ts, test/ui/RecommendationTest.ts
Machine learning will soon benefit from using actions history on all search and query suggestions calls to provide "personalized" relevance tuning and query suggestions.
This PR adds the needed parameters in those 2 call by adding a new decorator and using it for those 2 API calls.
https://coveord.atlassian.net/browse/JSUI-1604
=> Add actionsHistory to all search and querySuggest calls

gulpTasks/compile.js, gulpTasks/nodeEnv.js, package.json
We were not setting the node environment variable to `production` when minimizing so the css would be included in the bundle, just like when using the dev server.
https://coveord.atlassian.net/browse/JSUI-1668
=> set node prod env for minimizing

src/ui/AdvancedSearch/AdvancedSearch.ts, src/ui/AdvancedSearch/AdvancedSearchInputFactory.ts, src/ui/AdvancedSearch/DateInput/AnytimeDateInput.ts, src/ui/AdvancedSearch/DateInput/BetweenDateInput.ts, src/ui/AdvancedSearch/DateInput/DateInput.ts, src/ui/AdvancedSearch/DateInput/InTheLastDateInput.ts, src/ui/AdvancedSearch/DocumentInput/AdvancedFieldInput.ts, src/ui/AdvancedSearch/DocumentInput/DocumentInput.ts, src/ui/AdvancedSearch/DocumentInput/SimpleFieldInput.ts, src/ui/AdvancedSearch/DocumentInput/SizeInput.ts, src/ui/AdvancedSearch/KeywordsInput/AllKeywordsInput.ts, src/ui/AdvancedSearch/KeywordsInput/AnyKeywordsInput.ts, src/ui/AdvancedSearch/KeywordsInput/ExactKeywordsInput.ts, src/ui/AdvancedSearch/KeywordsInput/KeywordsInput.ts, src/ui/AdvancedSearch/KeywordsInput/NoneKeywordsInput.ts, src/ui/Analytics/AnalyticsActionListMeta.ts, src/ui/Recommendation/Recommendation.ts, test/ui/AdvancedSearch/AdvancedSearchTest.ts, test/ui/AdvancedSearch/DateInput/BetweenDateInputTest.ts, test/ui/AdvancedSearch/DateInput/InTheLastDateInputTest.ts, test/ui/AdvancedSearch/DocumentInput/AdvancedFieldInputTest.ts, test/ui/AdvancedSearch/DocumentInput/DocumentInputTest.ts, test/ui/AdvancedSearch/DocumentInput/SimpleFieldInputTest.ts, test/ui/AdvancedSearch/DocumentInput/SizeInputTest.ts, test/ui/AdvancedSearch/KeywordsInput/AnyKeywordsInputTest.ts, test/ui/AdvancedSearch/KeywordsInput/ExactKeywordsInputTest.ts, test/ui/AdvancedSearch/KeywordsInput/KeywordsInputTest.ts, test/ui/AdvancedSearch/KeywordsInput/NoneKeywordsInputTest.ts
Advanced search being opened in a modal box when the search interface is not global on the body would cause issue with queries not being triggered.
This changes the component so that it triggers it's event from the root of the interface instead of locally (which would bubble up before).
=> Issue with AdvancedSearch opened in external modal box VS search events

src/ui/Base/Initialization.ts, test/ui/RegisteredNamedMethodsTest.ts
Should not take the SearchInterface into account
https://coveord.atlassian.net/browse/JSUI-1693
=> Change check on init for "dual" initialization

src/misc/Logger.ts, src/ui/Base/Initialization.ts
Otherwise the errors gets "eaten" and it gets very hard to debug in lazy mode when something fails in the constructor of a component.
Also pimp up the Logger class a bit to use the appropriate console method when they are available.
https://coveord.atlassian.net/browse/JSUI-1709
=> Log error message at top level of init call in both lazy and eager mode

src/ui/Analytics/Analytics.ts
- Added a note in the `Analytics` component documentation to explicitly
state that its `searchHub` option should not be used for security
reasons.
=> DOC-340 Document JsSearch query suggestions and searchHub best practices

src/ui/Base/QueryBuilder.ts, src/ui/Querybox/Querybox.ts
- Refactored `QueryBuilder` doc to indicate that normally, certain
attributes of the QueryBuilder instance are set by corresponding
`Querybox` options during initialization.
- Some cosmetic changes and clarifications in `Querybox` and
`QueryBuilder` documentation.
=> DOC-444 Different ways to activate wildcards

src/ui/Quickview/Quickview.ts
- Documented the `Quickview` `enableLoadingAnimation` and
`loadingAnimation` options.
- Some other minor documentation adjustements/corrections in the
`Quickview` component documentation.
=> DOC-638 Quickview Component options - loading animation

src/ui/Querybox/Querybox.ts
- Documented certain notable behavior differences between the
on-premises and cloud versions of the Search API regarding query syntax.
=> JSUI-527 Update data-enable-query-syntax doc for Jan 16, 2017 search API release changes

src/events/AnalyticsEvents.ts, src/events/ResultListEvents.ts
`ResultListEvents`
- Documented `ResultListEvents` static class and related args
interfaces.
- Removed unused `IDisplayedNewResultEventArgs` interface.
- Imported `ValidLayouts` type and changed type of
`IChangeLayoutEventArgs.layout` accordingly.
`AnalyticsEvents`
- Removed unused `IAnalyticsDocumentViewEventArgs` interface.
- Improved documentation of `changeAnalyticsCustomData` and its related
args interfaces.
=> DOC-1197 - Improve ResultListEvents & AnalyticsEvents reference doc

src/ui/ResultList/ResultList.ts
- Improved `autoSelectFieldsToInclue` and `fieldsToInclude`
documentation
- Quick revision of entire `ResultList` documentation: cosmetic
changes, added some links, some clarifications/rephrasing.
=> DOC-520 - Fields to include

src/events/OmniboxEvents.ts, src/events/QuickviewEvents.ts, src/ui/Omnibox/FieldAddon.ts, src/ui/Omnibox/OldOmniboxAddon.ts, src/ui/Omnibox/Omnibox.ts, src/ui/Omnibox/QueryExtensionAddon.ts, src/ui/Omnibox/QuerySuggestAddon.ts
`QuickviewEvents.ts`:
- Documented everything.
`OmniboxEvents.ts`:
- Moved the `IPopulateOmniboxSuggestionsEventArgs` interface definition
from `Omnibox.txt`to `OmniboxEvents.ts` (refactored imports accordingly)
- Removed the unused `openOmnibox` and `closeOmnibox` events.
- Documented the `populateOmniboxSuggestions` event and its related
args interface.
`FieldAddon.ts`, `OldOmniboxAddon.ts`, `QueryExtensionAddon.ts`, and
`QuerySuggestAddon.ts`:
- Refactored `IPopulateOmniboxSuggestionsEventArgs` import.
`Omnibox.ts`:
- Removed unused `InitializationEvents` import.
- Some documentation improvements.
=> DOC-1198 Fully document the QuickviewEvents & OmniboxEvents classes

src/ui/ResultTagging/ResultTagging.ts
ResultTagging not available with Cloud V2
=> SFINT-941-ResultTagging

src/ui/Base/ComponentOptions.ts, src/ui/CardOverlay/CardOverlay.ts, src/utils/Utils.ts, templates/All/Card.html
Replace the old default icon names with the new ones, for the CardOverlay component. 
This is to avoid breaking old templates.
=> defensive coding for icon option in card overlay

gulpTasks/strings.js, src/ui/Facet/FacetSearch.ts
We recently added strings translations that were taken from the objectypes/filetypes files without their prefix:
```    out[objecttype.toLowerCase()] = json.objecttype[objecttype].captions;```
This caused the "list" string translation to be overwrited with its object type caption which is `marketing list`.
It's not necessarily wrong to do this as a backup so I inversed the order the strings translations were generated. Now the strings translations will overwrite the file types and object types captions.
=> translations over filetypes captions

docs/playground/src/PlaygroundConfiguration.ts
- Made the `.CoveoSearchInterface` CSS selector more specific (since
the blue header was added to the docs site, there are now two elements
with this class, which explains why this live example was not displaying
itself properly).
- Also specified the `title` option to make the example more complete.
=> DOC-1289 - Fix `HiddenQuery` live example

src/ui/SearchInterface/SearchInterface.ts
- Added the documentation back, but with deprecated tags (which will
appear in red in the generated documentation site).
=> DOC-1314 Reinstate loading animation options documentation

README.md, docs/theme/assets/js/header.js, docs/theme/partials/header.hbs
- Changed standalone searchbox endpoint to coveosearch on Cloud V2
- Changed recommendation field accordingly
- Fixed a closing HTML tag in the readme file
=> DOC-1326 Switch JS UI doc standalone search box to Cloud V2

deploy.doc.sh
deploying
- Added logic at the very beginning of the script.
If the version number in the `package.json` file is lower than the
current version number on npm, the process immediately aborts (exits
with code 2).
=> DOC-1416 Fix docs site job to make it check package version before

src/ui/Base/Initialization.ts, src/ui/SearchInterface/SearchInterface.ts, test/ui/InitializationTest.ts
This ensure that in Lazy Loading, the events gets triggered after the external components have been properly initialized.
https://coveord.atlassian.net/browse/JSUI-1807
=> Change initExternalComponents so that it return a Promises

package-lock.json, src/ui/Base/Initialization.ts, test/ui/InitializationTest.ts
This allows the recommendation component to be added multiple time inside one search interface.
The recommendation component needs to be ignored at initialization, so that they can be instead initialized on their own.
https://coveord.atlassian.net/browse/JSUI-1766
=> Ignore all HTML elements matching the ignore parameters on initialization

gulpTasks/dev.js, gulpTasks/test.js, templates/DynamicsCrm/CardDynamicsCrm.html, templates/Lithium/CardLithiumThread.html, templates/People/CardPeople.html, templates/Salesforce/CardSalesforce.html, templates/SharePoint/CardSharePoint.html, templates/SharePoint/CardSharePointList.html, templates/Slack/CardSlack.html, templates/YouTube/CardYouTubePlaylistItem.html, templates/YouTube/CardYouTubeVideo.html
With this, changing a .html file in the bin folder in dev mode will automatically reload the page.
Also removed all the FollowItem components from the default pages. The search alerts service is not available for 99% of clients anyway...
I also modified the regex for code coverage, it was reporting coverage on ./test files, which is not what we want. For example, if you go on the link that coveralls is outputting on each PR, you'll see it reporting 100% coverage on test utility functions.
This is probably why it bumped to ~90% when you changed that @samisayegh :P  
https://coveord.atlassian.net/browse/JSUI-1800
=>  Auto reload for .html files + remove all SearchAlerts components from templates

src/ui/Distance/GoogleApiPositionProvider.ts
=> JSUI-1831 - Replaced Google Maps API method `GET` by `POST`.

src/events/AnalyticsEvents.ts
interface
- Also documented the `documentViewEvent`.
=> Reinstated/documented the `IAnalyticsDocumentViewEventArgs`

sass/_PrintableUri.scss, src/ui/PrintableUri/PrintableUri.ts, test/ui/PrintableUriTest.ts
This was changed recently this summer, but PrintableUri inheriting from ResultLink causes a lot of issues, mostly to do with multiple call to usage analytics being logged, as well as visual/css issues.
Instead of inheriting, I changed it so that the PrintableUri inherits only the available options from the ResultLink, and then create the component as required, and passing down the option set.
I exposed the needed methods from ResultLink to open the result link.
Since the PrintableUri can output multiple ResultLink, I've decided to always open the "last" link available from those methods, since this will always be the most "precise" link.
https://coveord.atlassian.net/browse/JSUI-1834
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/pipelines/a3535101-5b …
=> Rework PrintableUri to create independant result link instead of inheriting

src/ui/PrintableUri/PrintableUri.ts, src/utils/StreamHighlightUtils.ts
Since we are doing title modification in the PrintableUri (to shorten or split in XML parts), the keyword highlighting that comes from the index need client side manipulation to match correctly.
https://coveord.atlassian.net/browse/JSUI-1859
=> Modify the highlighting in PrintableUri when the title gets modified.

src/utils/Dom.ts, test/utils/DomTest.ts
jQuery only accepts `[a-zA-Z0-9\:\_]` for custom events, so we need to modify event types that we launch internally to match those accepted by jQuery.
https://coveord.atlassian.net/browse/JSUI-1855
=> Add processing for non alpha numeric character for jQuery events

src/ui/Distance/DistanceResources.ts, test/ui/DistanceResourcesTest.ts
We also should not block the complete initialization process if no provider resolves. We can simply disable the component.
https://coveord.atlassian.net/browse/JSUI-1865
=> Modify DistanceResource when the first query is blocked to capture UA

gulpTasks/definition.js, src/ui/SimpleFilter/SimpleFilterValues.ts
The generated definition as "one single big module" should still be typescript 1.x compatible (readonly is a modifier that is only valid for typescript 2.x)
https://coveord.atlassian.net/browse/JSUI-1873
=> Fix definitions for typescript 1.x

sass/_FullSearchGrid.scss, sass/_ResultLayout.scss
This forces the "layout" and "sort" section to not shrink so as to not get all cramped up.
The summary section can be shrinked since it's text that can wrap when we need more space.
https://coveord.atlassian.net/browse/JSUI-1864
=> Some css tweaks for IE11 with result header

templates/All/Default.html, templates/Chatter/Chatter.html, templates/Confluence/Confluence.html, templates/Dropbox/Dropbox.html, templates/Email/EmailThread.html, templates/GoogleDrive/GoogleDrive.html, templates/Jira/Jira.html, templates/Lithium/LithiumThread.html, templates/RSS/RSS.html, templates/Salesforce/Salesforce.html, templates/SalesforceCase/SalesforceCase.html, templates/SalesforceCase/SalesforceCaseComment.html, templates/SharePoint/SharePoint.html, templates/SharePoint/SharePointList.html, templates/YouTube/YouTubeVideo.html
The ResultLink is arguably the most important part of the result, it should be displayed in full.
https://coveord.atlassian.net/browse/JSUI-1862
=> Remove all no-wrap for result-cell containing the ResultLink in default templates

docs/playground/src/Playground.ts, docs/playground/src/PlaygroundConfiguration.ts, docs/playground/src/SearchSectionBuilder.ts, docs/playground/src/SectionBuilder.ts, webpack.playground.config.js
The "playground" is the section that appear in the documentation where you can see a "Live example of ${component name}".
eg : https://coveo.github.io/search-ui/components/facet.html
Pretty much every component need some kind of configuration to be displayed in a manner that make sense or where people consulting the documentation understand properly what the component does exactly. 
This PR add a small utility classes to create standard "sections".
https://coveord.atlassian.net/browse/JSUI-1850
=> Fix some issues in the playground + some refactor

.travis.yml, package-lock.json, src/rest/Query.ts, src/rest/SearchEndpoint.ts, src/ui/Analytics/PendingSearchAsYouTypeSearchEvent.ts, src/ui/Omnibox/QuerySuggestAddon.ts, src/ui/PipelineContext/PipelineContext.ts, src/ui/PipelineContext/PipelineGlobalExports.ts, src/ui/SearchInterface/SearchInterface.ts, test/rest/SearchEndpointTest.ts, test/ui/PipelineContextTest.ts, test/ui/QuerySuggestAddonTest.ts, test/ui/SearchInterfaceTest.ts
The pipeline context would normally get resolved from the last query (when we are doing the call for the query suggest).
In some cases, we want to be able to provide the context without having performed any query.
This adds a logic in `SearchInterface` to `getQueryContext()`.
The search interface will return the last query context, if available.
If not available, instead it will try to resolve any `PipelineContext` component, and query them to retrieve the context.
This also adds a couple of utility method on the `PipelineContext` component to set and get the context.
=> Provide a way to resolve pipeline context when no query is performed

src/EventsModules.ts, src/events/DistanceEvents.ts, src/ui/Distance/DistanceResources.ts, src/ui/Distance/GoogleApiPositionProvider.ts, src/ui/Distance/NavigatorPositionProvider.ts, src/ui/Distance/StaticPositionProvider.ts, src/ui/Facet/FacetSearch.ts, src/ui/Facet/FacetSettings.ts, src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdownContent.ts, src/ui/ResponsiveComponents/ResponsiveTabs.ts, src/ui/SearchAlerts/SearchAlertsMessage.ts, src/ui/Settings/Settings.ts, src/utils/PopupUtils.ts, test/ui/DistanceResourcesTest.ts
It conflicts in the generated .d.ts with an existing `IPosition` in `PopupUtils`:
```
export interface IPosition {
vertical: VerticalAlignment;
horizontal: HorizontalAlignment;
verticalOffset?: number;
horizontalOffset?: number;
horizontalClip?: boolean;
}
```
😢
It still generates a valid .d.ts, but it gives a warning that I need to implement `vertical` and `horizontal`  
=> IPosition changed to IGeolocationPosition

package.json
People installing our package never actually use node when interacting with our package. We originally had it only for heroku but it's not actually necessary.
https://coveord.atlassian.net/browse/JSUI-1929
=> remove engine field from package.json

src/controllers/HistoryController.ts, src/models/Model.ts, src/ui/Analytics/SharedAnalyticsCalls.ts, src/ui/Omnibox/Omnibox.ts, src/ui/OmniboxResultList/OmniboxResultList.ts, src/ui/SearchInterface/SearchInterface.ts, src/ui/Sort/Sort.ts, src/utils/Utils.ts, test/controllers/HistoryControllerTest.ts
If the url hash gets modified (either manually, or with custom javascript code), we will now try to detect those change and log the corresponding analytics event.
https://coveord.atlassian.net/browse/JSUI-1810
=> Support logging analytics event on hash change in the URL

package.json, src/ui/Quickview/Quickview.ts, src/ui/Quickview/QuickviewDocument.ts, src/ui/Quickview/QuickviewFields.ts, src/utils/DomUtils.ts, test/Test.ts, test/ui/QuickviewTest.ts, test/utils/DomUtilsTest.ts, yarn.lock
Also include a couple of bugfixes for possibly undefined ResultLink component in lazy mode
This updaes the modalbox module to accept either an HTMLElement or a string for the title of the modal, instead of a only string.
https://coveord.atlassian.net/browse/JSUI-1877
=> Rework UA logging for Quickview 

src/ui/OmniboxResultList/OmniboxResultList.ts, src/utils/Dom.ts, test/Test.ts, test/ui/OmniboxResultListTest.ts
Card layout is too weird in Omnibox result list, so this will force the component to use the standard list layout.
This also add a change to ignore some components in the result list to let them handle their own click event, as opposed to always redirect to an external page.
Add UT.
https://coveord.atlassian.net/browse/JSUI-1841
=> Force list layout + adding some UT for this class

src/ui/ResultList/ResultList.ts, test/ui/ResultListTest.ts
This would cause problem when external/custom code would try to access this propery to determine if more results were available.
It was only getting calculated properly in infinite scrolling mode.
https://coveord.atlassian.net/browse/JSUI-1933
=> Change reachedEndOfResults to a dynamic value

src/controllers/FacetQueryController.ts, src/controllers/FacetSliderQueryController.ts, src/ui/Base/QueryBuilder.ts, src/ui/Base/QueryBuilderExpression.ts, src/ui/Facet/FacetSearchParameters.ts, test/controllers/FacetSliderQueryControllerTest.ts, test/ui/FacetSearchParametersTest.ts, test/ui/QueryBuilderTest.ts
Some places were still passing in possible query syntax inside facet queries.
Re-factored the query builder expression part a bit to hopefully make the code a bit clearer.
https://github.com/coveo/search-ui/compare/JSUI-1946
=> Remove any usage of query syntax in query override

plop/plopfile.js
In order for the handlebars to be replaced with the actual component name the call to plop.renderString prior to calling path.resolve was missing.
=> Fixed the file name generation via handlebars

src/ui/FacetRange/FacetRange.ts
This removes the special check on the "keepDisplayedValuesNextTime" property from the base Facet component.
This property is already handled correctly by the base facet component, thus making this check here un-necessary.
https://coveord.atlassian.net/browse/JSUI-1857
=> Always sort group by results by numerical value.

src/utils/Utils.ts, test/utils/UtilsTest.ts
When merging two arrays containing HTML elements, the element would be detected as an `object`. The merge would try to read its keys and merge the values just like a normal JS object.
This fixes the issue by considering an HTML element as a simple value instead of an object. It is covered by the `should merge two arrays with HTML element values` test.
=> Fix extend deep when merging arrays of HTML elements

src/ui/Folding/Folding.ts
To indicate that the values of those fields in the index should only contain alphanumerical characters.
=> Added note in `childFiled` and `parentField` options

src/rest/AccessToken.ts, src/rest/AnalyticsEndpoint.ts, src/rest/EndpointCaller.ts, src/rest/SearchEndpoint.ts, src/ui/Analytics/Analytics.ts, src/ui/Analytics/AnalyticsClient.ts, src/ui/Analytics/MultiAnalyticsClient.ts, src/ui/Analytics/NoopAnalyticsClient.ts, test/Test.ts, test/rest/AccessTokenTest.ts, test/ui/AnalyticsEndpointTest.ts, test/ui/AnalyticsTest.ts, test/ui/PendingSearchAsYouTypeSearchEventTest.ts, test/ui/SearchInterfaceTest.ts
Search Endpoint + Analytics are both using search token by default to authenticate. Search token expires after 12 hours. There was a renewal mechanism in place for search endpoint which was not properly propagated to the analytics components.
This PR refactor "access token" options, which were plain string, to an actual AccessToken class which encapsulate the renewal mechanism a bit more, as well as providing way to subscribe to renewal events.
https://coveord.atlassian.net/browse/JSUI-1945
=> Refactor Access Token renewal for Analytics + Search Endpoint

src/TemplatesModules.ts
Breaks *at runtime* if using 
```
import { TemplateHelpers } from "coveo-search-ui"; 
TemplateHelpers.anything()
```
while TypeScript is still compiling.
Change was done here: https://github.com/coveo/search-ui/pull/707/files#diff-17d3fb7a4319ae62917f4161770e4023L1
And breaks starting with 2.3826.0
JSUI-1980
=> Put back export of TemplateHelpers

sass/_FullSearchGrid.scss
the SimpleFilter background had `display: inherit` so it covered the entire search page.
https://coveord.atlassian.net/browse/JSUI-1995
=> less specific selector for after initialization display:inherit

src/ui/Recommendation/Recommendation.ts, test/ui/RecommendationTest.ts
The hide-if-no-results option on the recommendation component broke because of this change https://github.com/coveo/search-ui/pull/741/files#diff-1fd33db2e97b1b3b50602c19e35c19efR490.
The inline style was override the `coveo-hidden` class so I went back to something similar to the old behaviour we had when hiding/showing the recommendation component.
https://coveord.atlassian.net/browse/JSUI-2011
=> correctly hide recommendation component

src/ui/Base/ComponentOptions.ts
If the `option.alias` doesn't exist, simply return `undefined` this is the normal behavior of doing a `getAttribute()` with an `undefined` or `null` parameter according to the w3 specification and behavior in browser.
=> Added a check to getAttributeFromAlias to not check without an alias.

src/ui/Omnibox/OldOmniboxAddon.ts
Caching would prevent facet suggestions to be redrawn and updated properly on selection/exclusion.
We trade a bit of speed (caching) for simplicity. 
Seems a good tradeoff, especially since the "old" omnibox addon is not used for 95% of setup, especially recent ones with a lot of traffic.
https://coveord.atlassian.net/browse/JSUI-1971
=> Remove simili caching mechanism in old omnibox addon

sass/_SimpleFilter.scss, src/ui/SimpleFilter/SimpleFilter.ts
I added a sneaky 2 px padding, looks better visually since arrow + text is kinda weird looking when they are actually center aligned together.
https://coveord.atlassian.net/browse/JSUI-1988
=> Cheat on arrow svg alignment for simple filter

src/ui/Backdrop/Backdrop.ts, src/ui/Base/Initialization.ts, src/ui/ResultList/ResultList.ts, src/ui/YouTube/YouTubeThumbnail.ts, src/utils/DomUtils.ts, test/MockEnvironment.ts, test/ui/InitializationTest.ts
The initial problem was for "QuickviewHeader", which was directly calling the component constructor, without properly resolving the initialization option for ResultLink.
Since it's a pattern that is used in a couple of different place, I decided to add an helper method for that in Initialization module.
https://coveord.atlassian.net/browse/JSUI-2022
=> Add a dedicated initialization function for results element

package.json, src/events/QueryEvents.ts, src/ui/Base/Initialization.ts, src/ui/DidYouMean/DidYouMean.ts, yarn.lock
Updated to TypeScript 2.8, plus I tried out the "auto organize imports" feature that is new in the language in a couple of different file.
You can use it directly from vscode ( cmd palette > typescript: organize imports )
https://coveord.atlassian.net/browse/JSUI-2047
=> Update TS 2.8 + organize some imports

src/ui/SimpleFilter/SimpleFilter.ts, test/ui/SimpleFilterTest.ts
Not the cleanest fix, but it's pretty "surgical". 
Refactoring to handle checkbox selection depending on the user action would be much more involved and risky, so a simple flag seems the simplest approach.
https://coveord.atlassian.net/browse/JSUI-2014
=> Add a flag to block query in simple filter when clearing breadcrumb

docs/theme/partials/member.sources.hbs
https://coveord.atlassian.net/browse/JSUI-2049
=> Add missing path in generated documentation URL

src/events/InitializationEvents.ts, src/rest/Query.ts
- Enclose "fake" links between back-ticks so they don't get rendered as `a` tags
- Update external link to _Using Wildcards in Queries_ OH topic
=> [DOC-2015] Fix "broken" links in docs

src/ui/Omnibox/Omnibox.ts
https://coveord.atlassian.net/browse/JSUI-2085
=> Do not modify omnibox content on blur if last query matches exactly what is already inside the omnibox

sass/_Searchbox.scss, src/ui/Omnibox/Omnibox.ts, src/ui/Querybox/Querybox.ts, test/ui/OmniboxTest.ts
https://coveord.atlassian.net/browse/JSUI-2109
=> Disable syntax highlights in search box when query syntax is disabled on the component

filetypes/common.json, filetypes/objectType.json
The "shouldDisplayLabel" property is used to signify that a label should be used in tandem with the icon, because the icon might be too "ambiguous".
Since we've recently added a ton of new icons, we can remove the label since we have many more icons than can now be more precise.
https://coveord.atlassian.net/browse/JSUI-2107
=> Remove many "shouldDisplayLabel" + use more precise icons

src/ui/ChatterPostAttachment/ChatterPostAttachment.ts, src/ui/ChatterPostAttachment/ChatterPostAttachmentFields.ts, src/utils/Utils.ts, test/Fake.ts, test/ui/ChatterPostAttachmentTest.ts
In the new version of the schema service, the field `sfcontentfilename` does not exist anymore and it's replaced by `sftitle` or `sf_title`. I added them as `alternative` to `sfcontentfilename`
=> Add sftitle and sf_title to the ChatterPostAttachment JSUI-2119

.travis.yml, gulpTasks/definition.js, gulpfile.js, package.json, sass/bourbon/css3/_flex-box.scss
In addition to coverting box -> flex, I:
- Moved the `gulp doc` task to be part of the default gulp task.
- Moved the typedefintion validation gulp task to Travis.
I tested that the conversion from box to flex resolves the warnings when compiling the interface editor. To do this however, I needed to delete all search-ui CSS lines that contained:
`background-image: url(<svg>)`
For some reason, building the search-ui on my machine was adding an svg tag inline in the CSS file instead of placing a url to the svg image.
=> JSUI-2120 Converting display:box to display:flex

src/ui/Quickview/QuickviewDocumentIframe.ts
For cross browser compatibility : onload event was not being triggered properly in IE/Safari/Edge
https://coveord.atlassian.net/browse/JSUI-2145
=> Change order to bind the `onload` function for Quickview

src/ui/SearchInterface/SearchInterface.ts
=> Doc 3103 fix default value for allow queries without keywords

src/ui/FacetSlider/FacetSlider.ts, src/ui/ResponsiveComponents/ResponsiveComponentsManager.ts, unitTests/ui/ResponsiveComponents/ResponsiveComponentsManagerTest.ts
Resize events are sometimes not triggered in SFINT, because the reflow of the document can take too long, making the outer window well resized but not the inner, nor the div in the document.
That can cause the responsive components breakpoints to not be triggered.
To fix this issue, I propose the following PR, based on the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Events/resize).
In a nutshell, I'm waiting for the resize event to stop being triggered for at least 250ms before actually calling the listener.
=> Add debounce on every resize listener

src/controllers/HistoryController.ts, src/controllers/HistoryManager.ts, src/controllers/LocalStorageHistoryController.ts, src/controllers/NoopHistoryController.ts, src/ui/DidYouMean/DidYouMean.ts, src/ui/SearchInterface/SearchInterface.ts, unitTests/MockEnvironment.ts, unitTests/ui/DidYouMeanTest.ts, unitTests/ui/SearchInterfaceTest.ts
Replace history state will not create a new history entry, and so it will be possible to "pop" from the last browser state properly without getting stuck in a loop where you are going back to an invalid query that return corrections automatically.
https://coveord.atlassian.net/browse/JSUI-2058
=> Replace history state when doing auto query correction

src/ui/ResultActions/ResultActionsMenu.ts, unitTests/ui/ResultActionsMenuTest.ts
The menu should stay open when you click on a button, that way you can see the status of buttons like Attach To Case.
I also tested on mobile. I think it makes sense to always show the menu when you click on a result. Making it disappear when you click is confusing because again, the status of the button disappeared, so you have to click again to see if you item was attached to the case.
@sbelzile-Coveo @olamothe @tedre191 
=> Result actions menu stay open on click

accessibilityTest/AccessibilityErrorReport.ts, src/ui/ErrorReport/ErrorReport.ts, src/utils/Dom.ts
https://coveord.atlassian.net/browse/JSUI-2199
=> Fix couple of issue on ErrorReport accessibility features

src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdown.ts
The simplest solution I could find was to remove the blur event. I think this is inline with accessibility practices. I looked at sites like github and stackoverflow and found that "dropdowns" are not closed when blurring/tabbing away from the parent element.
https://coveord.atlassian.net/browse/JSUI-2212
=> JSUI-2212 Removing blur event from filter button

src/events/InitializationEvents.ts, src/ui/Base/Initialization.ts, src/ui/Distance/DistanceResources.ts, src/ui/Distance/GoogleApiPositionProvider.ts, unitTests/ui/DistanceResourcesTest.ts, unitTests/ui/InitializationTest.ts, unitTests/ui/RegisteredNamedMethodsTest.ts
So the idea here is to support a parameter that blocks the Initialization pipeline until an operation is finished.
This allows other components to add an event handler on `beforeInitialization`, `afterComponentsInitialization` or `afterInitialization` to defer the step until some async stuff is done.
For instance, the Distance Resources component could defer the initialization when "cancelQueryUntilPositionResolved" is true instead of canceling all queries. It would end up in a much more natural flow, leaving the placeholders on until the position is resolved.
Another use case is to dynamically fetch values asynchronously to create HTML that contains Components. This way, the components will be properly initialized before the whole Search Interface initialization process finishes.
It …
=> Allow to defer initialization through event args

src/controllers/QueryController.ts, unitTests/controllers/QueryControllerTest.ts
Whenever there's a new query, we receive a search UID from the API, that we need to set on each query results so that we can track it on click of each document. When fetching more results (eg: pager), we do not want to mark that as a "new" query, but instead a continuation of the last one.
The keepLastSearchUid parameter was not respected properly when passed in as an option to the query controller, making it so that the "Results per page component" would not correctly re-use the same ID, leading to incoherent event in UA.
Also did some janitor duty (reorganize imports/var -> const)
https://coveord.atlassian.net/browse/JSUI-2223
=> Fix issue to respect the "keepLastSearchUid" parameter.

sass/_Quickview.scss, src/ui/Quickview/Quickview.ts
https://coveord.atlassian.net/browse/JSUI-2207
Caption now moves according to the border of the results column
=> Use popper.js for quickview tooltip

src/controllers/HistoryController.ts, src/ui/Analytics/AnalyticsActionListMeta.ts, src/ui/CategoryFacet/CategoryFacet.ts, src/ui/CategoryFacet/CategoryFacetSearch.ts, src/ui/Facet/BreadcrumbValueElement.ts, src/ui/Facet/Facet.ts, src/ui/Facet/FacetHeader.ts, src/ui/Facet/FacetSearch.ts, src/ui/Facet/FacetSettings.ts, src/ui/Facet/OmniboxValuesList.ts, src/ui/Facet/ValueElement.ts, src/ui/FacetSlider/FacetSlider.ts, src/ui/FieldValue/FieldValue.ts, src/ui/ResultTagging/ResultTagging.ts, unitTests/controllers/HistoryControllerTest.ts, unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts, unitTests/ui/FacetTest.ts
It was simple to add the facetField for all facet events sent to UA where the facetId was already sent. This way it will already be present if needed in the future.
https://coveord.atlassian.net/browse/JSUI-2158
=> Jsui 2158 Add the facet field in facetSelect search event

src/ui/PipelineContext/PipelineContext.ts
Modified the PipelineContext introduction to mention `setContext` and `setContextValue`, and to remove `buildingQuery`.
In the reference doc of `setContext` and `setContextValue` functions, mentioned that they are only available since the december 2017 release.
Also significantly leaned out the introduction. It now only mentions the minimum and links to  https://docs.coveo.com/en/399/javascript-search-framework/adding-custom-context-information-to-queries for more details (btw, this page is currently being updated accordingly).
=> Doc 2444 update pipelinecontext doc

src/ui/Facet/Facet.ts, src/ui/Facet/FacetHeader.ts, src/ui/Facet/FacetSettings.ts, src/ui/Facet/ValueElementRenderer.ts, src/utils/AccessibleButton.ts, strings/strings.json, unitTests/ui/FacetHeaderTest.ts, unitTests/ui/FacetSettingsTest.ts, unitTests/ui/FacetTest.ts, unitTests/ui/ValueElementRendererTest.ts, unitTests/utils/AccessibleButtonTest.ts
- Facet values given role heading level 3 to allow jumping between screen readers.
- Facet search button is now accessible (but no search input/list).
- Facet more/less buttons are now accessible.
- Facet reset button is now accessible.
- Facet Settings button is now accessible (but not list).
- Added unit tests for click and enter key behaviour.
=> JSUI-2236 Improving Facet accessibility

.travis.yml
The issue: Travis PR builds from a fork will fail because the secrets are not shared, which is fine.
So I applied this workaround suggested by Travis-CI itself: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
=> Remove veracode from PR  JSUI-2270

src/ui/ResultList/ResultList.ts, unitTests/ui/ResultListTest.ts
Wait for the result to be actually rendered before checking if we need more result in the case of an infiniteScroll resultList.
=> Wait for result to be displayed in ResultList.handleQuerySuccess

src/ui/ResponsiveComponents/ResponsiveFacetColumn.ts, src/ui/ResponsiveComponents/ResponsiveRecommendation.ts, src/ui/ResponsiveComponents/ResponsiveResultLayout.ts, src/ui/ResponsiveComponents/ResponsiveTabs.ts, unitTests/MockEnvironment.ts, unitTests/ui/ResponsiveComponents/ResponsiveFacetsTest.ts, unitTests/ui/ResponsiveComponents/ResponsiveRecommendationTest.ts, unitTests/ui/ResponsiveComponents/ResponsiveTabsTest.ts
The issue was that the `needSmallMode` didn't use the responsive component and so didn't care about what was the responsive mode. Now if the responsive mode is set, then it'll be used before any breakpoints.
=> Fix responsiveMode feature JSUI-2269

src/ui/CategoryFacet/CategoryFacet.ts
- fixed a few broken links
- added a few missing descriptions
- leaned out the reference doc and referred to docs.coveo.com page. See https://bitbucket.org/coveord/doc_jekyll-public-site/pull-requests/959/doc-3950-category-facet/diff for the relevant docs.coveo.com pull request.
=> Doc 3950 category facet doc

src/ui/Analytics/PendingSearchEvent.ts
This code block was referenced in the following discuss post: https://discuss.coveo.com/t/how-to-track-long-queries-lq-in-usage-analytics/2123
I asked Marie Beaulieu and it turns out ML actually doesn't learn from refinedKeywords. Hence, I suggest deleting the comment.
=> [DOC-4043] - removed note about learning from refinedKeywords

gulpTasks/definition.js, src/utils/DateUtils.ts, unitTests/ui/CoreHelpersTest.ts
https://coveord.atlassian.net/browse/JSUI-2326
=> Date/datetime values displayed on result templates ignore the current locale.

src/ui/ResultLink/ResultLink.ts
=> Fix a couple of typos in ResutLink documentation

src/rest/QueryResult.ts, src/rest/SearchEndpoint.ts, src/ui/Base/QueryBuilder.ts, src/ui/ResultRating/ResultRating.ts, src/ui/SearchInterface/SearchInterface.ts
=> Add notes stating that result rating is obsolete in Cloud V2

src/ui/CategoryFacet/CategoryFacet.ts
Bug initially reported because of a misunderstanding on how to specify a "deeper" base path in the component.
I did not want to go into the whole option validation aspect, because that's another whole level of work. We'll see if we need it in the future.
I simply added more precision in the documentation.
https://coveord.atlassian.net/browse/JSUI-2342
=> Add more documentation on how to specify the option/format for CategoryFacet basePath

src/controllers/FacetQueryController.ts, unitTests/controllers/FacetQueryControllerTest.ts
Add an advanced override when additionnalFilter + advancedQueryExpression are defined & no values are selected in the facet
https://coveord.atlassian.net/browse/JSUI-2361
=> JSUI-2361 Facet add advanced override when additionnalFilter is passed & no values are selected

src/ui/Templates/CoreHelpers.ts
I added a note to the `highlightStreamHTML/highlightStreamText` parameters of the ICoreHelper component in order to make it more clear as to what they should be used for.
=> Doc 4003 improve documentation regarding highlighting

src/ui/Recommendation/Recommendation.ts
Escape recommendations history element title before storing it to fix 500 error when special characters exist https://answers.coveo.com/questions/19799/500-error-when-special-characters-exist-on-title-i.html
=> Escape recommendations history element title

sass/_CategoryFacet.scss, src/ui/CategoryFacet/CategoryFacet.ts, src/ui/CategoryFacet/CategoryFacetBreadcrumb.ts, src/ui/CategoryFacet/CategoryValue.ts, unitTests/ui/CategoryFacet/CategoryFacetBreadcrumbTest.ts, unitTests/ui/CategoryFacet/CategoryFacetTest.ts, unitTests/ui/CategoryFacet/CategoryValueTest.ts
- Adding the valueCaption option to the CategoryFacet values and breadcrumbs.
- Not creating a CategoryFacetSearchbox when value captions are specified.
- Fixing a bug where no footer is rendered when the logic dictates not to render the more/less buttons.
=> JSUI-2385 Adding #valueCaption option to CategoryFacet

src/ui/Omnibox/Omnibox.ts, unitTests/ui/OmniboxTest.ts
I introduced a regression with my last PR for this jira. I was updating `lastQuery` before calling `shouldExecuteQuery` causing the `cancel` property to be set to true all the time. This prevents sending a query for a regular search that does not use search-as-you-type.
=> JSUI-2383 Calling shouldExecuteQuery before updating this.lastQuery

src/ui/ResponsiveComponents/ResponsiveComponentsManager.ts, unitTests/ui/ResponsiveComponents/ResponsiveComponentsManagerTest.ts
The goal of this PR is to support the responsive mode override feature even when the component is hidden.
When the responsive mode is set to a value other than auto, the width check is no longer require because we no longer needs to detect the appropriate responsive mode.
=> Support Responsive Mode option inside the ResponsiveModeManager SFINT-2135

src/magicbox/SuggestionsManager.ts, src/utils/Dom.ts, unitTests/magicbox/SuggestionsManagerTest.ts, unitTests/utils/DomTest.ts
See the issue by the jira number.
tl;dr e.relatedTarget should be null in LockerService but is `{}` instead.
=> Support suggestions in LockerService SFINT-2110

src/utils/DateUtils.ts
Norwegian calendar retrieval using Globalize was failing because we were passing the momentjs locale `nn` instead of `no`.
https://coveord.atlassian.net/browse/JSUI-2386
=> JSUI-2386 Using non-momentjs locale code when retrieving Globalize calendar

src/controllers/QueryController.ts, src/events/QueryEvents.ts, src/ui/Analytics/AnalyticsActionListMeta.ts, src/ui/Querybox/Querybox.ts, src/ui/Querybox/QueryboxOptionsProcessing.ts
=> Change "search as you type" to "search-as-you-type" in docs & warnings

src/ui/OmniboxResultList/OmniboxResultList.ts, unitTests/Simulate.ts, unitTests/ui/AnalyticsSuggestionsTest.ts, unitTests/ui/FieldSuggestionsTest.ts, unitTests/ui/OmniboxResultListTest.ts
I had some difficulty understanding the root cause of why this issue happens on page refresh only.
I used a more pragmatic solution that checks if we have results. If there aren't any, we skip appending the Omnibox result list title/results, and do not trigger the `newResult` and `newResults` events).
=> JSUI-2389 Not appending OmniboxResultList title and body when no results.

src/ui/Facet/FacetSearch.ts, src/ui/Facet/FacetSearchDropdownNavigation/FacetSearchDropdownNavigator.ts
When there is a query in the facet search box, a "Search All" element is added to the result list. This element has a different mark-up from a normal result. This caused the dropdown navigation logic to throw an error in the console. It also cannot be excluded, requiring an exception in the navigation logic. 
https://coveord.atlassian.net/browse/JSUI-2408
=> JSUI-2408 Making "Search All" button accessible

src/ui/ResultsPerPage/ResultsPerPage.ts, unitTests/Simulate.ts, unitTests/ui/ResultsPerPageTest.ts
Initial choice would override the user selection in some case, because the initial state was not properly setup on load (after afterInitialization).
https://coveord.atlassian.net/browse/JSUI-2421
=> Fix ResultsPerPage for configuration with initial choice

src/utils/DateUtils.ts, unitTests/ui/DateUtilsTest.ts
Our documentation for formatting dates was not in sync with the syntax of our formatting library (momentjs). This PR transforms user-specified formats to align with momentjs syntax and give the outputs detailed in our documentation.
https://coveord.atlassian.net/browse/JSUI-2436
=> JSUI-2436 Transforming documented date format to momentjs format

src/ui/Analytics/AnalyticsActionListMeta.ts, src/ui/Templates/TemplateFieldsEvaluator.ts, src/utils/QueryUtils.ts, unitTests/ui/TemplateFieldsEvaluatorTest.ts
Normally, the field values we receive are strings. However, when specifying a multi-value field, the value is a string array. The logic uses a `.toLowercase()` call which fails on an array, causing the condition to fail.
=> JSUI-2437 Supporting fields with array values (e.g. multi-value fields) in template conditions using data-field-

src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdownContent.ts, src/ui/Settings/Settings.ts
For this, we agreed that the facets should take all the space when it's available. The problem is that popper when at the root of the window, outside the Coveo Search Interface. Adding a boundariesElement fixes that. See JIRA for example
https://coveord.atlassian.net/browse/JSUI-2456
=> JSUI-2456 Add the search interface root for popper elements

src/ui/Templates/TemplateFieldsEvaluator.ts, unitTests/ui/TemplateFieldsEvaluatorTest.ts
Native map function throws an error on an undefined value, whereas underscore has built-in protection against that.
https://coveord.atlassian.net/browse/JSUI-2459
=> Result with no field value should not throw an error when being evaluated against a template

src/rest/AnalyticsEndpoint.ts, src/rest/AnalyticsEndpointCaller.ts, src/rest/EndpointCaller.ts, src/ui/Analytics/Analytics.ts, unitTests/Test.ts, unitTests/rest/AnalyticsEndpointCallerTest.ts, unitTests/ui/AnalyticsEndpointTest.ts, unitTests/ui/AnalyticsTest.ts
We'll need to wait for UA to modify the write service to accepts different Content-Type for this to work, but this is the changes that would be required. For now, I just did the modification without being able to test it for real from end to end, so this is not ready to be merged yet.
I'm not 100% happy with the changes though, as it uses beacon for *all* click events, as opposed to only those that will make the page unloads from the browser (ie: navigating to another page). That's because, on a beacon event, we cannot listen to the response for the request (which is okay when the user is leaving the page anyway), but would not be ideal for normal click event that do not make the browser load a new page.
I have to think a bit more about what I could do to achieve that.
I'll also add tests …
=> Use beacon to send click event

src/events/AnalyticsEvents.ts, src/ui/Analytics/Analytics.ts, src/ui/Analytics/LiveAnalyticsClient.ts, src/ui/Analytics/PendingSearchEvent.ts, unitTests/ui/AnalyticsTest.ts, unitTests/ui/LiveAnalyticsClientTest.ts
=> JSUI-2467 Populate GTM datalayer with Coveo UA event data

src/ui/ResultsPerPage/ResultsPerPage.ts, unitTests/ui/ResultsPerPageTest.ts
https://coveord.atlassian.net/browse/JSUI-2390
When the default value of ResultsPerPage was in ChoiceDisplayed, it didn't use the initial choice option
=> initialChoice is use in resultPerPages

src/utils/DateUtils.ts, unitTests/ui/CoreHelpersTest.ts, unitTests/ui/DateUtilsTest.ts
We introduced a regression in the long date format in [this PR](https://github.com/coveo/search-ui/commit/747843360b05fe6f3da930a962cafa61dd88b01a), where the different parts of the date stopped being delimited by commas.
Here is the relevant snippet from the linked PR:
```
if (options.useLongDateFormat) {
-    return dateOnly.format('dddd, MMMM DD, YYYY');
+    return `${dateOnly.format('dddd')} ${dateOnly.format('LL')} ${dateOnly.format('YYYY')}`;
}
```
This PR readds the commas and a unit test.
https://coveord.atlassian.net/browse/JSUI-2488
=> JSUI-2488 Readding commas to long date format

src/ui/Quickview/QuickviewDocument.ts, unitTests/ui/QuickviewDocumentTest.ts
By triggering the event of the search interface rather than the CoveoQuickViewDocument, listeners on the SearchInterface or the body tag containing the interface will receive the event only once, which is what we want.
This solution is still breaking if a listener is attached on the `CoveoQuickviewDocument` or any parent up to but not including the body tag. This breaking change is reflected in the updates to the unit tests.
Another more complex option would be to:
1. Detect if the root and the body tag are the same element.
2. a. If they are, trigger the event on the element only.
b. If they are not, trigger the event on the element and on the Search Interface.
The down-side of this solution is if the listener is on the body tag rather than the SearchInterface (which Jerome mentions is …
=> JSUI-2491 Triggering openQuickView event on SearchInterface instead of element

src/ui/ResultList/ResultContainer.ts
With this change popper's reference seems to be correctly destroyed and the message doesn't show up in IE11
https://coveord.atlassian.net/browse/JSUI-2475
=> JSUI-2475 Use the DOM empty method instead of overwritting innerHTML

sass/_Quickview.scss
https://coveord.atlassian.net/browse/JSUI-2495
So this was the problem: https://github.com/sass/sass/issues/818
After more testing, the rule for left and top when using calc() was always overwritten because the element had the value set so I decided to delete it
=> JSUI-2495  scss variables not converted in css

docs/playground/src/PlaygroundConfiguration.ts
https://coveord.atlassian.net/browse/JSUI-2489
What I think happened is if we used the `withComponent` method, the browser simply delete the script tag so the browser then tried to render the component but it failed since a lot of its values were not initialized yet.
Putting text directly fixed that problem.
=> JSUI-2489 Fix the issue where the OmniboxResultlist didn't render in the docs

src/ui/ResultList/ResultList.ts, unitTests/ui/ResultListTest.ts
The issue arose due to the fact that **Window** is not **Window** in **Lightning Locker** but is instead **Secured Window**.
=> Fix an issue where scroll to top was not working in Lightning Locker JSUI-2516

src/models/QueryStateModel.ts, src/ui/MissingTerm/MissingTermManager.ts, src/ui/MissingTerm/MissingTerms.ts, unitTests/ui/MissingTermManagerTest.ts, unitTests/ui/MissingTermsTest.ts
https://coveord.atlassian.net/browse/JSUI-2546
So now we update the missing term when the query change.
If the missingTerms are still present in the new query, they will persist.
If not, they are removed from the missing term.
=> JSUI-2546 Update missingTerms to update when the query update

docs/playground/src/PlaygroundConfiguration.ts
https://coveord.atlassian.net/browse/JSUI-2548
Since the `missingTerms` is a new component, it won't work until the reference of the file `CoveoJsSearch.min.js` in `default.hbs` has been updated to the new version
=> JSUI-2548 Fix missingTerms example in the docs

.travis.yml
https://coveord.atlassian.net/browse/JSUI-2567
Headless Chrome is missing a dependency to start
=> JSUI-2567 travis CI missing dependency

src/controllers/DynamicFacetQueryController.ts, unitTests/controllers/DynamicFacetQueryControllerTest.ts
=> JSUI-2462  Remove isInternalQuery flag as backend will manage it on their side

src/ui/Facet/FacetSettings.ts
Use facet's parent element instead of root as boundaries element
When a facet is inside a scroll container the facet setting dropdown was behaving strangely and sometime was hidden.
=> Fix an issue the SalesForce Sidepanel

src/utils/DateUtils.ts
https://coveord.atlassian.net/browse/JSUI-2584
=> JSUI-2584 Use non-capturing group instead of look-behind which is not supported in Firefox

src/rest/AnalyticsEndpointCaller.ts, unitTests/rest/AnalyticsEndpointCallerTest.ts
The access token is not present in the Sitecore UI. Rather it is added by the sitecore server before forwarding the request to the platform. This PR checks if the access token is defined before adding it as a query string param.
https://coveord.atlassian.net/browse/JSUI-2589
=> JSUI-2589 Include token query string param only if defined

package.json, yarn.lock
To allow us to use the new `@examples` annotation to override generated option markup examples in reference documentation.
=> DOC-5650 Upgrade typedoc dependency

src/ui/CategoryFacet/CategoryFacet.ts, src/ui/CategoryFacet/CategoryFacetValuesTree.ts, unitTests/Test.ts, unitTests/ui/CategoryFacet/CategoryFacetTest.ts, unitTests/ui/CategoryFacet/CategoryFacetValuesTreeTest.ts
**The problem:**
When a category facet is selected, performing a search query giving no results causes two query state model (QSM) updates (one for the query, the other for clearing the active category facet). This creates a loop of search queries with no results that prevents us from going back in history.
**The solution:**
There were at least two ideas to solve the issue.
The one I chose was to not update the QSM when there are no values for an active category facet. This means that when another search is done that does give results, the category facet state will be preserved to what it was before. This behaviour matches that of the standard facet.
Another approach might have been to update the QSM with the `silent` option set to `true`. I did not experiment to see if it would work, but …
=> JSUI-2594 Prevent resetting the category facet state when there are no results

sass/_QuerySuggestPreview.scss
https://coveord.atlassian.net/browse/JSUI-2605
Remove Grey background because we could have white background on some image
and added a greyborder when a preview has the focus to see which ose is selected
=> JSUI-2605 CSS tweak for QuerySuggestPreview

src/ui/Templates/TemplateConditionEvaluator.ts, unitTests/ui/TemplateConditionEvaluatorTest.ts
Fixed an error where the regex `TemplateConditionEvaluator.getFieldFromString` would not detect fields with an underscore in their names.
Added more unit tests for the function.
https://coveord.atlassian.net/browse/JSUI-2572
=> Fixed regex used to automatically detect fields to include

src/ui/Omnibox/Omnibox.ts, unitTests/ui/OmniboxTest.ts
There's the possibility to configure components as "external" from the root of the search interface.
In those case, triggering the event from the Omnibox element only would mean it does not get picked up by other components inside the search interface, since they do not have a common ancestor.
https://coveord.atlassian.net/browse/JSUI-2639
=> Trigger events from root if the element is not a descendant of the search interface

src/controllers/QueryController.ts, src/ui/Base/QueryBuilder.ts
TLDR: 
Salesforce Locker service modifies underscore.js module to add `strict mode`;
This means the _.extend function starts throwing when extending object with getter but no setter...
https://coveord.atlassian.net/browse/JSUI-2640
=> Add setter on query builder

src/controllers/DynamicFacetRangeQueryController.ts, src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValues.ts, src/ui/DynamicFacetManager/DynamicFacetManager.ts, unitTests/ui/DynamicFacet/DynamicFacetRangeTest.ts, unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValuesTest.ts
https://coveord.atlassian.net/browse/JSUI-2652
Because we get send ranges and freezeCurrentValue = true, we sometimes get empty idle values back, which we should not display, but need to keep in our "current values". Added a filter for not rendering them.
=> JSUI-2652 Don't display facet values that are "idle" and without results

src/ui/ResponsiveComponents/ResponsiveTabs.ts, unitTests/ui/ResponsiveComponents/ResponsiveTabsTest.ts
This solve an issue where a search interface is initialize while being hidden (client height & width 0).
See the video in the linked issue.
When the search interface is hidden, we will now add the tab to the dropdown by default.
This way, tabs would be in responsive mode when shown again.
=> Add tab to dropdown when clientWidth is 0 JSUI-2645

src/ui/Analytics/PendingSearchEvent.ts, src/ui/ResultList/ResultList.ts, src/ui/SearchAlerts/SearchAlerts.ts, src/utils/DomUtils.ts, unitTests/utils/DomUtilsTest.ts
This goal of this change is to make the search-ui compatible with client promise polyfills that do not support the `.finally` method.
=> JSUI-2659 Convert.finally() calls to async/await

src/ui/DidYouMean/DidYouMean.ts, unitTests/ui/DidYouMeanTest.ts
The corrected word in the DidYouMean message was always appended at the end up until now.
With this change, it will now be possible to change the location of the corrected word in the by specifying a custom localized string containing a placeholder in the desired position.  
https://coveord.atlassian.net/browse/JSUI-2679
=> JSUI-2679 Pass corrected word to localized string placeholder processing utility

src/ui/SearchButton/SearchButton.ts, src/ui/Searchbox/Searchbox.ts, unitTests/ui/SearchButtonTest.ts
**Problem**
When there are two or more searchboxes in the page, if a user clicks the search button of any other than the first searchbox, they will need to press twice to send the query.
**Cause**
The reason is the BuildingQuery event is handled first by the first searchbox in the page. It adds it's old query and blocks further additions (see file `QueryBoxQueryParameters.ts`).
When the second searchbox processes the event, it is not able to add it's query. It does update the QSM though, synchronizing it's query with the first searchbox. Since the query is now synchronized across both searchboxes, on the second click, the intended keywords are sent.
**Solution**
When the search button is clicked, we sync all searchboxes with the new query using the QSM, before executing the query. …
=> JSUI-2682 Update QSM with searchbox query before executing query on SearchButton click

gulpTasks/definition.js, package.json, src/magicbox/MagicBox.ts, src/magicbox/SuggestionsManager.ts, src/ui/QuerySuggestPreview/QuerySuggestPreview.ts, src/utils/Utils.ts, unitTests/magicbox/SuggestionsManagerTest.ts, unitTests/ui/QuerySuggestPreviewTest.ts
https://coveord.atlassian.net/browse/JSUI-2685
Since there is a circular dependency between `SuggestionsManager` and `QuerySuggestPreview` that prevents lazy loading, creation of search result previews was delegated to `SuggestionsManager`. `QuerySuggestPreview` is now only responsible for feeding barebones result previews in response to an event (`PopulateSearchResultPreviews`).
To test `QuerySuggestPreview`, here's my test environment:
```html
<head>
...
<script>
document.addEventListener('DOMContentLoaded', function () {
Coveo.$$(document.body).on('doneBuildingQuery', (_, args) => {
args.queryBuilder.fieldsToInclude = undefined;
args.queryBuilder.includeRequiredFields = false;
});
Coveo.SearchEndpoint.configureCloudV2Endpoint("coveodemocommerceqmqaepc4", /* TOKENHERE */); …
```
=> JSUI-2685 Move generation of search result previews to SuggestionsManager

pages/DynamicsCrm.html, pages/Salesforce.html, pages/ServiceNow.html, src/ui/Facet/Facet.ts, src/ui/Matrix/Matrix.ts
While these options support any case, I decided to convert to lowercase to keep the validation code in the Interface Editor simpler.
=> JSUI-2689 Convert templates and option docs to use lowercase sort values

src/rest/Query.ts, unitTests/ui/QueryBuilderTest.ts
Following the changes in the commerce rest parameter done in the backend with https://coveord.atlassian.net/browse/SEARCHAPI-4036, the `ICommerceRequest` interface needs to be updated to keep-up with the new specs.
All fields are considered optional because they can be also set in the search token (e.g: a catalogId is mandatory for any of the other field to be there, but it can be set in the search token, so it can be omitted in the query).
=> feat(JSUI-2701): Update commerce fields and tests

src/ui/QuerySuggestPreview/QuerySuggestPreview.ts
Restored the old documentation for `QuerySuggestPreview` then improved it.
https://coveord.atlassian.net/browse/JSUI-2716
=> JSUI-2716 Added documentation for QuerySuggestPreview

sass/_QuerySuggestPreview.scss
A trick used to make the width of the search result previews container responsive caused an issue that prevented any result previews from showing up at all. This PR fixes it by setting the size of that container to 70%.
https://coveord.atlassian.net/browse/JSUI-2746
=> JSUI-2746 Fixed the width of the search result previews container

src/ui/QuerySuggestPreview/QuerySuggestPreview.ts, unitTests/ui/QuerySuggestPreviewTest.ts
Since `QuerySuggestPreview`'s results were affected by search box's sort, this change makes it create its own query from scratch. 
https://coveord.atlassian.net/browse/JSUI-2750
=> JSUI-2750 Made `QuerySuggestPreview` create its own query instead of copying the last one

src/ui/FieldSuggestions/FieldSuggestions.ts, unitTests/ui/FieldSuggestionsTest.ts
When the Searchbox has the `data-trigger-query-on-clear` option set to true, clicking a FieldSuggestion was clearing the searchbox which would trigger an empty string query rather than one with the selected suggestion.
https://coveord.atlassian.net/browse/JSUI-2748
=> JSUI-2748 Prevent clearing Searchbox when clicking a field suggestion

src/ui/CategoryFacet/CategoryFacet.ts, src/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValues.ts, src/ui/DynamicFacet/DynamicFacet.ts, unitTests/ui/CategoryFacet/CategoryFacetTest.ts, unitTests/ui/CategoryFacet/CategoryFacetValues/CategoryFacetValuesTest.ts, unitTests/ui/DynamicFacet/DynamicFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2699
I have deprecated the public documented methods that are now pretty useless internally.
=> JSUI-2699 Cleanup part #3: Add back dependsOn / availableValues / visibleParentValues / selectValue / deselectCurrentValue

sass/_QuerySuggestPreview.scss, src/magicbox/ResultPreviewsManager.ts, strings/strings.json
Re-aligned `QuerySuggestPreview`'s header to the left, highlighted header text and changed header text like such:
https://coveord.atlassian.net/browse/JSUI-2757
=> Removed center alignment on `QuerySuggestPreview`'s header text

src/magicbox/ResultPreviewsManager.ts, src/magicbox/SuggestionsManager.ts, src/ui/QuerySuggestPreview/QuerySuggestPreview.ts, unitTests/magicbox/SuggestionsManagerTest.ts, unitTests/ui/QuerySuggestPreviewTest.ts
`QuerySuggestPreview` was triggering clicks on elements when selected and `ResultPreviewsManager` was triggering `QuerySuggestPreview`'s selected event on click, making duplicate calls to analytics.
https://coveord.atlassian.net/browse/JSUI-2756
=> Removed duplicate analytics click event from `QuerySuggestPreview`

src/ui/QuerySuggestPreview/QuerySuggestPreview.ts, unitTests/ui/QuerySuggestPreviewTest.ts
We were sending  documentPosition:null to UA because we weren't getting the index of the results
https://coveord.atlassian.net/browse/JSUI-2766
=> JSUI-2766 Add firstResult value to get result's index back from the API

src/ui/Pager/Pager.ts, unitTests/ui/PagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2776
You would get an exception for this before. Notice the resultsPerPage component is not used but numberOfResults=12 is set on the interface
=> JSUI-2776 Prevent having a RequestedResultsMax error requesting results over the maximumNumberOfResultsFromIndex value

src/magicbox/ResultPreviewsManager.ts, unitTests/Test.ts, unitTests/magicbox/QueryProcessorTest.ts, unitTests/magicbox/SuggestionsManagerTest.ts, unitTests/misc/EnvironmentTest.ts
Importing lodash was [overwriting the global](https://github.com/lodash/lodash/issues/1798) `_` variable. Since lodash does not have a method called `findWhere`, when certain code paths were executed by the IEditor tests, they failed with: `findWhere is not a function`
The IEditor run-time did not fail though. The reason is the IEditor webpack config uses `ProvidePlugin`, which sets the `_` variable to underscore when building the bundle.
I think we should hotfix this PR because the last release technically contains a breaking change. Any consumers of the search-ui using an underscore-specific method that does not exist on lodash will have a fatal error when upgrading to the latest search-ui.
https://coveord.atlassian.net/browse/JSUI-2780 …
=> JSUI-2780 Convert lodash imports to underscore

src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetBreadcrumb.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValue.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValues.ts, src/ui/DynamicHierarchicalFacet/IDynamicHierarchicalFacet.ts, unitTests/ui/DynamicFacet/DynamicFacetTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetBreadcrumbTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTestUtils.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValuesTest.ts
Renamed clear/reset in order to fit the DynamicFacet's public methods. Would be confusing otherwise. Previously had to follow what the CategoryFacet was doing
=> JSUI-2709 [DynamicHierarchicalFacet] Add analytics and reduce the differences of implementation with DynamicFacet

docs/playground/src/PlaygroundConfiguration.ts, docs/theme/layouts/default.hbs, gulpTasks/doc.js
Update configuration for ErrorReport to enforce a failing request and also references to the latest version of the framework were updated on the html doc template.
I had to add a small css rule because the border of QueryBox and Omnibox wasn't being displayed, because in the last css version the border only gets displayed if the components are inside a Searchbox. Should we add `.magic-box { border: 1px solid #9e9e9e; }` to the `MagicBox.scss` so the border gets displayed even if QueryBox/Omnibox are not inside a Searchbox? Though I understand that is not common to have them stand alone.
https://coveord.atlassian.net/browse/JSUI-2660
=> JSUI-2660 Live example of Error Report/ MissingTerms are broken

.travis.yml, read.version.sh
To be able to support SRI ( https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity ) we need to tweak how we deploy version to the CDN a bit.
Since we normally deploy patch version over existing CDN version to be able to deploy hotfix, it would be impossible for a client to "lock" a version for ever and ever, and to have a valid integrity attribute.
This adds another deploy step (which is an exact copy of the s3 deploy phase we already have) except it also insert the patch version in the URL.
So on every release, we will keep the way we deploy stuff to the CDN ( `/v{major}{minor}` ) but also add a new deploy to `/v{major}{minor}/{patch}` which won't be overwritten on every new patch release.
I also discussed with @fbeaudoincoveo about how we can auto-generate the …
=> JSUI-2783 Re-deploy patch on another bucket folder

src/controllers/DynamicFacetQueryController.ts, src/controllers/DynamicFacetRangeQueryController.ts, src/controllers/DynamicFacetRequestBuilder.ts, src/controllers/DynamicHierarchicalFacetQueryController.ts, src/rest/Facet/FacetRequest.ts, src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicFacet/IDynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts, src/ui/DynamicHierarchicalFacet/IDynamicHierarchicalFacet.ts, unitTests/Test.ts, unitTests/controllers/DynamicFacetQueryControllerTest.ts, unitTests/controllers/DynamicFacetRangeQueryControllerTest.ts, unitTests/controllers/DynamicFacetRequestBuilderTest.ts, unitTests/controllers/DynamicHierarchicalFacetQueryControllerTest.ts
After thinking about it, having a "basic" request builder works pretty well in this situation. The refactor wasn't so big (worst is the renaming of `buildFacetRequest` with the additional parameter).
Thanks @olamothe for the suggestion!
=> JSUI-2785 Add filterFacetCount to the FacetRequest

src/ui/FacetValueSuggestions/FacetValueSuggestions.ts, src/ui/FacetValueSuggestions/FacetValueSuggestionsProvider.ts, unitTests/ui/FacetValueSuggestionsProviderTest.ts
Add an expression property to FacetValueSuggestions
Update FacetValueSuggestionProvider to append the expression in queryOverride
Add unit test
https://coveord.atlassian.net/browse/JSUI-2627
=> JSUI-2627 The FacetValueSuggestions component is missing a data-expression property, creating invalid suggestions for a filtered search interface

src/ui/DynamicFacetManager/DynamicFacetManager.ts, unitTests/ui/DynamicFacetManagerTest.ts
Remove the uncessary logger error that was logged when a facet response was not in the manager. 
https://coveord.atlassian.net/browse/JSUI-2788
=> JSUI-2788 Ignore facets results of dynamic facets outside the manager

sass/_QuerySuggestPreview.scss, src/events/ResultPreviewsManagerEvents.ts, src/magicbox/ResultPreviewsManager.ts, src/magicbox/SuggestionsManager.ts, src/ui/FacetValueSuggestions/FacetValueSuggestions.ts, src/ui/QuerySuggestPreview/QuerySuggestPreview.ts, strings/strings.json, unitTests/magicbox/ResultPreviewsManagerTest.ts, unitTests/magicbox/SuggestionsManagerTest.ts, unitTests/ui/FacetValueSuggestionsTest.ts, unitTests/ui/QuerySuggestPreviewTest.ts
https://coveord.atlassian.net/browse/JSUI-2763
Added compatibility to ensure that suggestions from `FacetValueSuggestion` apply a filter on previews requested by `QuerySuggestPreview`. Also made sure that `ResultPreviewsManager` shows the correct header when suggestions include a field.
There's many other ways of doing this, don't hesitate to criticize heavily!
=> JSUI-2763 – Added compatibility for `QuerySuggestPreview` and `FacetValueSuggestions`

src/ui/QuerySuggestPreview/QuerySuggestPreview.ts, unitTests/ui/QuerySuggestPreviewTest.ts
Firefox couldn't append children to a `script` tag, so this fix changes `QuerySuggestPreview`'s `script` tag for a `div`.
https://coveord.atlassian.net/browse/JSUI-2768
=> Fixed default template for `QuerySuggestPreview` in Firefox

src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicFacetManager/DynamicFacetManager.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts, unitTests/ui/DynamicFacet/DynamicFacetTest.ts, unitTests/ui/DynamicFacetManagerTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2789
=> JSUI-2789 Making sure querySuccess is handled in each dynamic facets before the manager

src/ui/Facet/FacetSettings.ts, unitTests/ui/FacetSettingsTest.ts
https://coveord.atlassian.net/browse/JSUI-2796
Added `Tab` and `Shift + Tab` keyboard navigation for `FacetSettings` along with some accessibility attributes.
=> JSUI-2796 Added keyboard navigation for `FacetSettings`

src/ui/Templates/CoreHelpers.ts, unitTests/ui/CoreHelpersTest.ts
This is essentially just copying what's already been done for the other `highlighting` functions. 
Not sure why it was absent for this one... 🤔 
https://coveord.atlassian.net/browse/JSUI-2799
=> JSUI-2799 Merge options before executing `highlightStreamHTMLv2`

src/magicbox/InputManager.ts, src/magicbox/SuggestionsManager.ts, unitTests/magicbox/SuggestionsManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2801
* Moved some accessibility properties from `Omnibox` to `InputManager`'s `input`
* Changed `Omnibox`'s `role` to `search`
* Changed the role of `InputManager`'s `input` to `combobox`
Those changes were made according to some of Deque's recommendations, which I copied over to the JIRA issue above. I also took some inspiration from Google's and Amazon's search bar which also seemed to follow Deque's recommendation but wrapped their search input in a container with `role="search"`.
=> JSUI-2801 Fixed accessibility for `SearchBox`

src/ui/ResultsPerPage/ResultsPerPage.ts, unitTests/ui/ResultsPerPageTest.ts
https://coveord.atlassian.net/browse/JSUI-2803
Fixed accessibility on the list generated by `ResultsPerPage` according to Deque's recommendations.
=> Fixed accessibility on `ResultsPerPage`'s list

.travis.yml, read.version.sh
* Missing condition to deploy CDN on "all branch" if tagged (the travis.yml condition)
* Fix the regex to extract minor version with more than one number
https://coveord.atlassian.net/browse/JSUI-2817
=> JSUI-2817 Adjust travis CDN deploy for patch version

accessibilityTest/AccessibilityQuickview.ts, lib/modal-box/index.d.ts, src/ui/FocusTrap/FocusTrap.ts, src/ui/Quickview/Quickview.ts, unitTests/Simulate.ts, unitTests/Test.ts, unitTests/ui/FocusTrapTest.ts, unitTests/ui/QuickviewTest.ts
https://coveord.atlassian.net/browse/JSUI-2798
1. Added label to close button
2. Added tab index to close button for keyboard navigation
3. Locked keyboard focus within `QuickView`'s modal while it's open.
4. Added accessibility tests for QuickView
This was tested with Android's TalkBack and doesn't seem to work. Most tutorials and articles online, even when searching specifically for accessible modals, seem to ignore accessibility altogether by detecting the `tab` key. However, some tutorials using ally.js seem to detect focus/blur for the desktop and add `aria-hidden` for mobile accessibility tools, which seems to be a less radical solution than setting `tabindex="-1"` to every focusable element. There is no guarantee that this works with iOS's VoiceOver either, but setting …
=> JSUI-2798 Improved accessibility of `Quickview`

src/ui/Combobox/ComboboxInput.ts, unitTests/ui/Combobox/ComboboxInputTest.ts
https://coveord.atlassian.net/browse/JSUI-2808
Moved the `aria-autocomplete` property from `ComboboxInput`'s `<input>` element to its parent div with `role="combobox"`.
According to W3, it seems like `aria-autocomplete` is meant to be defined in elements with the `combobox` role.
Source: https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html#rps_label_textbox
=> JSUI-2808 Fixed incompatible ARIA property in `DynamicFacetSearch`'s `ComboboxInput`

src/ui/Combobox/ComboboxInput.ts, src/ui/Combobox/ComboboxValues.ts, unitTests/ui/Combobox/ComboboxInputTest.ts, unitTests/ui/Combobox/ComboboxValuesTest.ts
https://coveord.atlassian.net/browse/JSUI-2819
This fixes an issue where using the arrow keys to navigate through `DynamicFacetSearch`'s results while TalkBack is on wouldn't cause TalkBack to speak the new selection. The issue was caused by the lack of a focus on the new selection, which is required for TalkBack to detect the new selection.
This fix makes sure that `DynamicFacetSearch`'s results are focusable and are focused when using the arrow keys.
=> JSUI-2819 Fixed `DynamicFacetSearch`'s keyboard interaction with Android's TalkBack

sass/_SortDropdown.scss, sass/vapor/_Dropdown.scss, src/Eager.ts, src/Lazy.ts, src/ui/Sort/Sort.ts, src/ui/SortDropdown/LazySortDropdown.ts, src/ui/SortDropdown/SortDropdown.ts, unitTests/Test.ts, unitTests/ui/SortDropdownTest.ts, unitTests/ui/SortTest.ts
Here is the most basic approach that implements the SortDropdown by composing an existing `Dropdown` and `Sort` components. I also tried to stick to the current results header look and feel.
The markup looks like this and no options at all for the moment:
```
<div class="CoveoSortDropdown">
<span class="CoveoSort" data-sort-criteria="relevancy" data-caption="Relevance"></span>
<span class="CoveoSort" data-sort-criteria="date descending" data-caption="Newest"></span>
<span class="CoveoSort" data-sort-criteria="date ascending" data-caption="Oldest"></span>
</div>
```
For IEditor, I think it's not necessary to use D&D for the moment and maybe one grid like the one it's being used for _Custom Facet Value Options_ could do the job, but really don't know what option could be more convenient to …
=> JSUI-2478 - SortDropdown component

src/ui/CategoryFacet/CategoryFacetSearch.ts, src/ui/Facet/Facet.ts, src/ui/Facet/FacetSearch.ts, src/ui/Facet/FacetSearchElement.ts, src/ui/Facet/IFacetSearch.ts, unitTests/ui/FacetSearchTest.ts, unitTests/ui/FacetTest.ts
Added `aria-expanded` and `aria-controls` to indicate to accessibility tools that `FacetSearch` is opened.
=> JSUI-2826 Add `aria-expanded` to `FacetSearch`

sass/DynamicFacet/_DynamicFacetValues.scss, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValues.ts, unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValuesTest.ts
https://coveord.atlassian.net/browse/JSUI-2829
According to UX:
=> JSUI-2829 Display collapsed values differently for DynamicFacets

src/ui/ResponsiveComponents/ResponsiveComponentsManager.ts, unitTests/ui/ResponsiveComponents/ResponsiveComponentsManagerTest.ts
Make the `ResponsiveComponentManager.resizeAllComponentsManager` method public.
To help with UTs, I moved the registration of the ResponsiveComponentManager from `ResponsiveComponentManager.register` into the constructor of `ResponsiveComponentManager`
I think it also makes more sense because this prevent a ResponsiveComponentManager to _not_ be registered. 
=> feature(JSUI-2845): Expose ResponsiveComponentManager.resizeAllComponentsManager

src/rest/AccessToken.ts, src/rest/AnalyticsEndpoint.ts, src/ui/Analytics/Analytics.ts, unitTests/rest/AccessTokenTest.ts, unitTests/ui/AnalyticsEndpointTest.ts, unitTests/ui/AnalyticsTest.ts
Manage 400 error in the AnalyticsEndpoint directly.
Stop reinitializing Analytics Client on token renewal.
https://coveord.atlassian.net/browse/JSUI-2842
https://discuss.coveo.com/t/support-00058328-client-is-trying-to-automatically-generate-authentication-token/3162/16
=> JSUI-2842 Analytics Access Token Renewal Fix

src/ui/PrintableUri/PrintableUri.ts, unitTests/ui/PrintableUriTest.ts
https://coveord.atlassian.net/browse/JSUI-2840
* Added the "list" role to `PrintableUri`
* Added the "listitem" role to `PrintableUri`'s items
* Added the "separator" role to `PrintableUri`'s separators
=> JSUI-2840 Made `PrintableUri` accessible

sass/_FullSearchGrid.scss
https://coveord.atlassian.net/browse/JSUI-2855
Before/after:
🤢 
😌 
=> JSUI-2855 Make facet-column padding more adequate for DNE

src/magicbox/InputManager.ts
https://coveord.atlassian.net/browse/JSUI-2859
In this commit (https://github.com/coveo/search-ui/commit/23a0a6c0bc535d627e7614b812302dfeb55ccc6c), I added the `aria-active-option` attribute when trying to give the search bar a similar DOM as search bars from other websites. 
However, W3 only recommends using `aria-activedescendant`.
I could not find any source online recommending to use `aria-active-option` or even any indication that it exists in the first place. I must've added it when trying to mimic other search bars. Given that `aria-active-option` doesn't seem to exist and it's already covered by accessibility tests, are unit tests necessary for this? …
=> JSUI-2859 Fix AXE accessibility error in `InputManager`

src/ui/Facet/Facet.ts, unitTests/ui/FacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2857
This PR removes the `aria-controls` attribute from `FacetSearch`'s checkbox since activating it replaces it with a search bar that already owns the facet search results.
This fixes AXE accessibility errors that were triggered by two `aria-controls` properties owning the same component.
=> JSUI-2857 Removed `aria-controls` attribute from `FacetSearch`'s checkbox

accessibilityTest/AccessibilityDynamicHierarchicalFacet.ts
https://coveord.atlassian.net/browse/JSUI-2858
This fixed `DynamicHierarchicalFacet`'s accessibility tests by making it wait for `defferedQuerySuccess` instead of `querySuccess`.
=> JSUI-2858 Fixed accessibility tests for `DynamicHierarchicalFacet`

accessibilityTest/AccessibilityQuickview.ts
https://coveord.atlassian.net/browse/JSUI-2862
`QuickviewDocument`'s function isn't awaited by `Quickview`'s `open` function. This PR compensates for that by adding a delay before running accessibility tests on a modal.
This fixes one of the accessibility tests error.
=> JSUI-2862 Added delay before running accessibility tests on the Quickview modal

karma.accessibility.test.conf.js
https://coveord.atlassian.net/browse/JSUI-2860
On my computer, only 4 tests would run with `gulp && gulp accessibilityTests` before Chrome would disconnect. This PR fixes the configuration file in case this issue may happen to anybody else.
I'm still not sure whether it's a good or bad idea to update the configuration, since I seem to be the only one experiencing this issue so far. I suspect the issue may be related to me using Vivaldi as my default browser instead of Chrome. Before approving, it might be a good idea to checkout this PR and test it out.
=> JSUI-2860 Fixed accessibility tests configuration

accessibilityTest/AccessibilityFacet.ts, accessibilityTest/ContrastChecker.ts, sass/_FacetSearch.scss, sass/_FacetValues.scss
https://coveord.atlassian.net/browse/JSUI-2853
This PR also adds a new class called `ContrastChecker` to test contrasts, since axe is unable to test contrast on borders or svg icons.
=> JSUI-2853 Improved contrast in Facet and added contrast accessibility tests

src/controllers/LocalStorageHistoryController.ts, src/ui/Base/RegisteredNamedMethods.ts, src/utils/HashUtils.ts, unitTests/MockEnvironment.ts, unitTests/Test.ts, unitTests/controllers/LocalStorageHistoryControllerTest.ts
**Problem**
When redirecting from a stand-alone searchbox to a search page that is using localstorage to manage state, we are using `q` attribute value in local storage to perform the query.
The value in the stand-alone search box is ignored.
**Solution**
With this PR, it is possible to configure history and using localstorage on the stand-alone interface. When the query is set, the value is updated in localstorage and can be retrieved by the main interface on initialization.
=> JSUI-2863 Allow configuring options on StandAloneSearchInterface

src/ui/SearchInterface/SearchInterface.ts, unitTests/MockEnvironment.ts
Seems .replace() is not working for everyone
Relevant documentation here:
https://developer.mozilla.org/en-US/docs/Web/API/Location/replace
https://coveord.atlassian.net/browse/JSUI-2883
=> JSUI-2883 Use Location .assign instead of .replace to add current page to browser history

sass/DynamicFacet/_DynamicFacetValues.scss
https://coveord.atlassian.net/browse/JSUI-2873
=> JSUI-2873 Put a bigger line-height for facet collapsed values

accessibilityTest/AccessibilityOmnibox.ts, accessibilityTest/AccessibilitySearchbox.ts, accessibilityTest/AccessibilitySettings.ts, accessibilityTest/ContrastChecker.ts, accessibilityTest/Test.ts, sass/MagicBox/MagicBox.scss, sass/_SearchButton.scss, sass/_Searchbox.scss, sass/_Settings.scss, sass/_Variables.scss
https://coveord.atlassian.net/browse/JSUI-2881
Improved the contrast on `Searchbox`/`Omnibox` and `Settings`.
The plan wasn't to fix `Settings` at the same time, but Deque's test page doesn't have the `Settings` component in it. Fixing the contrast on the `Searchbox` component without fixing `Settings` visually looked out of place.
The hue and the saturation of the new color is the same as the old one, only the lightness was changed. It doesn't look too different from before and has a passing contrast ratio of 3.4:1.
=> JSUI-2881 Improved contrast on `Searchbox` and `Settings`

src/magicbox/InputManager.ts
The browser was autocompleting the input with it's previous selected text without respecting the righteous JSUI state!
https://coveord.atlassian.net/browse/JSUI-2889
=> JSUI-2889 Add autocomplete=off on the input of the Searchbox

src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValues.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValuesTest.ts
This will prevent the QSM and breadcrumbs to keep the selection if the API returns no values.
https://coveord.atlassian.net/browse/JSUI-2893
=> JSUI-2893 DynamicHierarchicalFacetValues: Clear selected path when getting a new response

gulpTasks/definition.js, package.json, src/rest/BackOffRequest.ts, src/rest/SearchEndpoint.ts, unitTests/rest/BackOffRequestTest.ts, yarn.lock
More than a year ago, I deployed versions of the `exponential-backoff` npm package with missing bin files due to a mistake with Travis-CI.
When people install the search-ui, the installer sometimes does not respect the package-lock version for the `exponential-backoff` package. As a result, they pull a bad version and face errors when they start the project.
e.g. `1.0.5` specified in the lock file is good, but the installer pulls `1.2.0` which is a broken.
By updating the package to the latest, we should avoid this issue.
I will also attempt to [unpublish ](https://www.npmjs.com/policies/unpublish)the packages if possible.
=> JSUI-2892 Update exponential-backoff to latest

sass/coveo-styleguide/scss/controls/_checkboxes.scss
https://coveord.atlassian.net/browse/JSUI-2887
This PR aims to give `DynamicFacet`'s checkboxes a contrast ratio greater than 3:1. However, I've been trying for hours to add an accessibility test to it without success because headless accessibility tests appear to ignore the style applied on this specific component and use the browser's default styling for `button` instead.
Should I merge this without an accessibility test, or should I keep trying to find a way to apply that style?
=> JSUI-2887 Improved the contrast ratio on `DynamicFacet`'s checkboxes

src/ui/Base/Component.ts, src/ui/FormWidgets/Dropdown.ts, src/ui/SortDropdown/SortDropdown.ts, unitTests/ui/DropdownTest.ts, unitTests/ui/SortDropdownTest.ts
```
<div class="CoveoSortDropdown" data-tab="All">
<span class="CoveoSort" data-sort-criteria="relevancy" data-caption="Relevance" data-tab="Some"></span>
<span class="CoveoSort" data-sort-criteria="date descending" data-caption="Newest" data-tab="All"></span>
<span class="CoveoSort" data-sort-criteria="date ascending" data-caption="Oldest" data-tab="All"></span>
</div>
```
on CoveoSortDropdown, data-tab (or data-tab-not) will be stripped. On CoveoSort, the data-tab (or data-tab-not) will be respected.
https://coveord.atlassian.net/browse/JSUI-2884
=> JSUI-2884 Disable tab feature for SortDropdown, fix tab feature for it's children

accessibilityTest/AccessibilityDynamicFacet.ts, accessibilityTest/ContrastChecker.ts, sass/DynamicFacet/_DynamicFacetValues.scss, sass/mixins/_dynamicFacet.scss
https://coveord.atlassian.net/browse/JSUI-2897
This issue aims to give `DynamicFacetValue`'s labels a 4.5:1 contrast ratio while focused.
In addition, this issue makes `ContrastChecker` capable of determining contrast between a transparent foreground and an opaque background.
=> Fixed contrast on `DynamicFacetValue` labels

docs/theme/layouts/default.hbs
Any reason why we aren’t using a relative path for the JSUI version?
https://coveord.atlassian.net/browse/JSUI-2877
=> JSUI-2877 Use relative path for doc JS/CSS

src/utils/AccessibleModal.ts, unitTests/utils/AccessibleModalTest.ts
https://coveord.atlassian.net/browse/JSUI-2879
This PR makes accessible modals reset the keyboard focus back to their original location after they are closed.
=> JSUI-2879 Made modal focus reset on close

.travis.yml, docs/theme/layouts/default.hbs
This will fix the playground
https://coveord.atlassian.net/browse/JSUI-2877
=> JSUI-2877 Add back CDN with the upcoming JSUI version

.travis.yml, accessibilityTest/AccessibilityFacet.ts, accessibilityTest/AccessibilityQuickview.ts, accessibilityTest/AccessibilityYouTubeThumbnail.ts, accessibilityTest/Test.ts, accessibilityTest/Testing.ts, src/ui/Quickview/Quickview.ts, src/ui/YouTube/YouTubeThumbnail.ts, src/utils/AccessibleModal.ts, unitTests/Simulate.ts
https://coveord.atlassian.net/browse/JSUI-2898
This PR attempts to fix inconsistent build results with accessibility tests, which occasionally time out.
The first fix this PR does is to increment the time out for accessibility tests to 15 seconds, since a 10 seconds time out seemed to be barely enough to succeed every test with a 500ms latency.
The second fix this PR does is to remove the delay in `AccessibilityFacet` and replace it with a new function: `afterQuerySelector`.
If this doesn't make builds more consistent, a third fix could be to make tests run up to 3 times when they fail, but a quick search revealed that most information about such a solution involves using the `protractor-retry` package.
**UPDATE**: I discovered that accessibility tests for modals occasionally broke, due …
=> JSUI-2898 Attempted to fix accessibility tests' inconsistencies

src/utils/ResultListUtils.ts, unitTests/utils/ResultListUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-2900
=> JSUI-2900 Should not scroll "to top" when the top of the Search Interface top position is already in the viewport

.travis.yml, accessibilityTest/AccessibilityQuerySummary.ts, accessibilityTest/Test.ts, accessibilityTest/Testing.ts, src/ui/QuerySummary/QuerySummary.ts, unitTests/ui/QuerySummaryTest.ts
https://coveord.atlassian.net/browse/JSUI-2904
This PR makes the "Cancel last action" button generated by `QuerySummary` usable with the keyboard and accessible.
=> JSUI-2904 Fixed accessibility for `QuerySummary`'s no results button

.travis.yml, src/ui/CategoryFacet/CategoryFacet.ts, src/ui/CategoryFacet/CategoryFacetTemplates.ts, unitTests/ui/CategoryFacet/CategoryFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2906
This PR improves the accessibility of `CategoryFacet`'s "all categories" button. It does so by moving its label's `tabindex` to itself and giving itself a role. This makes the element usable with the keyboard's enter key and recognizable by accessibility tools as a button. This also makes this button more consistent with other buttons in `CategoryFacet` whose focus isn't solely on their label.
=> JSUI-2906 Improved accessibility for `CategoryFacet`'s "all categories" button

sass/_FieldTable.scss, sass/_Variables.scss, sass/coveo-styleguide/scss/common/_palette.scss
https://coveord.atlassian.net/browse/JSUI-2905
This PR changes the color of every link to have at-least 3:1 contrast with both black and white. Ultimately, this fixes an issue reported by Deque where contrast isn't great enough between `FieldValue`'s label and value when the value is a link.
=> JSUI-2905 Changed color of links to improve contrast with pitch black labels

.travis.yml, src/ui/Sort/Sort.ts, strings/strings.json, unitTests/ui/SortTest.ts
https://coveord.atlassian.net/browse/JSUI-2868
This PR aims to improve the accessibility for `Sort` components while keeping them as independent as they already are. It does so by making the following improvements:
* Making each `Sort` component into a toggle-able button by giving them a `role="button"` along with the `aria-pressed` property. Sorts are viewed as toggled when their sort criteria is active.
* Giving each `Sort` component with both an ascending and descending state a label that reflects the state they will take when pressed. E.g.: `Sort results by Date in ascending order` instead of `Sort results by Date`.
=> JSUI-2868 Improved accessibility for the `Sort` component

.travis.yml, src/ui/ResultLink/ResultLink.ts, unitTests/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-2910
This PR aims to add redundancy with a `title` attribute to `ResultLink`, providing tooltips in case a link is partially hidden by CSS.
=> JSUI-2910 Added a `title` attribute to `ResultLink`

.travis.yml, pages/All.html, pages/Chatter.html, pages/Confluence.html, pages/Dropbox.html, pages/DynamicsCrm.html, pages/Email.html, pages/GoogleDrive.html, pages/Jira.html, pages/Lithium.html, pages/People.html, pages/Recommendation.html, pages/Salesforce.html, pages/SalesforceCase.html, pages/ServiceNow.html, pages/SharePoint.html, pages/YouTube.html, pages/index.html, sass/_FullSearchGrid.scss
https://coveord.atlassian.net/browse/JSUI-2917
This PR aims to fix an issue where `Logo` and `ResultsPerPage` would swap order visually relatively to their order in the DOM, which also caused the tab order to be wrong (E.g., if `div.CoveoLogo` preceded `div.CoveoResultsPerPage` in the DOM, it would appear after `ResultsPerPage` visually)
This fix tries to be the least impactful by only adding new sections to the default search pages and only adding CSS to those.
=> JSUI-2917 Improved alignment for search results footer

src/ui/Facet/Facet.ts, unitTests/ui/FacetTest.ts
The `this.facetValuesList.get` call functions more like a get or create. We were passing a string rather than the facet value, causing counts to be lost when rendering the list.
=> JSUI-2882 Get value from the list using the passed FacetValue object

.travis.yml, src/ui/Facet/FacetSearchElement.ts, unitTests/ui/FacetSearchTest.ts
https://coveord.atlassian.net/browse/JSUI-2925
=> JSUI-2925 Added `aria-expanded` attribute to `FacetSearchElement`'s input

src/ui/FacetSlider/FacetSlider.ts
https://coveord.atlassian.net/browse/JSUI-2929
=> JSUI-2929 Fix className typo for FacetSlider breadcrumb

.travis.yml, sass/_CategoryFacet.scss, sass/_CategoryFacetSearch.scss, sass/_FacetSearch.scss, sass/_FacetValues.scss, sass/_FacetVariables.scss, src/ui/CategoryFacet/CategoryFacetSearch.ts, src/ui/Facet/FacetSearch.ts, src/ui/Facet/FacetSearchElement.ts, src/ui/Facet/ValueElementRenderer.ts, unitTests/ui/FacetSearchTest.ts, unitTests/ui/ValueElementRendererTest.ts
https://coveord.atlassian.net/browse/JSUI-2928
This PR addresses two issues concerning `Facet`'s and `CategoryFacet`'s search results.
1. `FacetSearch`'s results aren't focused when pressing tab from the search box. In this PR, this is fixed by moving its position in the DOM just below the search box.
2. `FacetSearch`'s results aren't read out by TalkBack and VoiceOver. In this PR, this is fixed by giving labels to results.
=> JSUI-2928 Improved accessibility for `FacetSearch`'s results

.travis.yml, src/ui/Quickview/Quickview.ts, unitTests/ui/QuickviewTest.ts
https://coveord.atlassian.net/browse/JSUI-2932
This PR removes a redundant `tabindex` on `Quickview`'s label that caused its label to be focused instead of the `Quickview` button itself with Voiceover on iOS.
=> JSUI-2932 Removed redundant `tabindex` on `Quickview`'s label

src/controllers/DynamicHierarchicalFacetQueryController.ts, src/rest/Facet/FacetRequest.ts, unitTests/controllers/DynamicHierarchicalFacetQueryControllerTest.ts
https://coveord.atlassian.net/browse/JSUI-2934
There is currently a bug API-side: when another facet has a selected value, the displayed values & count are not affected by the basePath
They have been notified
=> JSUI-2934 Add filterByBasePath=false to the facetRequest

.travis.yml, src/ui/Backdrop/Backdrop.ts, src/ui/Quickview/Quickview.ts, src/ui/YouTube/YouTubeThumbnail.ts, src/utils/AccessibleModal.ts, unitTests/ui/BackdropTest.ts, unitTests/utils/AccessibleModalTest.ts
https://coveord.atlassian.net/browse/JSUI-2935
When a user closes `Quickview`'s modal or `YoutubeThumbnail`'s modal, the focus is expected to jump back to wherever it was before the modal was initially opened.
However, the following issues occurred:
1. On Android, when opening either modal with TalkBack, focus was never returned to its initial location. It seems like this may have been caused by the original location being determined from `document.activeElement`, which was always null on Android.
2. On a mobile device, results are displayed in card view. In card view, `YoutubeThumbnail` elements are replaced with a `Backdrop` element, which open `YoutubeThumbnail`'s modal whenever a card result is clicked anywhere. However, card results aren't focusable. VoiceOver and TalkBack happened …
=> JSUI-2935 Fixed `AccessibleModal`'s focus on close for VoiceOver and TalkBack

src/ui/FieldTable/FieldTable.ts, unitTests/ui/FieldTableTest.ts, unitTests/ui/ThumbnailTest.ts
The issue is intermittent, but sometimes after performing a query, expanding the field table does not work because the scrollHeight computed after a zero-second `setTimeout` returns `0`. Increasing the timeout could have worked, but rather than choosing an arbitrary number, I opted to self-heal when the user clicks to expand.
I initially tried to avoid using a variable, opting instead to retrieve the scroll height every time. I noticed some lag in the animation though, so reverted back to storing the value in memory.
I tried to add a unit test but hit a brick wall with every approach. I was not able to mock the `scrollHeight` property to a value other than `0`.
Edit: I found it's possible to mock read-only properties like `scrollHeight` by using `Object.defineProperty`. I added unit …
=> JSUI-2938 Attempt to self-heal toggleContainer height if falsy

.travis.yml, src/ui/FieldTable/FieldTable.ts, unitTests/ui/FieldTableTest.ts
https://coveord.atlassian.net/browse/JSUI-2937
This PR improves accessibility for `FieldTable` in its toggleable state by making the following changes:
* Giving the "Details" button a "Details" `aria-label`
* Giving the "Details" button an `aria-expanded` attribute
* Giving the "Details" button an `aria-controls` attribute
* Giving the collapsible details container a unique id
=> JSUI-2937 Improved accessibility for `FieldTable`

src/ui/CommerceQuery/CommerceQuery.ts, src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts, src/ui/SearchInterface/SearchInterface.ts, src/ui/SimpleFilter/SimpleFilter.ts, src/ui/SortDropdown/SortDropdown.ts
* Added `@availablesince` tags for components mentioned in March and April 2020 releases.
* Fixed broken link.
=> [DOC-7054] Added availablesince tags for new releases

templates/Email/CardEmailThread.html, templates/GoogleDrive/CardGoogleDrive.html
https://coveord.atlassian.net/browse/JSUI-2936
A previous PR improved the contrast of most templates by changing the heading colors in card templates to be black (like the card on the left) instead of blue (like the card on the right).
Unfortunately, `CardEmailThread` and `CardGoogleDrive` kept the same colors since they explicitly chose their headings' text color using `data-color`. This PR fixes this issue by removing this attribute.
=> JSUI-2936 Removed `data-color` overrides in some templates

src/ui/ResponsiveComponents/ResponsiveTabs.ts, unitTests/ui/ResponsiveComponents/ResponsiveTabsTest.ts
What was changed ?
Added some wizardry to detect if a click originate from the more button or the more dropdown content.
Why was it changed ?
In Salesforce, event target are not available to event listener attached to document.documentElement.
What was tested ?
Keyboard navigation
Mobile navigation
Mouse navigation
Tested in Salesforce
=> JSUI-2945 Fix an issue where the more button was not able to open in Salesforce

src/ui/Facet/Facet.ts, unitTests/ui/FacetTest.ts
https://coveord.atlassian.net/browse/JSUI-2948
When the number of selected/excluded facet values is higher than the numberOfValues option, unselecting/unexcluding a value will hide the last selected/excluded value, because we freeze displayed values on a user action. There is a simple solution, to stop updating the number of values when the facet is supposed to have the same values.
~I'll try to find a way to test this in the UTs although the change didn't make any UT fail 😅. Maybe an integration test might be good for this one too.~ Tests added!
=> JSUI-2948 Stop updating the number of values of a "frozen" Facet

src/ui/Base/InitializationPlaceholder.ts, src/ui/DynamicFacetManager/DynamicFacetManager.ts, src/ui/Facet/Facet.ts, src/ui/ResponsiveComponents/ResponsiveFacetColumn.ts, src/utils/ComponentsTypes.ts, src/utils/DependsOnManager.ts, unitTests/MockEnvironment.ts, unitTests/ui/CategoryFacet/CategoryFacetTest.ts, unitTests/ui/DynamicFacet/DynamicFacetTestUtils.ts, unitTests/ui/DynamicFacetManagerTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTestUtils.ts, unitTests/ui/FacetTest.ts, unitTests/utils/ComponentsTypesTest.ts, unitTests/utils/DependsOnManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2951
Follow up to https://github.com/coveo/search-ui/pull/1486
- Use new method in other relevant parts of the code (duplicate facets, depends on)
- Rename older methods to something less confusing (open to other suggestions)
- Fix many UTs
=> JSUI-2951 Part 2 Use new "getAllFacetsFromSearchInterface" throughout the application

src/ui/Base/InitializationPlaceholder.ts, src/ui/DynamicFacetManager/DynamicFacetManager.ts, src/ui/Facet/Facet.ts, src/ui/ResponsiveComponents/ResponsiveFacetColumn.ts, src/ui/SearchInterface/FacetValueStateHandler.ts, src/ui/SearchInterface/SearchInterface.ts, src/utils/ComponentsTypes.ts, src/utils/DependsOnManager.ts, unitTests/MockEnvironment.ts, unitTests/ui/CategoryFacet/CategoryFacetTest.ts, unitTests/ui/DynamicFacet/DynamicFacetTestUtils.ts, unitTests/ui/DynamicFacetManagerTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTestUtils.ts, unitTests/ui/FacetTest.ts, unitTests/ui/FacetValueStateHandlerTest.ts, unitTests/utils/ComponentsTypesTest.ts, unitTests/utils/DependsOnManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-2951
An improvement upon this PR: https://github.com/coveo/search-ui/pull/1157
The issue is with external components, when they are registered with the SearchInterface but not inside the Dom element.
Question: should I go forward and replace methods that were calling `ComponentsTypes.getAllFacetsInstance` with the goal of getting instances from the root of the SearchInterface?
Should I change the name `ComponentsTypes.getAllFacetsInstance` to something like `ComponentsTypes.getAllFacetsInstanceInElement`?
=> JSUI-2951 Retrieve All facets from the SearchInterface directly instead of looking inside the root element

src/ui/Base/Component.ts, unitTests/ui/ComponentEventsTest.ts
This PR should make it more "standard" across various methods inside `ComponentEvents` how to detect if jQuery should be used for event propagation or not.
It also adds some logic to leverage `Dom.useNativeJavaScriptEvents` as an additional condition/check.
https://coveord.atlassian.net/browse/JSUI-2950
=> Uniformize Component.on/one/trigger jQuery detection

.travis.yml, src/ui/CategoryFacet/CategoryFacetSearch.ts, src/utils/AccessibleButton.ts, unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts, unitTests/utils/AccessibleButtonTest.ts
https://coveord.atlassian.net/browse/JSUI-2952
This PR aims to fix two issues:
1. The aria-expanded attribute should also be represented in `CategoryFacet`'s container, according to Deque
2. `CategoryFacetSearch` wouldn't allow spaces. This was found in a [Discuss post](https://discuss.coveo.com/t/dell-request-facetsearch-missing-in-dynamichierarchicalfacet/3655).
=> JSUI-2952 Fixed spacebar detection and `aria-expanded` attribute for `CategoryFacet`

src/ui/FieldValue/FieldValue.ts, unitTests/ui/FieldValueTest.ts
https://coveord.atlassian.net/browse/JSUI-2815
This PR makes `FieldValue` use its `field` option as a fallback to find a corresponding `Facet`.
=> JSUI-2815 Made `FieldValue` use the `field` option as a fallback

src/ui/Quickview/Quickview.ts, src/utils/AccessibleModal.ts
Changed in what element the QuickView component creates the modal box to use the search interface instead of the document body.
Using the document body causes problems when the search interface is initialized inside a shadow root and the styles are only applied within the shadow dom tree.
Reproduced and tested locally then ran unit tests!
JSUI-2942
PS: Do you think it would be useful to have an additional option to set a specific owner element instead of using the search interface?
=> Changed in what element the quickview creates the modalbox

src/utils/DependsOnManager.ts, unitTests/utils/DependsOnManagerTest.ts
Reason for this change in JIRA:
https://coveord.atlassian.net/browse/JSUI-2960
=> JSUI-2960 Change DependsOn newQuery listener to buildingQuery listener

src/ui/FieldTable/FieldTable.ts, unitTests/ui/FieldTableTest.ts
Small regression introduced on last release. If field table is expanded by default on initial paint, we need to sync toggle height calculation with browser paint/reflow.
https://coveord.atlassian.net/browse/JSUI-2959
=> JSUI-2959 Sync toggle height calculation to animation frame

src/ui/MissingTerm/MissingTerms.ts, unitTests/ui/MissingTermsTest.ts
The searchapi returns absent terms in lower-case, and we were matching them against the query in a case-sensitive manner. This meant that `Hello WORLD` would not match `absentTerms: ['world']`.
This PR
1. Changes the regex to match in a case-insensitive way, and
2. Returns the query term so that the displayed value has the same case, [mimicking the behaviour](https://www.google.com/search?rlz=1C1GCEU_enCA822CA822&ei=x9a5Xr2uHoGo_QaF5YyABw&q=jello+bean+RolluP&oq=jello+bean+RolluP&gs_lcp=CgZwc3ktYWIQAzIHCCEQChCgAToECAAQDToGCAAQDRAeUIIpWNI4YLk8aAFwAHgAgAFuiAHuBJIBAzIuNJgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwj9rZbs8qzpAhUBVN8KHYUyA3AQ4dUDCAw&uact=5) on Google. 
https://coveord.atlassian.net/browse/JSUI-2963
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.her …
=> JSUI-2963 Match absent terms with query case-insensitively, and display query terms

src/ui/ResultLink/ResultLink.ts, unitTests/ui/ResultLinkTest.ts
I opted for the bottom-up fix on the component where the XSS was found.
An alternative would have been to sanitize all the properties of a result in a top-down way, but some concerns were:
1. Impacting performance, `O(numOfResults * propertiesPerResult * lengthOfPropertyValue)`
2. Unintended consequences within JSUI and other parts of the stack (e.g. analytics, ML, SFINT)
3. No security benefit in cases where we are not rendering the string as `innerHtml`
https://coveord.atlassian.net/browse/JSUI-2962
=> JSUI-2962 Encode clickuri before displaying it

src/controllers/HistoryController.ts, unitTests/MockEnvironment.ts, unitTests/controllers/HistoryControllerTest.ts
When a page has no components that are always stateful (e.g. no selected tab, selected sort criteria), and when a user interacts with a stateful component and then reverses the action (e.g. select facet value, followed by unselecting the value), the page scrolls to the top.
This happens because the final url contains a hash, that causes the browser to jump to the top.
Once a hash is in the url, the simplest way to remove it without reloading the page is by using the history API. I switched away from using `window.location.hash`.
The edge-case also revealed bugs with the `initialHashChange` and `ignoreNextHashChange` flags. I added a test for the first, and removed the second.
Ref: [removing a hash from url](https://stackoverflow.com/questions/4508574/remove-hash-from-url/4508751). …
=> JSUI-2966 Fix scroll-to-top by removing hash from url when there is no state

src/ui/Analytics/Analytics.ts, unitTests/ui/AnalyticsTest.ts
**Description**
Before the [recent change](https://github.com/coveo/search-ui/commit/fc7e31e3fd3594763a3338e2d0664f01cd5099e0#diff-d29441841a806633e79db771ddd85d5eL217) to the analytics url, we used to append `/rest` to all specified endpoint urls.
With the new endpoint though, it is not possible to append /rest, because the base url contains it in the middle of the path and ends with `/ua`.
```
// old
'https://usageanalytics.coveo.com' + '/rest' (it's possible to always append /rest)
//new
'https://platform.cloud.coveo.com/rest/ua' (cannot append /rest or shorten the url)
```
This PR brings back the old behaviour for manually specified urls to avoid breaking clients who are updating versions.
**Question**
Should we use this opportunity to deprecate the `endpoint` option on the Analytics …
=> JSUI-2971 Ensure manually specified analytics endpoints end with /rest

CODEOWNERS
https://coveord.atlassian.net/browse/JSUI-2958
Now that we're getting bigger, it's a bit tiresome to add everyone every time to our PRs.
This will automatically add everyone in the Github Search Team to this repo's PRs https://github.com/orgs/coveo/teams/search
Before merging, we should make the team members are all relevant. I don't seem to have rights to edit the team.
More doc on CODEOWNERS here https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
=> JSUI-2958 Add CODEOWNERS

src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
Inline was overriding the placeholder's css
https://coveord.atlassian.net/browse/JSUI-2988
=> JSUI-2988 Use css class to hide search instead of inline css

src/ui/QuerySuggestPreview/QuerySuggestPreview.ts, unitTests/ui/QuerySuggestPreviewTest.ts
https://coveord.atlassian.net/browse/JSUI-2993
Despite the `tab` parameter from the last query being re-used, the `constantExpression` (aka `cq`) generated by the `Tab` component wasn't being re-used.
Since `constantExpression` seems to hold contextual expressions, like the tab's expression, it feels appropriate to re-use it even though it can also be defined with `SearchInterface`'s `expression` and `OmniboxResultList`'s `queryOverride`.
=> JSUI-2993 Made `QuerySuggestPreview` keep the last constant expression

src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueMoreLessButton.ts
The default type of button if 'submit'. In the context of ServiceNow, clicking the button therefore submits the form in which the button is. Changing the type of button to 'button' prevents submitting form on click.
SNOW-349
=> * Add button type to ShowMoreLessButton

src/ui/Base/RegisteredNamedMethods.ts, src/utils/AnalyticsUtils.ts, unitTests/Test.ts, unitTests/ui/AnalyticsTest.ts, unitTests/utils/AnalyticsUtilsTest.ts
The reason ServiceNow would like to be able to add custom actionCauses is to link the search event inside the search page to the use of our "top querry widget" which would potentially be in another page. (Users would click on a top querry on a certain page and be redirected to the search page)
There would be a way to add more actionCause to the actionCauseList on the ServiceNow integration side, but it would be a bit less stable IMO. Adding the addActionCause utility in the search-ui repo and covering it with tests makes it a bit more future proof.
link to a related discuss discussion: https://discuss.coveo.com/t/custom-actioncause/3903/2
SNOW-347
=> + Add an utility to add/remove CustomActionCause

src/ui/AdvancedSearch/AdvancedSearch.ts, src/ui/AuthenticationProvider/AuthenticationProvider.ts, src/ui/Debug/Debug.ts, src/ui/PreferencesPanel/PreferencesPanel.ts, src/ui/Quickview/Quickview.ts, src/ui/RelevanceInspector/RelevanceInspector.ts, src/ui/SearchAlerts/SearchAlerts.ts, src/ui/SearchInterface/SearchInterface.ts, src/ui/ShareQuery/ShareQuery.ts, src/ui/YouTube/YouTubeThumbnail.ts, unitTests/ui/ShareQueryTest.ts
In Service Now' Workspace, the Search Interface is in a shadow root. When created, Modals are added to the document's body, outside of the Shadow Dom, thus not being able to share CSS and JS to the Modal Component. 
The work-around here is to be able to specify, in the Search Interface, to attach all Modals to the Search Interface Component.
2 other points to note: 
1. There was already a possibility (added on May 4th 2020, https://github.com/coveo/search-ui/pull/1489) to specify the component to which to attach the Quickview Modal. This PR would remove that possibility. 
2. Debug Panel and Relevance Inspector do not have a SearchInterface Object because they inherit from _Root Component_ instead of _Component_. I had them attached to the Search Interface, if one present, by default. …
=> + Add possibility to attach modals to search interface

src/ui/FacetRange/FacetRange.ts, unitTests/ui/FacetRangeTest.ts
The label is sent to the API and returned as the lookupValue, in those cases we should prioritize the label.
https://coveord.atlassian.net/browse/JSUI-3006
=> JSUI-3006 Display "label" for FacetRange value when defined.

sass/_FacetSlider.scss, sass/mixins/_slider.scss
Without this rule, you can get weird behaviour if:
* You have a facet slider with "large snapping steps"
* You have a touch screen that is large enough (tablet, for example)
The browser would misunderstand the intention to slide buttons on the slider for wanting to navigate back and forth in the history. Since the gesture requires a lot of lateral movement to happen, you need those two conditions described above.
With this rule, the touch and hold gesture becomes 100% handled by the slider JavaScript code, and behaves correctly.
https://coveord.atlassian.net/browse/JSUI-3008
=> Add touch-action: none; for FacetSlider

src/magicbox/SuggestionsManager.ts, unitTests/magicbox/SuggestionsManagerTest.ts
Without parentheses, "b" always won as long as is was defined 😓 
https://coveord.atlassian.net/browse/JSUI-2991
=> JSUI-2991 Add precedence rules for Suggestions sorting

src/ui/PipelineContext/PipelineContext.ts
The change clarifies a misunderstanding around using the PipelineContext component to customize non-search UA events.
The discuss thread is available [here](https://discuss.coveo.com/t/00061577-context-is-not-passing-for-click-events-in-analytics/3924/16?u=sami_sayegh).
https://coveord.atlassian.net/browse/JSUI-3007
=> JSUI-3007 Improve PipelineContext documentation

src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdownModalContent.ts, unitTests/ui/ResponsiveComponents/ResponsiveDropdownModalContentTest.ts
https://coveord.atlassian.net/browse/JSUI-2997
A bug caused `FacetsMobileMode` to create multiple close buttons when the modal was already opened and resized repeatedly:
=> JSUI-2997 Prevented the creation of multiple close buttons with `FacetsMobileMode`

sass/_CategoryFacet.scss, sass/_CategoryFacetSearch.scss, sass/_FacetSearch.scss, src/ui/CategoryFacet/CategoryFacet.ts, src/ui/CategoryFacet/CategoryFacetSearch.ts, src/ui/Facet/FacetSearch.ts, src/ui/Facet/FacetSearchElement.ts, src/ui/Facet/IFacetSearch.ts, unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts, unitTests/ui/CategoryFacet/CategoryFacetTest.ts
Normal/old behaviour
displaySearchOnTop = true
displaySearchOnTop = true AND displaySearchButton = false
https://coveord.atlassian.net/browse/JSUI-3011
=> [CategoryFacet] Add options to have search on top and display directly the input

accessibilityTest/AccessibilitySmartSnippet.ts, accessibilityTest/Test.ts, accessibilityTest/Testing.ts, sass/_ExplanationModal.scss, sass/_SmartSnippet.scss, sass/_Variables.scss, src/rest/QueryResults.ts, src/ui/Analytics/AnalyticsActionListMeta.ts, src/ui/SmartSnippet/ExplanationModal.ts, src/ui/SmartSnippet/HeightLimiter.ts, src/ui/SmartSnippet/SmartSnippet.ts, strings/strings.json, unitTests/Test.ts, unitTests/TestUtils.ts, unitTests/ui/ExplanationModalTest.ts, unitTests/ui/HeightLimiterTest.ts, unitTests/ui/SmartSnippetTest.ts, unitTests/ui/UserFeedbackBannerTest.ts
Along with those unit tests and accessibility tests, some minor tweaks were made.
For instance, closing a modal by pressing the send button no longer sends both the "reason" analytics and the "modal closed" analytics, it only sends the "reason".
Additionally, the following accessibility changes were made:
=> JSUI-3015 Added unit tests and accessibility tests for `SmartSnippet`

docs/theme/assets/css/coveo-connect-header.css, docs/theme/assets/js/coveo-connect-header.js
[DOC-7591](https://coveord.atlassian.net/browse/DOC-7591)
A clone of the community search page is now hosted on docs.coveo.com; it loads much faster than its connect.coveo.com counterpart.
=> Search box on https://coveo.github.io/search-ui/ should point to https://docs.coveo.com/en/search

src/magicbox/Grammars/Field.ts, unitTests/magicbox/GrammarTest.ts
This part of the query was causing a syntax error:
`[[@foldfoldingfield] @sfdcpublic=Public]` because quotes were added `[@foldfoldingfield] @sfdcpublic="Public]"`
https://coveord.atlassian.net/browse/JSUI-3022
=> JSUI-3022 Treat "[" & "]" as field value delimiter for grammar

src/ui/SmartSnippet/HeightLimiter.ts, src/ui/SmartSnippet/SmartSnippet.ts, unitTests/ui/HeightLimiterTest.ts, unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3023
Sending a query that results in a long snippet, expanding it, then sending a query that results in a small snippet caused `HeightLimiter` to stay resizable due to `scrollHeight` being the max value between the current size of a parent container and the current size of its content.
This PR replaces `scrollHeight` with the content's size.
=> JSUI-3023 Fixed subsequent resizes of `HeightLimiter`

src/ui/ResultLink/ResultLink.ts, unitTests/ui/ResultLinkTest.ts
The original XSS issue is here: https://coveord.atlassian.net/browse/JSUI-2962
The bug is not reproduced because the displayed resultUri is still escaped. We could be more precise and escape if there are still concerns with leaving stuff like <> unescaped in the href
https://coveord.atlassian.net/browse/JSUI-3028
=> JSUI-3028 Stop escaping strings added in the result URI that is used as href

accessibilityTest/AccessibilitySmartSnippet.ts, sass/_ExplanationModal.scss, sass/_SmartSnippet.scss, sass/_Variables.scss, src/ui/FormWidgets/RadioButton.ts, src/ui/SmartSnippet/ExplanationModal.ts, src/ui/SmartSnippet/SmartSnippet.ts, unitTests/ui/ExplanationModalTest.ts
https://coveord.atlassian.net/browse/JSUI-3025
This PR aims to improve the looks of `ExplanationModal` and makes it slightly more accessible.
* For the purpose of accessibility, the orange used had to be darker.
* Although the original close button on the top right corner isn't visible due to being replaced with the "Cancel" button, it's still focusable with the keyboard.
=> JSUI-3025 Improved looks and accessibility of `ExplanationModal`

src/ui/Facet/Facet.ts, src/utils/DependsOnManager.ts, unitTests/ui/FacetTest.ts, unitTests/utils/DependsOnManagerTest.ts
Release `2.8864` onwards introduced a breaking change where Facets configured to display `0` values stopped being displayed.
A client upgrading versions reported the issue. They are using only the facet search box. Their configured field holds ids that users can search through and select from.
This PR brings back the old behavior for just the `CoveoFacet` component.
The behavior of `CategoryFacet` and `DynamicFacet` components is inconsistent with the `CoveoFacet`, but did not change. Configuring `0` values on these facets hides them.
=> JSUI-3043 Display Facet even when number-of-values is 0

src/controllers/QueryController.ts, src/ui/Recommendation/Recommendation.ts, src/ui/SearchInterface/SearchInterface.ts, unitTests/controllers/QueryControllerTest.ts, unitTests/ui/InitializationTest.ts, unitTests/ui/RecommendationTest.ts, unitTests/ui/RegisteredNamedMethodsTest.ts, unitTests/ui/SearchInterfaceTest.ts
Action history was always being tracked and sent by the QueryController, even when analytics are disabled.
This PR makes it so actions are only tracked when analytics is enabled.
=> JSUI-3042 Disable action history tracking if analytics is disabled. 

src/ui/ResultList/ResultList.ts, unitTests/ui/ResultListTest.ts
Starting with version `2.7023`, the `data-result-container-selector` option (`result` is singular as in our [documentation](https://coveo.github.io/search-ui/components/resultlist.html)) stopped working. This occurred due to [renaming the option](https://github.com/coveo/search-ui/pull/1167/files#diff-8fe6a6cc8cb32278669d7cb6f08f2291R113) to use the plural `results`.
This PR adds an alias to support the attribute when written with either the singular or plural form.
=> JSUI-3045 Add alias for data-results-container-selector

sass/_FacetFooter.scss
Since divs are `display: block` by default, I found an opportunity to simplify. There is no need to specify the rule in CSS, which ends up overriding a `display:none` set when the Facet is collapsed. See [this discuss post](https://discuss.coveo.com/t/coveofacet-can-get-unwanted-additional-footing-when-collapsed/4256) for additional context behind this change.
=> JSUI-3049 Prevent coveo-facet-empty from overriding display rule

src/ui/Facet/Facet.ts, unitTests/ui/FacetTest.ts
This PR prevents the "select all" button in the facet search from increasing the facet page number.
Also, the showMore function is now smarter, taking into account the number of values in the facet rather than just increasing by 1. See [this Discuss post](https://discuss.coveo.com/t/support-00062406-facet-doesnt-collapse-after-clearing-all-filters/4251/3) for additional info.
=> JSUI-3051 Prevent selectAll from changing the page, adjust showMore logic

src/controllers/DynamicFacetRangeQueryController.ts, unitTests/controllers/DynamicFacetRangeQueryControllerTest.ts
Determined with the API that it's the best way to deal with possible overlap. When no values is selected in the facet, we let the index redefine the new ranges.
https://coveord.atlassian.net/browse/JSUI-3066
=> JSUI-3066 Send currentValues with generateAutomaticRanges only when there is an active value

image/svg/plus.svg, sass/_FacetValues.scss, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts, src/ui/Facet/ValueElement.ts, src/ui/Facet/ValueElementRenderer.ts, src/ui/FormWidgets/Checkbox.ts, src/utils/SVGIcons.ts, strings/strings.json, unitTests/MockElement.ts, unitTests/ui/CheckboxTest.ts, unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts, unitTests/ui/ValueElementRendererTest.ts, unitTests/ui/ValueElementTest.ts
https://coveord.atlassian.net/browse/JSUI-3064
This PR improves accessibility for Facet values by making the following changes:
* Make the aria-label on the following elements static:
* Facet's values' checkboxes
* Facet's values' exclude button
* DynamicFacet's values' checkboxes
* Adds aria-pressed to Facet's values' checkboxes, making them toggleable buttons
* Facet's values' checkboxes
* Facet's values' exclude button
* DynamicFacet's values' checkboxes
* Makes Facet's values' exclude buttons stay visible & toggleable on excluded values
* Removed strings that are no longer used
=> JSUI-3064 Added aria-pressed to facet value checkboxes and exclude buttons

sass/_FacetValues.scss, src/ui/Facet/ValueElementRenderer.ts, unitTests/ui/ValueElementRendererTest.ts
https://coveord.atlassian.net/browse/JSUI-3067
This PR simply exchanges the order of the `FacetValue` caption and count to be in the same order as they are displayed. This helps screen readers read facet values in the expected order.
=> JSUI-3067 Reordered `FacetValue`'s caption and count

sass/DynamicFacet/_DynamicFacetBreadcrumbs.scss, sass/_FacetBreadcrumb.scss, src/ui/DynamicFacet/DynamicFacetBreadcrumbs.ts, src/ui/Facet/BreadcrumbValueElement.ts, src/ui/Facet/BreadcrumbValuesList.ts
Display breadcrumbs as list in the DOM.
I did not modify DynamicHierarchicalFacetBreadcrumb, since these are not "groups", and do not allow you to have more than one filter/one path selected for a given facet. 
So, it's always a unique value in that case.
https://coveord.atlassian.net/browse/JSUI-3077
=> JSUI-3077 Facet breadcrumbs should be represented in the accessibility tree as lists

package.json, sass/_FieldTable.scss, sass/_Variables.scss
https://coveord.atlassian.net/browse/JSUI-3079
Before (IE11):
After (IE11):
Before (Firefox):
After (Firefox):
=> JSUI-3079 Added an outline to clickable field values in Windows high contrast mode

sass/_Breadcrumb.scss, sass/mixins/_breadcrumb.scss
https://coveord.atlassian.net/browse/JSUI-3090
Before (IE11):
After (IE11):
Before (Firefox):
After (Firefox):
=> JSUI-3090 Added outline to clickable breadcrumb elements in Windows high contrast mode

accessibilityTest/AccessibilityPager.ts, accessibilityTest/AccessibilityResultsPerPage.ts, sass/mixins/_pagerList.scss
https://coveord.atlassian.net/browse/JSUI-3082
Before:
After:
=> JSUI-3082 Improved border contrasts for `Pager` and `ResultsPerPage`

accessibilityTest/AccessibilityFacet.ts, sass/_CategoryFacetSearch.scss, sass/_FacetSearch.scss, src/ui/CategoryFacet/CategoryFacetSearch.ts, src/ui/Facet/FacetSearch.ts, src/ui/Facet/FacetSearchElement.ts, unitTests/Test.ts, unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts, unitTests/ui/FacetSearchElementTest.ts, unitTests/ui/FacetSearchTest.ts
https://coveord.atlassian.net/browse/JSUI-3087
Before:
After:
Inspiration (`DynamicFacet`'s search):
=> JSUI-3087 Changed the appearance of the "no results" facet search state

src/ui/CategoryFacet/CategoryFacet.ts, src/ui/QuerySummary/QuerySummary.ts, strings/strings.json, unitTests/ui/QuerySummaryTest.ts
https://coveord.atlassian.net/browse/JSUI-3062
=> JSUI-3062 Query summary, have a fallback string for when there is no query

src/controllers/QueryController.ts, src/rest/SearchEndpoint.ts, src/ui/Omnibox/QuerySuggestAddon.ts, src/utils/HistoryStore.ts, unitTests/Test.ts, unitTests/controllers/QueryControllerTest.ts, unitTests/ui/QuerySuggestAddonTest.ts, unitTests/utils/HistoryStoreTest.ts
**Problem**
Initializing the coveo.analytics `HistoryStore` with anything other than `CookieStorage` causes the class to delete the actionHistory cookie. Chrome detects this activity, and reports in the lock icon that the coveo-search-ui is using a cookie called `__coveo.analytics.history`. The client saw this and opened a case.
**Approaches that did not work**
I [opened a PR](https://github.com/coveo/coveo.analytics.js/pull/216) in the coveo.analytics repo removing the behaviour. 
However, I wasn't able to build the JSUI project correctly after updating the coveo.analytics package. The build errors stem from unrecognized syntax in the `coveo.analytics` typedefinitions.
To solve this issue, I tried upgrading typescript. However, starting with version 2.9.x, dts-generator stopped …
=> JSUI-3107 Avoiding interacting with cookies when initializing HistoryStore

src/events/ResultPreviewsManagerEvents.ts, src/ui/QuerySuggestPreview/QuerySuggestPreview.ts, unitTests/ui/QuerySuggestPreviewTest.ts
https://coveord.atlassian.net/browse/JSUI-2998
Usage example:
```js
coveoRootElement.addEventListener('buildingResultPreviewsQuery', ({ detail: { query } }) => {
query.q = query.q === 'test' ? 'blah' : query.q;
});
```
=> JSUI-2998 Added building query event for QuerySuggestPreview

src/ui/ResponsiveComponents/ResponsiveComponentsManager.ts, unitTests/ui/ResponsiveComponents/ResponsiveComponentsManagerTest.ts
When a tab has `enableResponsiveMode` set to `false`, other responsive components (e.g. facets) stop being responsive.
This PR fixes the bug by ensuring we always decrement the counter tracking components to initialize.
=> JSUI-3110 Decrement component counter even when a component is not responsive

sass/_SmartSnippet.scss, src/ui/SmartSnippet/SmartSnippet.ts, unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3094
This feature isn't part of the original design, but was requested for a demo with a client. If everybody likes it, it could be merged.
Alternatively, it could also be made optional.
=> JSUI-3094 Added the question above `SmartSnippet`

src/rest/Query.ts, src/rest/SearchEndpoint.ts, src/rest/SearchEndpointInterface.ts, src/rest/SearchEndpointWithDefaultCallOptions.ts, src/ui/ExportToExcel/ExportToExcel.ts, unitTests/MockEnvironment.ts, unitTests/ui/ExportToExcelTest.ts
The url of a GET request sent to the platform can have a max length of 8k characters. Due to the limitation, we used to pick-and-choose what query parameters were sent in the Excel export request. The dynamic facets were not included, causing a bug.
This PR adapts the logic to use a POST request with the full query.
https://coveord.atlassian.net/browse/JSUI-3113
=> JSUI-3113 Adapt ExportToExcel download to send a POST request with the full query

sass/DynamicFacet/_DynamicFacetHeader.scss, src/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderButton.ts, src/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderCollapseToggle.ts, unitTests/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderButtonTest.ts, unitTests/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderCollapseToggleTest.ts
Header buttons were focused on facet select, facet search, omnibox search, etc. Now it's only when explicitly clicking or selecting the toggle with the keyboard.
**Also styles** 
Before:
After:
https://coveord.atlassian.net/browse/JSUI-3137
=> JSUI-3137 Focus on the collapse/expand button only on selection & improve styles

src/ui/QuerySummary/QuerySummary.ts, unitTests/ui/QuerySummaryTest.ts
https://coveord.atlassian.net/browse/JSUI-3148
Won't replace what is used as "snapshot" e.g.
```
<span class="CoveoQuerySummary" data-enable-no-results-found-message="true" data-enable-search-tips="false">
<span class="coveo-show-if-no-results">This won't be replaced by "No result"</span>
</span>
```
=> Only replace noResultsFoundMessage with "No result" when the query is empty

src/ui/Quickview/QuickviewDocumentWords.ts, unitTests/ui/QuickviewDocumentWordsTest.ts
I am not sure whether this fix should be in the JSUI or if it is caused by an issue with the index. The problem occurs when calculating Quickview highlight toggles for a document with the following structure:
```
<span id="CoveoHighlight:1.1.1" style="background-color: #e9bdff">
<coveotaggedword id="CoveoHighlight:2.1.1">FICO Score</coveotaggedword>
</span
<span id="CoveoHighlight:2.2.1" style="background-color: #ffe6b8">FICO</span>
```
1. When processing the document, the first element is the `1.x.x` `span` and we add `FICO Score` as the `1` highlight.
2. The next element is the `2.x.x` `coveotaggedword`. This resolves to an empty string because in the case of `coveotaggedword` elements, the logic looks at the text of child elements of which there are none. Before this PR, this would be …
=> JSUI-3150 Prevent adding highlights containing no text

src/ui/ResultLink/ResultLink.ts, unitTests/ui/ResultLinkTest.ts
A few months ago we added stricter checking on CoveoResultLink urls to prevent XSS. The changes only supported absolute urls. This PR loosens the check to support relative urls,
https://coveord.atlassian.net/browse/JSUI-3151
=> JSUI-3151 Readd support for relative urls in ResultLink

Jenkinsfile, read.version.sh
Docs should publish correctly 🤞 There is logic in the bash script to ensure we only release when the package json version is greater than the latest version on npm.
=> JSUI-3168 Publish docs on tagged commits

build/npm.deploy.js
When publishing the beta package to npm via Jenkins, the process fails due to exceeding the buffer size.
```
(node:4285) UnhandledPromiseRejectionWarning: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
at Socket.onChildStderr (child_process.js:377:14)
at Socket.emit (events.js:198:13)
at addChunk (_stream_readable.js:288:12)
at readableAddChunk (_stream_readable.js:265:13)
at Socket.Readable.push (_stream_readable.js:224:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
```
I could not reproduce the error locally, so I am bumping the buffer from the default of 200 kb to 2 MB in the hopes of resolving the issue on jenkins during the next run.
https://coveord.atlassian.net/browse/JSUI-3173 …
=> JSUI-3173 Increase buffer size by 10x

src/rest/QuestionAnswerResponse.ts, src/ui/SmartSnippet/SmartSnippet.ts, src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts, src/ui/SmartSnippet/SmartSnippetSuggestions.ts, unitTests/ui/SmartSnippetSuggestionsTest.ts, unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3171
`SmartSnippetSuggestions` was already able to render without a main question & answer. However, `SmartSnippet` would still attempt to render when there was only `relatedQuestions`.
=> JSUI-3171 Made it possible to render `SmartSnippetSuggestions` without `SmartSnippet`

sass/_SmartSnippet.scss
https://coveord.atlassian.net/browse/JSUI-3118
I could not reproduce the other issue from this JIRA on Chrome, Firefox and Chromium, which is that pressing "show more" would scroll the page.
This PR adds a margin above the "show more" button to avoid breaking the default browser focus style. We could have our own focus style on it, but the browser's seems fine to me.
=> JSUI-3118 Added a margin above `HeightLimiter`'s "show more" button

sass/_ExplanationModal.scss, src/ui/SmartSnippet/ExplanationModal.ts, unitTests/ui/ExplanationModalTest.ts
https://coveord.atlassian.net/browse/JSUI-3116
`ExplanationModal` should only be visible when "Other" is checked.
=> JSUI-3116 Made the details section of `ExplanationModal` hide itself when disabled

.deployment.config, build/deployment-pipeline.deploy.js, build/tag.utilities.js
I only migrated one s3 upload step when transitioning to the deployment pipeline. There was a second s3 upload step in the travis.yml file however, that uploaded the patch version to a dedicated directory.
Some of our cdn clients ask to reference a version that will never change for security reasons. This second upload into a dedicated directory is for them,
https://coveord.atlassian.net/browse/JSUI-3175
=> JSUI-3175 Upload files to dedicated s3 directory for patch version

src/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeader.ts, src/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderCollapseToggle.ts, src/ui/SimpleFilter/SimpleFilter.ts, unitTests/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderCollapseToggleTest.ts, unitTests/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderTest.ts
There are two fixes in this PR:
1. Dynamic Facet collapse/expand toggle now uses a single element instead of switching focus between two elements. This change causes NVDA to read the aria-label/aria-title after toggling a change.
2. Removed a tabindex so allow navigating between SimpleFilter options with one `tab` instead of two.
https://coveord.atlassian.net/browse/JSUI-3164
=> JSUI-3164 Edit attributes of single DynamicFacet toggle versus switching between two elements

.gitignore, Jenkinsfile, build/github-release.deploy.js, build/tag.utilities.js, package.json, yarn.lock
This PR uploads the search-ui zip file to Github releases. Every beta version will be uploaded, keeping the same condition in [travis.yml](https://github.com/coveo/search-ui/blob/master/.travis.yml#L90). The logic will not upload alpha (nightly) tags.
Alpha commits are detected as those that are tagged, and start with version `2.0.x`. I think our tagging logic in `search-ui version` can be improved in a future PR, removing the `beta` suffix, and adding an `alpha` suffix.
https://coveord.atlassian.net/browse/JSUI-3176
=> JSUI-3176 Upload zip to Github releases

sass/_SmartSnippet.scss, sass/_SmartSnippetSuggestions.scss, src/ui/SmartSnippet/SmartSnippet.ts, src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts, src/ui/SmartSnippet/SmartSnippetCommon.ts, src/ui/SmartSnippet/SmartSnippetSuggestions.ts, unitTests/ui/SmartSnippetSuggestionsTest.ts, unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3100
Most if not all `SmartSnippet` typically started and ended with elements that have margins such as `p` and `ul`. However, in the event that the first or last element didn't have the expected margins, the padding would look wrong.
Additionally, since the `SmartSnippet` uses an `iframe`, the font looks very wrong inside of it by default.
This PR attempts to solve that by introducing a default style that adds the appropriate font family. This PR also removes the top margin of the first element as well as the bottom margin of the last element, transferring the responsibility to the CSS outside the `iframe`.
=> JSUI-3100 Added default styling to SmartSnippet and SmartSnippetSuggestion's anwers

package.json, src/ui/SmartSnippet/SmartSnippet.ts, unitTests/ui/SmartSnippetSuggestionsTest.ts, unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3119
=> JSUI-3119 Introduced an option to limit the height of `SmartSnippet`

src/utils/DependsOnManager.ts, unitTests/utils/DependsOnManagerTest.ts
https://coveord.atlassian.net/browse/JSUI-3166
This resolves a bug where if somebody had three facets where two depend on their parents (e.g., `facet1`, `facet2` [depends on `facet1`], `facet3` [depends on `facet2`]), only one facet would be hidden (in this case, `facet2`).
As it is, DynamicFacets are hidden at two different moment:
1. When initializing the `DependsOnManager`, regardless of whether a dependency is met or not, the facet is hidden (but not disabled).
2. When `QueryEvents.buildingQuery` is triggered, the facet is shown+enabled or hidden+disabled based on whether their dependency is met or not.
However, when `QueryEvents.buildingQuery` is triggered, each facet is responsible for hiding their children (e.g., `facet1` hides `facet2` and `facet2` hides `facet3`). The issue was …
=> JSUI-3166 Allowed multiple levels of dependent DynamicFacets to hide

src/ui/ResultLayoutSelector/ResultLayoutSelector.ts, unitTests/ui/ResultLayoutSelectorTest.ts
Resizing a screen smaller disables the `list` layout by default, and activates either `card` or `table`. When resizing larger though, the original layout is not restored. An experience that starts in `list`, will change to `card` on a smaller screen, and remain there.
This PR keeps the user's preferred layout in memory, and restores it when it becomes available again. However if the user changes the layout in between, the preferred layout is reset and no longer restored.
https://coveord.atlassian.net/browse/JSUI-3165
=> JSUI-3165 Restore layout prior to forced responsive layout change

src/ui/Breadcrumb/Breadcrumb.ts, src/utils/Dom.ts
https://coveord.atlassian.net/browse/JSUI-3141
The `focus` event scrolls the page by default, and `preventScroll` appears to be unsupported in IE11.
This solution, on my computer at-least, behaves the same on Vivaldi/Chromium and Firefox as using the `preventScroll` parameter. However, half the time on IE11, the page scrolls down for a very short moment, making the page feel jittery. I recommend trying this out on IE11 before approving this PR.
=> JSUI-3141 Prevented IE11 from scrolling after removing the last breadcrumb

src/misc/AttachShadowPolyfill.ts, src/ui/SmartSnippet/SmartSnippet.ts, unitTests/Test.ts, unitTests/misc/AttachShadowPolyfillTest.ts, unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3187
There was a bug on certain snippets that caused `SmartSnippet` to sometimes be slightly too small and hide part of the answer.
=> JSUI-3187 Improved SmartSnippet's expanded size

src/ui/Base/QueryBuilder.ts, src/ui/FieldSuggestions/FieldSuggestions.ts, src/ui/Omnibox/Omnibox.ts, src/ui/Querybox/Querybox.ts, src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts, src/ui/ResultsPreferences/ResultsPreferences.ts, strings/strings.json
This PR updates some links that were pointing to the old documentation site.
https://coveord.atlassian.net/browse/JSUI-3198
=> JSUI-3198 Update documentation links; improve string

src/ui/Facet/FacetSearchElement.ts
Accessibility issue opened by American Heart Association.
When the classic facet search is open, tabbing focuses the first search result. When tabbing from the last result, focus shifts to the "show more" button, but the facet search stays open. Similarly, when shift-tabbing from the facet search input, the facet search stays open. This PR closes the facet search when one of this events occur.
I did not feel it was worthwhile to include unit tests for these interactions. If you prefer to have them, I will revisit.
=> JSUI-3199 Hide facet search when tabbing away from input or last result.

gulpTasks/definition.js, lib/coveoanalytics/index.d.ts
**Context**
This change is to solve a bundling issue with upstream projects, in this case IPX. The simplest way to describe the problem:
When a package has both `coveo-search-ui` and `coveo.analytics` as dependencies,
when the ts-loader webpack resolver sees an import from `coveo.analytics`,
it incorrectly assumes that the import's definitions are those in the coveo-search-ui `.d.ts` file.
Since these definitions are out-of-sync with what is actually exported by `coveo.analytics`, ts throws an error saying that an imported function is missing.
**Solution**
Remove the module declaration from the definitions exported by coveo-search-ui so that webpack ts-loader can correctly resolve the import's definitions. I think this is safe and not a breaking change …
=> JSUI-3209 Remove coveo.analytics module declaration

src/controllers/FacetSliderQueryController.ts, unitTests/controllers/FacetSliderQueryControllerTest.ts
To retrieve the "full range" from the index, on first load, when we cannot know for sure what is the full range of the index due to other filters active in the interface, we perform an additional group by requests for the slider ( `groupByRequestForFullRange` ).
It clones the "normal" group by request from the slider facet, and tries to tweak it to remove any filter it might contain, except the `constantQueryOverride` (that one, we still want to apply, since it comes from a Tab/is not dynamic based on user input).
There was a bug when no tab were present with any filter applied, we'd get a completely empty "query override" payload for the `groupByRequestForFullRange`.
When that happens, it defats the whole purpose of that request, since now all the filters from the main query get applied …
=> JSUI-3210 add fallback for full range request when it is completely empty

src/ui/SmartSnippet/SmartSnippet.ts, src/ui/SmartSnippet/UserFeedbackBanner.ts, unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3205
The thank you banner was still being displayed after a new question answer was rendered.
=> JSUI-3205 Reseted thank you banner after a new question answer is rendered

src/ui/Facet/FacetSearchElement.ts
I created a regression when trying to improve keyboard accessibility https://github.com/coveo/search-ui/pull/1707.
- If someone tried to click on a facet search result, the input blur would close the dropdown before the click event could execute.
- Similarly, if someone tabbed with their keyboard to focus on a facet search result, but then decided to click on the result instead of using the Enter key, the result would not be selected.
Before closing the results, I now check first check if the event handler was actually triggered by the keyboard.
=> JSUI-3199 Prevent keyboard accessibility events from overriding mouse click

src/ui/FacetSlider/FacetSlider.ts
https://coveord.atlassian.net/browse/JSUI-3215
The facet slider breadcrumb now uses the same icon as every other facet breadcrumb.
The previous icon was mostly used for facet search and became invisible in the context of breadcrumbs but not in other contexts.
=> JSUI-3215 Changed icon for facet slider

src/ui/Pager/Pager.ts, unitTests/ui/PagerTest.ts
https://coveord.atlassian.net/browse/JSUI-3219
Near the last pages, the `numberOfPages` option wasn't respected anymore. For instance, if `numberOfPages` was 5 and we were on the last page, only 3 buttons would show up.
=> JSUI-3219 Made `Pager`'s `NumberOfPages` consistent near last page

package.json, src/ui/CategoryFacet/CategoryFacetSearch.ts, unitTests/ui/CategoryFacet/CategoryFacetSearchTest.ts, unitTests/ui/FacetSliderTest.ts, unitTests/ui/ResponsiveComponents/ResponsiveComponentsManagerTest.ts, yarn.lock
Updating underscore causes tests that are mocking underscore's `debounce` function, or using jasmine.clock to fail.
I did not find a way to make them pass using `jasmine.clock` or `Promise.resolve`. I also get blocked when trying to override the method using a jasmine spy.
```
debounce is not declared writable or has no setter
```
The simplest solution I found was to let the test run with debounce, and use setTimeout's with the correct delay before asserting.
https://coveord.atlassian.net/browse/JSUI-3213
=> JSUI-3213 update underscore; fix tests

src/utils/StreamHighlightUtils.ts, unitTests/ui/CoreHelpersTest.ts
For the cases where the termsToHighlight  are exactly the same as the phrasesToHighlight  and that the text to highlight starts with a word delimiter, an infinite loop occurs. Validating that there is a unique term to highlight prior to execute the regex fixes the issue. If there's no unique terms to highlight there's no point in running the regex anyway.
https://coveord.atlassian.net/browse/JSUI-3222
https://discuss.coveo.com/t/performance-mem-leaks-issues-with-terms-to-highlights/5604/9
=> Fix infinite loop in highlights for special cases [JSUI-3222]

src/ui/FacetValueSuggestions/FacetValueSuggestions.ts
Added note to the `useQuerySuggestions` option of the `facetValueSuggestions` component following this request: https://coveord.atlassian.net/browse/DOC-8994
=> [DOC-8994] added note to useQuerySuggestions

src/ui/DynamicFacet/DynamicFacetRange.ts
I'm removing this completely rather than leaving it to 'false', because otherwise the generated documentation still indicates that the option is required (see https://coveo.github.io/search-ui/components/dynamicfacetrange.html#options.ranges)
=> [DOC-7768] Remove 'required' from 'ranges' DynamicFacetRange option

src/ui/SearchInterface/SearchInterface.ts, unitTests/ui/StandaloneSearchInterfaceTest.ts
**Context**
Leveraging the `/plan` endpoint introduced a regression where an incorrect action cause started being sent when the redirection stemmed from a user selecting a query suggestion.
Changing the redirection code from sync to async caused the [pendingSearchEvent ](https://github.com/coveo/search-ui/blob/master/src/ui/Analytics/LiveAnalyticsClient.ts#L213) to be cleared, before it was read.
**Solution**
The PR caches the hash before the async plan request is performed.
=> JSUI-3233 Cache hash value to redirect to prior to fetching the execution plan

src/ui/ResultLink/ResultLink.ts, unitTests/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-3240
`ResultLink` didn't support `../` and `./` urls.
=> JSUI-3240 added support for relative urls prefixed with periods in ResultLink

src/ui/SmartSnippet/SmartSnippet.ts, unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3248
Before:
After: 
=> JSUI-3248 resolved relative URLs in smart snippet subtitle

sass/_FacetBreadcrumb.scss, sass/_Variables.scss
https://coveord.atlassian.net/browse/JSUI-3251
Previous story https://github.com/coveo/search-ui/pull/1595 added a transparent outline to the Breadcrumbs (also valid for field values).
The problem is we used the outline to show that the buttons were focused. I did two things here:
- added the underline state to the focus, like it was for the hover
- only added the transparent outline when the use is not focused
Here is an example with red instead of transparent
=> JSUI-3251 fix breadcrumbs focus styling

src/ui/Facet/BreadcrumbValuesList.ts
For the following discuss https://discuss.coveo.com/t/support-00069878-clicking-on-breadcrumb-more-button-set-focus-on-wrong-button/6084/5
Goes along the other PR as well.
The DOM changes a bit, the collapsed values were a list inside of a list, a little weird... 🤔 
https://coveord.atlassian.net/browse/JSUI-3252
=> JSUI-3252 Append collapsed Facet breadcrumbs after Nmore element

src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts
Fixes https://coveord.atlassian.net/browse/DOC-8251
(see https://discuss.coveo.com/t/support-00064043-facet-counts-changed-after-selecting/4770)
=> add notes about the field requirements for filterFacetCount option

src/ui/FieldValue/FieldValue.ts, unitTests/ui/ImageFieldValueTest.ts
https://coveord.atlassian.net/browse/JSUI-3257
Before this change, `srcTemplate`'s `raw` always referred to the last result in the result list.
=> JSUI-3257 Fixed ImageFieldValue's srcTemplate resolution

src/utils/ResultListUtils.ts, unitTests/utils/ResultListUtilsTest.ts
https://coveord.atlassian.net/browse/JSUI-2504
=> JSUI-2504 always use #window.scrollTo to scroll to top of search interface

src/rest/AccessToken.ts, src/rest/SearchEndpoint.ts, src/rest/SearchEndpointInterface.ts, src/rest/SearchEndpointWithDefaultCallOptions.ts, src/ui/AuthenticationProvider/AuthenticationProvider.ts, unitTests/ui/AuthenticationProviderTest.ts
The first PR assumed a single `CoveoAuthenticationProvider` component. This PR makes two adjustments to handle multiple configured providers:
- When a handshake token is found in the url, only the Auth provider matching the active tab in the hash will attempt to exchange.
- During an exchange, if an access token exists, it will be sent as part of the request. The search api will return a new access token that augments the existing privileges. This avoids the UI needing to manage and hot-swap access tokens when a user switches between tabs.
https://coveord.atlassian.net/browse/JSUI-3260
=> JSUI-3260 Support multiple AuthenticationProvider instances configured with data-tab

src/ui/Base/CoveoUnderscore.ts
https://coveord.atlassian.net/browse/JSUI-3263
Basically since version 1.10.0 of underscore, the noConflict method is not available for EcmaScript 6, AMD or CommonJS module system. It’s only available with the “window embed” mode, meaning when you load the code directly in the browser. In CoveoUnderscore, we import it as a module (`import * as _ from 'underscore’;`) and set the imported “_” to the window, without the noConflict method.
A solution, which I implement here, is to add the noConflict method on the “_” we export, reproducing the previous implementation.
PR in underscore https://github.com/jashkenas/underscore/pull/2826 (where you can see the previous implementation)
PR where we bumped https://github.com/coveo/search-ui/pull/1627 (introduced in our release versions 2.9659 to …
=> JSUI-3263 add noConflict method to exported underscore

src/rest/SearchEndpoint.ts, src/ui/AuthenticationProvider/AuthenticationProvider.ts, unitTests/MockEnvironment.ts, unitTests/ui/AuthenticationProviderTest.ts
If the token is invalid, users would need to manually clear localstorage to get the JSUI to redirect.
This PR clears the token. More work would be needed to auto redirect though because the starting api key is no longer in memory when the error is received (the bad request was made with the invalid token).
I could explore storing the key in state. Another option could be to just trigger a refresh using `window.location.reload`.
https://coveord.atlassian.net/browse/JSUI-3269
=> JSUI-3269 Remove token from storage if invalid

sass/DynamicFacet/_DynamicFacet.scss, sass/_CategoryFacet.scss, sass/_Facet.scss, src/utils/DependsOnManager.ts, src/utils/Dom.ts, unitTests/utils/DependsOnManagerTest.ts
The problem was related to using `coveo-hidden` inside dependant facet manager.
Since that is also used to control the visibility for dynamic facet on no results, we'd get a quick flicker when a dependant facet with no results was interacted with: 
* Shortly visible because DependsOnManager would remove `coveo-hidden` class.
* Then invisible because the facet itself would add back the class `coveo-hidden` because there's no result.
https://coveord.atlassian.net/browse/JSUI-3272
=> fix dependant facet flicker on no results

src/ui/AuthenticationProvider/AuthenticationProvider.ts, unitTests/ui/AuthenticationProviderTest.ts
I learned on Friday that the leading `/` was not introduced by Sharepoint, but rather the Angular framework being used to build the app. The Intuit team has fixed the behavior by setting an option on the framework.
In theory, this means we the work-around in the JSUI is no longer needed. This PR removes the lines.
Or do you prefer to keep the logic? If so, then I will rename Sharepoint to Angular for clarity,
=> JSUI-3265 Remove Sharepoint (actually Angular) work-around

src/controllers/LocalStorageHistoryController.ts, src/ui/Analytics/AnalyticsInformation.ts, src/ui/AuthenticationProvider/AuthenticationProvider.ts, src/ui/ResultsPreferences/ResultsPreferences.ts, src/utils/LocalStorageUtils.ts
If the JSUI is running in a third-party context, and access to third-party data is disabled, the JSUI crashes due to the browser throwing an error when it tries to access `localStorage`.
The issue was reported by someone using IPX in Chrome Incognito. Since the JSUI is inside an iframe, the browser considers this JSUI instance third-party. In incognito, third-party access to storage is blocked by default.
This PR adds `SafeLocalStorage` , and replaces direct calls to `localStorage`.
=> JSUI-3275 Add SafeLocalStorage, replace direct calls to localStorage

src/ui/AuthenticationProvider/AuthenticationProvider.ts, unitTests/ui/AuthenticationProviderTest.ts
The Intuit team reported 401s when switching from the non-prod to the prod org. This happened because the JSUI was reading the non-prod access token from localstorage.
This PR suffixes the storage key with the organization, to support multiple orgs on the same domain.
https://coveord.atlassian.net/browse/JSUI-3277
=> JSUI-3277 Prefix access token storage key with organization name

src/ui/Analytics/Analytics.ts, unitTests/ui/AnalyticsTest.ts
There is some history behind this issue:
- Initially, [this PR](https://github.com/coveo/search-ui/pull/1458) transitioned the JSUI to default to using the new UA endpoint.
- This was a breaking change for people upgrading, who were specifying the old UA endpoint. This [was fixed here](https://github.com/coveo/search-ui/pull/1507).
- However, the fix introduced a bug. It assumed manually specified endpoints were pointing to the legacy hipaa endpoint (`https://usageanalyticshipaa.cloud.coveo.com`), but some clients were using it to point to the new hipaa endpoint (`https://platformhipaa.cloud.coveo.com/rest/ua`). The changes would strip `/ua`.
This PR only appends `/rest` if a legacy endpoint is detected. Otherwise, it leaves it intact,
https://coveord.atlassian.net/browse/JSUI-3281 …
=> JSUI-3281 append /rest only if legacy endpoint

src/utils/UrlUtils.ts, unitTests/utils/UrlUtilsTest.ts
When a value is partially encoded, it would not be encoded to avoid double encoding.
However, this created a bug when a value was only partially encoded.
Given a SAML redirect url:
```
https://site.com/?q=hello%20world#t=All
```
The `#` would not be encoded. Query string params after the hash would not be sent to the server, causing the login request to fail.
=> JSUI-3279 when a value is only partially encoded, decode before encoding

src/misc/AttachShadowPolyfill.ts, src/ui/SmartSnippet/SmartSnippet.ts, src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts, src/ui/SmartSnippet/SmartSnippetSuggestions.ts, unitTests/ui/SmartSnippetSuggestionsTest.ts, unitTests/ui/SmartSnippetTest.ts
The iframes cause an issue with this component within Salesforce.
I added an option that defaults to changing nothing, that lets us create a simple div instead of injecting an iframe to display the SmartSnippet and the SmartSnippetSuggestions.
the option is called `withoutFrame` on both these components.
It will just render this instead of an iframe:
`<div class="coveo-shadow-iframe">`
Also added unit tests to test that option
=> JSUI-3283 Smart snippet without iframe

src/ui/ResultLink/ResultLink.ts, src/ui/SmartSnippet/SmartSnippet.ts, src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts, unitTests/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-3292
Additionally, I made made the default ResultLink analytics stay instead of being replaced by SmartSnippet's when their source is clicked.
=> JSUI-3292 Improved analytics for smart snippet source

src/ui/ResultLink/ResultLink.ts, unitTests/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-3296
With this PR, clicking on the source of a SmartSnippet or SmartSnippetSuggestions logs a single click event (`openSmartSnippetSource`/`openSmartSnippetSuggestionSource`). The [last PR](https://github.com/coveo/search-ui/pull/1783) logged `documentOpen`, which is removed from this PR.
=> JSUI-3296 Made SmartSnippet only log 1 analytics event when clicking on source

src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValue.ts, src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearchValueRenderer.ts, unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueTest.ts, unitTests/ui/DynamicHierarchicalFacetSearchValueRendererTest.ts
**Background**
The inclusion filter text was added by this [PR](https://github.com/coveo/search-ui/pull/1607) in response to this [maintenance case](https://coveord.atlassian.net/browse/JSUI-3057).
However, the final result of that PR does not follow the WCAG 2.1 label-in-name recommendation:
> ... the visible label (should) be at the beginning of every non-visible label (e.g. aria-label)
**Context**
Laurie's feedback is that starting every facet value focus announcement with "inclusion filter ..." adds redundancy and unnecessary verbosity for the screen reader users. I think what she's saying makes sense,
This change goes with the [aria-labelledby change](https://github.com/coveo/search-ui/pull/1797). Now, when a user focuses on the first facet value, they will be notified that they are …
=> JSUI-3315 Announce facet value immediately; remove "inclusion filter" phrase

src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValue.ts, src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearchValueRenderer.ts, src/ui/ResultLink/ResultLink.ts, strings/strings.json, unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueTest.ts, unitTests/ui/DynamicHierarchicalFacetSearchValueRendererTest.ts, unitTests/ui/ResultLinkTest.ts
**Context**
A `title` attribute [was added](https://github.com/coveo/search-ui/pull/1448) to result links to allow seeing the full text on hover in case the result link was being clipped ([Discuss](https://discuss.coveo.com/t/add-data-title-for-anchor-tooltip/3424)).
The change caused screen readers to read result links twice, once for the `title` attribute, once for the anchor element text.
`<title> link <anchor link text>`
**Suggested solution**
Specifying an [aria-label](https://github.com/nvaccess/nvda/issues/7841#issuecomment-664912888) prevents screen readers from reading the title attribute. A screen reader will now read:
`Result link <anchor link text>`
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f1 …
=> JSUI-3315 Add aria label on result link to prevent announcing link text twice

gulpfile.js, src/ui/AriaLive/AriaLive.ts, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValue.ts, src/ui/DynamicHierarchicalFacetSearch/DynamicHierarchicalFacetSearchValueRenderer.ts, src/ui/ResultLink/ResultLink.ts, strings/strings.json, unitTests/ui/AriaLiveTest.ts, unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueTest.ts, unitTests/ui/DynamicHierarchicalFacetSearchValueRendererTest.ts, unitTests/ui/ResultLinkTest.ts
With this PR, screen readers will announce when a query is in progress by saying `Updating results`.
Additional context available in issue 6 in the jira,
https://coveord.atlassian.net/browse/JSUI-3315
=> JSUI-3315 notify screen readers when results are being updated

src/ui/DynamicFacet/DynamicFacet.ts, src/ui/Facet/Facet.ts
It was unclear, fields of what type can be used in the `DynamicFacet` and `Facet` components. This led to that a one user tried to use a numerical field in those components and didn't understand why the components wouldn't render.
This PR adds a note that `string` is the only acceptable type for the `field` option.
JIRA: https://coveord.atlassian.net/browse/DOC-9965
=> [DOC-9965] DynamicFacet and Facet: adds a note on the field type

image/svg/filetypes/slack.svg
[WORK-1270](https://coveord.atlassian.net/browse/WORK-1270)
- Fixed Slack Icon Size
=> WORK-1270: slack icon size

gulpTasks/strings.js, gulpfile.js
The `doc` step was running in parallel to the `build`. Sometimes, this would be fine. Other times, the doc step would fail due to missing string files generated by `buildStrings` step part of `build` (see last two merge [build errors on master](https://github.com/coveo/search-ui/commits/master)).
```
ERROR in ./src/BaseModules.ts
(12,33): error TS2307: Cannot find module './strings/DefaultLanguage'.
...
Error: Command `npx webpack --config ./webpack.playground.config.js` failed with exit code 2
```
~~This PR adjusts to run the doc step only after the strings have been created.~~
This PR adjusts to build the strings first, followed by running `build` and `doc` in parallel to not increase the build time by 27 seconds. 
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboar …
=> JSUI-3318 Build doc after building strings

gulpTasks/strings.js, gulpfile.js
The `buildStrings` job uses a file generated by `fileTypes`. This did not show up on CI in the initial PR because the `bin` directory already existed on the machine used to run the build.
The `fileTypes` job now runs before `buildStrings`. I also added a step to clean the bin to prevent such errors in the future,
=> JSUI-3318 build fileTypes before buildStrings 

src/controllers/DynamicFacetQueryController.ts, src/controllers/DynamicFacetRangeQueryController.ts, src/controllers/DynamicFacetRequestBuilder.ts, src/controllers/DynamicHierarchicalFacetQueryController.ts, src/controllers/FacetSearchController.ts, src/controllers/HierarchicalFacetSearchController.ts, src/rest/Facet/FacetSearchRequest.ts, src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts, unitTests/controllers/DynamicFacetQueryControllerTest.ts, unitTests/controllers/DynamicFacetRangeQueryControllerTest.ts, unitTests/controllers/DynamicFacetRequestBuilderTest.ts, unitTests/controllers/DynamicHierarchicalFacetQueryControllerTest.ts, unitTests/controllers/FacetSearchControllerTest.ts, unitTests/controllers/HierarchicalFacetSearchControllerTest.ts, unitTests/rest/SearchEndpointTest.ts
The JSUI is more complex, because the default value of `filterFacetCount` depends on whether folding is being used.
Sharing this state happens on building query. This life cycle is not used by facet search.
I wanted to explore simplifying the default to always be `true`, regardless of whether folding is configured or not.
Do you see this causing any problems?
**Update**
Confirmed with Daniel Lavoie that the logic is flipped. Adjusted the default to always be `true`.
https://coveord.atlassian.net/browse/JSUI-3317
=> JSUI-3317 Send filterFacetCount in search request; adjust default to be true if undefined 

src/ui/Combobox/ComboboxValues.ts, src/utils/HighlightUtils.ts, unitTests/ui/Combobox/ComboboxValuesTest.ts, unitTests/utils/HighlightUtilsTest.ts
**Context**
Facet values were being escaped before render to prevent XSS. However, if a value actually contains one of the dangerous characters (an `&` in Humana's case), then it would appear as `&amp;`.
**Approach**
Instead of escaping and rendering as `innerHtml`, I created DOM elements that hold the text content. If a facet value contains valid html, it will be not be evaluated. The string will be treated as text.
**Further work**
The current PR will solve the client's issue.
However, dynamic facets configured using `filetype` or `objecttype` fields still have the issue because the JSUI has a [special code path](https://github.com/coveo/search-ui/blob/master/src/ui/Facet/FacetUtils.ts#L100) that tries to get value captions, and [escapes the …
=> JSUI-3319 Highlight facet value match without escaping

docs/playground/src/Playground.ts, src/ui/DidYouMean/DidYouMean.ts, src/ui/DynamicFacet/DynamicFacetBreadcrumbs.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetBreadcrumb.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueRenderer.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValues.ts, src/ui/MissingTerm/MissingTermManager.ts, src/ui/MissingTerm/MissingTerms.ts, src/ui/PrintableUri/PrintableUri.ts, src/ui/RelevanceInspector/AvailableFieldsTable.ts, src/ui/RelevanceInspector/ExecutionReportEffectiveIndexQuerySection.ts, src/ui/RelevanceInspector/InlineRankingInfo.ts, src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdownModalContent.ts, src/ui/SimpleFilter/SimpleFilter.ts, src/ui/SmartSnippet/ExplanationModal.ts, src/ui/SmartSnippet/HeightLimiter.ts, src/ui/SmartSnippet/UserFeedbackBanner.ts, src/utils/DebugUtils.ts, unitTests/ui/DynamicFacet/DynamicFacetBreadcrumbsTest.ts
In order to fix the issue we have with the ServiceNow integration using Dynamic facets I needed to add the button type to the button elements of the breadcrumbs. I figured why not add it to all buttons!
Simply, not having `type="button"` on a button element will by default `submit`, so if the JSUI is inside a page-wide form (which is the case for servicenow) it reloads the page when you click on a breadcrumb. It's also good practice to always set the type apparently 😅
https://coveord.atlassian.net/browse/JSUI-3322
=> JSUI-3322 Added type button on all button elements I found

src/ui/AriaLive/AriaLive.ts, strings/strings.json, unitTests/ui/AriaLiveTest.ts
https://coveord.atlassian.net/browse/JSUI-3323
When a user with a screen reader types a search query, this notifies them of how many suggestions are available.
=> JSUI-3323 Added live region updates for search query suggestions

sass/_SmartSnippetSuggestions.scss
The tabindex was already set correctly to -1 along with the other aria attributes, but some children had tabindex=0 (such as the result link). I just hide the content, while keeping the parent visible so it doesn't affect accessibility. 
https://coveord.atlassian.net/browse/JSUI-3326
=> JSUI-3326 hide content of SmartSnippetSuggestion when collapsed

src/ui/Facet/FacetUtils.ts, src/ui/Misc/FileTypes.ts
https://coveord.atlassian.net/browse/JSUI-3321
Dynamic facet values are being localized by both their captions and `l(facetValue)`. The former is okay because those captions are included with facet search calls, but the latter means that values are not always searchable by their displayed name, which causes confusion.
Here are the potential solutions to this:
* Not localizing by facet value at all, only localizing by captions (the option used in this PR)
* May be slightly breaking for existing implementations, since some values that may be localized for them right now would suddenly not be localized.
* Adding all localization to `caption` of `facetSearch` calls
* Dynamically detecting when localized values are displayed and adding their captions to upcoming facet search calls
* …
=> JSUI-3321 Removed generic localization from dynamic facet values

src/controllers/QueryController.ts, unitTests/controllers/QueryControllerTest.ts
**Lots more details here** -> https://coveord.atlassian.net/browse/JSUI-3245
First in a possible series of fixes/improvements.
Basically the way the hash was saved in the local storage was made with an omit, which can be hard to maintain (facets were forgotten, not to mention all the debug properties). And it was a string comparison (had to respect exact order).
Switched to a pick & compared the objects, added tests, should reduce the probability of not using the right search uid when logging analytics.
=> JSUI-3245 Improve comparison of stored query hash

src/ui/DynamicFacet/DynamicFacetRange.ts, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetRangeValueParser.ts, src/ui/DynamicFacet/IDynamicFacetRange.ts, unitTests/ui/DynamicFacet/DynamicFacetValues/DynamicFacetRangeValueParserTest.ts
https://coveord.atlassian.net/browse/JSUI-3329
Something that was possible for the legacy FacetRange but not the new one. The option is undefined by default so there are no breaking changes
=> JSUI-3329 Add numberOfDecimals to DynamicFacetRange

src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdown.ts, src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdownContent.ts, src/ui/ResponsiveComponents/ResponsiveFacetColumn.ts, src/ui/ResponsiveComponents/ResponsiveRecommendation.ts, src/utils/AccessibleModal.ts, unitTests/ui/ResponsiveComponents/ResponsiveDropdownContentTest.ts, unitTests/ui/ResponsiveComponents/ResponsiveDropdownTest.ts, unitTests/ui/ResponsiveFacetColumnTest.ts
Essentially a lot of code delete.
Facet responsive dropdown was built without the AccessibleModal class. Which means that there was no focus trap, and other accessibility features were missing.
This does change how the UI behaves, but I think it's for the best long term regarding accessibility.
https://coveord.atlassian.net/browse/JSUI-3332
=> Use AccessibleModal class for facet dropdown

src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts, unitTests/ui/SmartSnippetSuggestionsTest.ts
https://coveord.atlassian.net/browse/JSUI-3335
I couldn't test accessibility for VoiceOver on iOS due to inconsistencies with iframes, but I tested with VoiceOver on Mac OS and TalkBack on Android and both worked.
=> JSUI-3335 Removed smart snippet suggestion answers from tab order while collapsed

webpack.config.js
**Context**
When the `umdNamedDefine` webpack option is `true`, the amd module is named.
```
// umdNamedDefine = false
define([], factory);
// umdNamedDefine = true
define('Coveo__temporary', [], factory);
```
The option was first set to true in response to a [Sitecore maintenance case](https://coveord.atlassian.net/browse/JSUI-1775).
However, when an amd module is named, the `Coveo` global is not set inside Sharepoint.
**So which is correct?**
Reading through the docs, it feels like we should not name the module. The requirejs documentation [mentions this here](https://requirejs.org/docs/whyamd.html#:~:text=You%20should%20avoid%20naming%20modules%20yourself%2C%20and%20only%20place%20one%20module%20in%20a%20file%20while%20developing.%20However%2C%20for%20tooling%20and%20performance%2C%20a% …
=> JSUI-3337 revert to anonymous amd module

src/ui/ResultList/ResultList.ts
This is a follow-up to an already merged PR https://github.com/coveo/doc_jekyll-public-site/pull/6364
=> [DOC-9232] explains some behavior nuances of the autoSelectFieldsToInclude and fieldsToInclude options

src/ui/Base/Component.ts, src/ui/ResultActions/ResultActionsMenu.ts, unitTests/MockEnvironment.ts, unitTests/ui/ResultActionsMenuTest.ts
When a `ResultActionContext` is instantiated inside a result folding template, it is still not attached to the DOM. The `CoveoResult` element is not found, throwing an error, and not rendering the `ResultActionContext` component.
This PR adjusts the ResultActionContext component to check if it is a child of a folded result template.
https://coveord.atlassian.net/browse/JSUI-3345
=> JSUI-3345 resolve parent element when inside folded result template

src/ui/CategoryFacet/CategoryFacet.ts, src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts, src/ui/Facet/Facet.ts, src/ui/Facet/FacetSettings.ts, src/ui/FacetSlider/FacetSlider.ts, src/ui/ResponsiveComponents/ResponsiveDropdown/ResponsiveDropdown.ts, unitTests/ui/ResponsiveFacetColumnTest.ts
This was a piece that was reworked during maintenance, due to a report with accessibility issues with the facet modal.
It introduced some regressions: 
* Facet modal needlessly closing when doing a selection (all the various `closeModalBox: !ResponsiveComponentsUtils.isSmallFacetActivated($$(this.root))` for all facets)
* Some css issues with zIndex, fixed with calling `close()` properly, which modifies css classes on the dropdown.
https://coveord.atlassian.net/browse/JSUI-3351
=> fix issues related to responsive dropdown rework

sass/DynamicFacet/_DynamicFacetBreadcrumbs.scss, src/ui/DynamicFacet/DynamicFacetBreadcrumbs.ts
https://coveord.atlassian.net/browse/JSUI-3346
The `ul` contained a `h3`, which was reported as an accessibility issue. IMO, I would prefer to avoid having anything readable in a list other than listitems.
The changes to the HTML may be slightly breaking for existing implementations. After this change, the structure of dynamic facet breadcrumbs matches the structure of legacy facet breadcrumbs.
* `ul.coveo-dynamic-facet-breadcrumb.coveo-breadcrumb-item`
* `h3.coveo-dynamic-facet-breadcrumb-title`
* `li.coveo-dynamic-facet-breadcrumb-title`
* `li.coveo-dynamic-facet-breadcrumb-title`
* ...
* `div.coveo-dynamic-facet-breadcrumb.coveo-breadcrumb-item`
* `h3.coveo-dynamic-facet-breadcrumb-title`
* `ul.coveo-dynamic-facet-breadcrumb-values`
* `li.coveo-dynamic-facet-breadcrumb-title`
* …
=> JSUI-3346 Improved accessibility for dynamic facet breadcrumbs

src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValue.ts, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueRenderer.ts, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValues.ts, src/ui/DynamicFacet/IDynamicFacet.ts, unitTests/ui/DynamicFacet/DynamicFacetTest.ts
https://coveord.atlassian.net/browse/JSUI-3347
I didn't fix `DynamicHierarchicalFacet` since it would be more complex to fix, and the loss of focus basically just moves the "next focus" to the first item.
=> JSUI-3347 maintained focus on dynamic facet when values are toggled

src/rest/GroupByRequest.ts, src/ui/CategoryFacet/CategoryFacet.ts, src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts, src/ui/Facet/Facet.ts
Turns out the index can't take in an injection depth below 1000, even if JSUI accepts as low as 0.
https://coveord.atlassian.net/browse/DOC-10356
=> DOC-10356: fix minimum injection depth

src/ui/ResultLink/ResultLink.ts, unitTests/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-3369
A client needs to set `tabindex="-1"` to a result link which contains an image, which is also the approach I recommended for the visual section in Atomic. Unfortunately, the ResultLink always sets the tabindex to 0.
=> JSUI-3369 Prevented ResultLink from overriding tabindex

src/ui/Quickview/Quickview.ts
Someone reported that page on customizing the quickview no longer exists, so I'm removing/updating the links.
=> DOC-10520 remove or update broken links

src/ui/MissingTerm/MissingTerms.ts, unitTests/ui/MissingTermsTest.ts
https://coveord.atlassian.net/browse/JSUI-3373
Update to the last PR https://github.com/coveo/search-ui/pull/1860
Snippet to help test out the feature with sample endpoint
```
Coveo.$$(root).on("preprocessResults", function (e, args) {
args.results.results.forEach(function (result, index) {
// Missing terms "President" and "Zelensky" in query "Ukraine President Zelensky"
// No missing terms in query "Ukraine President.Zelensky"
if (index === 0) {
result.absentTerms = ["President", "Zelensky"];
}
// Missing phrase "President Zelensky" in query "Ukraine President.Zelensky" or "Ukraine President Zelensky"
if (index === 1) {
result.absentTerms = ['"President Zelensky"'];
}
// Missing terms "President" and "Zelensky" in query "Ukraine President Zelensky" (phrase contain terms)
// Missing …
```
=> JSUI-3373 Match with word breaking characters in query

src/ui/Pager/Pager.ts, src/ui/ResultsPerPage/ResultsPerPage.ts, unitTests/ui/PagerTest.ts, unitTests/ui/ResultsPerPageTest.ts
https://coveord.atlassian.net/browse/JSUI-3382
Follow-up to Olivier's PR: https://github.com/coveo/search-ui/pull/1867
[FastPass](https://accessibilityinsights.io/docs/en/web/getstarted/fastpass/) (which uses axe-core) is reporting an error and two clients reported it separately:
(screenshot from Olivier's PR)
The accessibility DOM structure we had for the pager (and similar for the results per page) was like so:
* `ul[role="navigation"]`
* `li[role="button"]`
* `a[aria-hidden][tabindex=-1]`
Technically, since `role` and `aria-hidden` *should* (at-least in my experience so far) override the default roles of their respective elements, this shouldn't count as an interactive element being inside another interactive element. However, I suspect that axe-core dislikes an `a` element being …
=> fix accessibility insights reports

src/controllers/QueryController.ts, unitTests/controllers/QueryControllerTest.ts
This was code that was added last release. Normally, this is all internal logic code (the usage analytics client interface).
However, it seems there's popular custom code that override internal functions on the usage analytics client, deployed at different clients.
And since these module don't implement all the functionalities needed, we get null ref error.
This adds defensive code around this, with hardcoded values. 
https://coveord.atlassian.net/browse/JSUI-3383
=> add preventive code for custom code override usage analytics

src/ui/Base/Component.ts, unitTests/ui/ComponentTest.ts
https://coveord.atlassian.net/browse/JSUI-3392
Didn't add UTs because it would be complicated, but if you think it's very important I can add them. Prior to this fix, `QuerySuggestPreview` didn't work when the search box wasn't a descendant of the search interface (e.g., defined in `externalComponents`). This was caused by the search box being unable to find a search interface to fire its event on.
=> Fixed resolveRoot in external components

src/ui/ResultLink/ResultLink.ts, unitTests/ui/ResultLinkTest.ts
https://coveord.atlassian.net/browse/JSUI-3400
The "Result" label was added in response to a ticket saying that the "title" attribute caused the element's title to be read twice.
IMO, reading the title twice isn't so bad, it seems a lot more like a screen reader error to me than a problem with the UI. We can't remove the title because it gives a useful hint under the cursor, but overriding the label with "Result", in theory, removes the title from every result.
=> JSUI-3400 changed result link aria label

src/ui/ResponsiveComponents/ResponsiveComponentsManager.ts, unitTests/ui/ResponsiveComponents/ResponsiveComponentsManagerTest.ts
In some scenario (when the interface loads and initialize with hidden tabs, for example) , resizing the responsive component only after initialization is not enough, and we need to also hook into after the initial query is performed.
https://coveord.atlassian.net/browse/JSUI-3401
=> resize responsive components once after initial query

src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts, src/ui/Facet/Facet.ts, src/ui/FieldValue/FieldValue.ts, src/ui/FieldValue/IFieldValueCompatibleFacet.ts, unitTests/ui/FieldValueTest.ts
https://coveord.atlassian.net/browse/JSUI-3405
I don't think this is a breaking change, since we couldn't even display hierarchical facet values, the whole path was displayed.
I tested, and value captions work.
* When the value is not selected in the facet OR
* When an ancestor is selected OR
* When the value was selected in the facet, then the field value was clicked
* When the value is selected OR
* When the field value was clicked
=> JSUI-3405 added field values for DynamicHierarchicalFacet

src/ui/SearchButton/SearchButton.ts, unitTests/ui/SearchButtonTest.ts
https://coveord.atlassian.net/browse/JSUI-3407
Any reason why this wasn't the case? 
=> JSUI-2383 Log query in action history when clicking search button

accessibilityTest/AccessibilityQuickview.ts
This kinda revert what you changed @wmannard with https://github.com/coveo/search-ui/commit/145b8dcfed3fbcb9f1b7e616d812fe32c2a8c997
The reason this started to fail was that there was some changes in the documents in the index, and the quickview tests were not specific enough to filter on something more "stable". 
So the random Quickview that got opened would not load quick enough, and axe-core tests would incorrectly report them as un-accessible since it would not get the full iframe with all attributes set properly.
Another solution would have been to simply wait for ~1s before running axe-core. Adding a filter for a specific type of document seems better.
https://coveord.atlassian.net/browse/JSUI-3410
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/ …
=> fix quickview accessibility tests

src/ui/SmartSnippet/SmartSnippet.ts, src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts, src/ui/SmartSnippet/SmartSnippetSuggestions.ts, unitTests/ui/SmartSnippetSuggestionsTest.ts, unitTests/ui/SmartSnippetTest.ts
https://coveord.atlassian.net/browse/JSUI-3414
Copied the doc and option name from ResultLink.
This option causes the source of results to open in a new tab.
=> JSUI-3414 Added alwaysOpenInNewWindow to SmartSnippet and SmartSnippetSuggestions

src/ui/Pager/Pager.ts, src/ui/ResultsPerPage/ResultsPerPage.ts
This was a regression that was introduced by: https://github.com/coveo/search-ui/commit/163e75b1adf6f15454aa279538d8b6d1d3d4d7bd
This PR simply adds the same click listener on the list item itself, with a stop propagation to block double queries if you click precisely on the pagination number directly.
https://coveord.atlassian.net/browse/JSUI-3421
=> add click handler on pager list element

src/ui/HierarchicalFacet/HierarchicalFacet.ts
https://coveord.atlassian.net/browse/JSUI-3420
https://github.com/coveo/search-ui/pull/1897/files#r940654585
Set no label/title because it reads the title of the SVG which is expand/collapse
=> JSUI-3420 add withoutLabelOrTitle for expand/collapse button

src/events/BreadcrumbEvents.ts, src/ui/AdvancedSearch/AdvancedSearch.ts, src/ui/Breadcrumb/Breadcrumb.ts, src/ui/CategoryFacet/CategoryFacet.ts, src/ui/CategoryFacet/CategoryFacetBreadcrumb.ts, src/ui/DynamicFacet/DynamicFacet.ts, src/ui/DynamicFacet/DynamicFacetBreadcrumbs.ts, src/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeader.ts, src/ui/DynamicFacet/IDynamicFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacet.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetBreadcrumb.ts, src/ui/DynamicHierarchicalFacet/IDynamicHierarchicalFacet.ts, src/ui/Facet/BreadcrumbValuesList.ts, src/ui/Facet/Facet.ts, src/ui/FacetSlider/FacetSlider.ts, src/ui/HierarchicalFacet/HierarchicalBreadcrumbValuesList.ts, src/ui/HierarchicalFacet/HierarchicalFacet.ts, src/ui/MissingTerm/MissingTermManager.ts, src/ui/ResultsFiltersPreferences/ResultsFiltersPreferences.ts, src/ui/SimpleFilter/SimpleFilter.ts, src/utils/AccessibilityUtils.ts, unitTests/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderCollapseToggleTest.ts, unitTests/ui/DynamicFacet/DynamicFacetHeader/DynamicFacetHeaderTest.ts, unitTests/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetTestUtils.ts
https://coveord.atlassian.net/browse/JSUI-3432
Facet headings and breadcrumbs had heading levels, which could break the heading hierarchy in other pages. Since simply replacing them with `span`/`div` could be breaking, I added `heading-level` options to override them.
=> JSUI-3432 Made heading levels adjustable

src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueMoreLessButton.ts, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValueRenderer.ts, src/ui/DynamicFacet/DynamicFacetValues/DynamicFacetValues.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValueRenderer.ts, src/ui/DynamicHierarchicalFacet/DynamicHierarchicalFacetValues/DynamicHierarchicalFacetValues.ts, strings/strings.json
https://coveord.atlassian.net/browse/JSUI-3433
I applied [ARIA17](https://www.w3.org/TR/WCAG20-TECHS/ARIA17.html#ARIA17-ex1) by setting the role of the `ul` element which groups facet values to [`group`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role) and removing the [`listitem`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listitem_role) role from `li` elements.
A localization key was missing so I added it.
=> JSUI-3433 Apply ARIA17 to facets and improve localization

src/ui/Templates/CoreHelpers.ts, templates/Slack/SlackMessage.html, templates/Slack/SlackMessageReply.html, templates/Slack/SlackMessageThread.html, unitTests/ui/CoreHelpersTest.ts
[SVCINT-1058](https://coveord.atlassian.net/browse/SVCINT-1058)
Some updates in the Slack JSUI result template to match the changes asked in the ticket. 
Final result
=> SVCINT-1058 update slack result template visual

src/ui/Analytics/AnalyticsActionListMeta.ts, src/ui/SmartSnippet/SmartSnippetCollapsibleSuggestion.ts, unitTests/ui/SmartSnippetSuggestionsTest.ts
https://coveord.atlassian.net/browse/JSUI-3394
This mimicks the new behavior of coveo.analytics and Headless.
=> JSUI-3394 added question and answer to smart snippet suggestions analytics

CODEOWNERS, src/events/OmniboxEvents.ts, src/magicbox/SuggestionsManager.ts, src/ui/AriaLive/AriaLive.ts, unitTests/ui/AriaLiveTest.ts
https://coveord.atlassian.net/browse/JSUI-3458
HTML structure can be different for field suggestions vs query suggestions... What seems to stay consistent is the presence of the suggestion class
=> JSUI-3458 Count all types of suggestions for Aria Live
